### ISSUE TITLE
Error occurred while enabling Citizens v1.2

### ISSUE THREAD

**Issue by ThornsOfire** [CitizensDev/Citizens#1008]
10:14:19 [INFO] [Citizens] Enabling Citizens v1.2
10:14:19 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester,
 trader, wizard
10:14:20 [SEVERE] Error occurred while enabling Citizens v1.2 (Is it up to date?
)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at net.citizensnpcs.Economy.init(Economy.java:21)
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:122)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:336)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232
)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

Plugins:
TimTheEnchanter, MagicCarpet, WorldBorder, Citizens, NoCheatPlus, MinecartRevolution, Buycraft, PorteCoulissante, Spout, Deathnotifier, Multiverse-core, PEX, Simplerestart, Chairs, iConomy, Retractable Bridge, Pexrank, Lockette, mcMMO, MobDisguise, Essentials, Chatmanager, Worldedit, EssentialsSpawn, VanishNoPacket, Guardian, WorldGuard, ChestShop, Factions, SpoutEssentials

craftbukkit-1.2.5-R1.0

**Comment by fullwall** [comment]
Need to download vault.

**Comment by ThornsOfire** [comment]
Ahha much thanks good sir! And duh I'm an idiot lol
