### ISSUE TITLE
i cant even make a npc anymore

### ISSUE THREAD

**Issue by deathrage7243** [CitizensDev/Citizens#1009]
so i just recently got Vault to save all my npcs, and now if i do /npc create deathrage7243 it says 
please report this error: [see console]
Java.lang.NullPointerExeption: null

but i dont have acces to the console but i thought id go ahead and report this myself cause the owner is a lazy bum

**Comment by fzman** [comment]
Thats weird, it doesnt happen to me. Whats you citizens and vault version.

**Comment by deathrage7243** [comment]
i have Citizens 1.2 and Vault 1.2.15 for CB 1.2.5-R1.0 cause the owner just got both and i have the error

21:12:37 [SEVERE] java.lang.NullPointerException
21:12:37 [SEVERE]       at com.iCo6.system.Queried.useMiniDB(Queried.java:92)
21:12:37 [SEVERE]       at com.iCo6.system.Queried.hasAccount(Queried.java:237)
21:12:37 [SEVERE]       at com.iCo6.system.Accounts.exists(Accounts.java:10)
21:12:37 [SEVERE]       at net.milkbowl.vault.economy.plugins.Economy_iConomy6.h
asAccount(Economy_iConomy6.java:226)
21:12:37 [SEVERE]       at net.citizensnpcs.Economy.playerHasEnough(Economy.java
:50)
21:12:37 [SEVERE]       at net.citizensnpcs.Economy.hasEnough(Economy.java:92)
21:12:37 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicC
ommands.java:169)
21:12:37 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
21:12:37 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
21:12:37 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
21:12:37 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
21:12:37 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
uteMethod(CommandsManager.java:500)
21:12:37 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
ute(CommandsManager.java:392)
21:12:37 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:208
)
21:12:37 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:40)
21:12:37 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:166)
21:12:37 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:473)
21:12:37 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:821)
21:12:37 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:781)
21:12:37 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:764)
21:12:37 [SEVERE]       at net.minecraft.server.Packet3Chat.handle(Packet3Chat.j
ava:34)
21:12:37 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:229)
21:12:37 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:113)
21:12:37 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(NetworkLis
tenThread.java:78)
21:12:37 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServe
r.java:551)
21:12:37 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:449)
21:12:37 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:492)
