### ISSUE TITLE
Delivery quests

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#101]
These have a few issues. First, no matter what amount you set, if you do /quest status it will say "Delivering 0 item to whatevernpc" and the number always remains 0. Next, I go to the npc that's supposed to get the delivery and it doesn't seem to register no matter if I left or right click him. I've tried toggling him as a quester, but now if I left/right click it just says that I can only have one quest at a time etc. Also, I'm not sure if this will be a problem in the future or not, but if you're delivering food and you right click with it you will eat the food. Same goes for whatever else items that utilize the right clicking.

Here's my quest in the config file:

Friend_in_need:
    texts:
        description: Please deliver a fish to my friend in the Mora dungeon. He's badly hurt.
        completion: <g>Thank you so much! Have this.
        acceptance: <g>Quest <y>accepted<g>.
    repeatable: false
    objectives:
        '0':
            '0':
                type: delivery
                npcdestination: 20
                materialid: 350
                amount: 1
                message: Thank you so much kind sir! Go back to my friend up above.
    rewards:
        '0':
            type: item
            id: 264
            amount: 20
            take: true

Also if I set the materialid to 0 and the amount to 0 and do /quest status, it gives a null pointer exception and displays this error in the console:

2011-09-11 00:49:48 [SEVERE] java.lang.NullPointerException
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.utils.StringUtils.format(StringUtils.java:249)
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.utils.StringUtils.format(StringUtils.java:245)
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.utils.StringUtils.formatter(StringUtils.java:274)
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.questers.quests.types.DeliveryQuest.getStatus(DeliveryQuest.java:63)
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.questers.QuesterCommands.status(QuesterCommands.java:239)
2011-09-11 00:49:48 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-09-11 00:49:48 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2011-09-11 00:49:48 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2011-09-11 00:49:48 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
2011-09-11 00:49:48 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-11 00:49:48 [INFO] [Citizens] An error occurred whilst sending your error report.
2011-09-11 00:49:48 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-11 00:49:48 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
2011-09-11 00:49:48 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
2011-09-11 00:49:48 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)
2011-09-11 00:49:48 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:352)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:737)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:701)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:694)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
2011-09-11 00:49:48 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by fullwall** [comment]
Delivery quests themselves should work now.
