### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PureTryOut** [CitizensDev/Citizens#1011]
I've recently had this error:

2012-04-26 14:23:50 [SEVERE] java.lang.NullPointerException
2012-04-26 14:23:50 [SEVERE]    at net.citizensnpcs.utils.Metrics.postPlugin(Metrics.java:259)
2012-04-26 14:23:50 [SEVERE]    at net.citizensnpcs.utils.Metrics.access$000(Metrics.java:54)
2012-04-26 14:23:50 [SEVERE]    at net.citizensnpcs.utils.Metrics$1.run(Metrics.java:194)
2012-04-26 14:23:50 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-04-26 14:23:50 [SEVERE]    at java.lang.Thread.run(Thread.java:662)

The server didn't crash and everything else was working fine. Any idea what the problem is?

**Comment by fzman** [comment]
From what i can tell the problem is related to trader npcs, never trusted them always full of bugs.
