### ISSUE TITLE
Guards not working

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#1013]
I have the 1.2 build for bukkit 1.2.5 and when I create a guard it doesn't attack anyone or any mob, here is the error message i get at the server

[WARNING] Task of 'Citizens' generated an exception
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
    at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91)
    at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:522)
    at net.citizensnpcs.permissions.PermissionManager.getGroups(PermissionManager.java:105)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:99)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:142)
    at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:33)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:57)
    at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
    at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
    at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
    at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by ghost** [comment]
If I set it as a soldier It work good is just in bouncer mode that gives this error

**Comment by fzman** [comment]
I have the same problem, it happens when i turn my guard aggro on, when someone attacks the guard he will fight back otherwise hes just a standing npc with no function the problem is related to flag sorting.

**Comment by ghost** [comment]
Well I just resolved the priblem today, I dint had permissions instaled on the server, because on guards you can set them to atack groups, so you need permissions plugins to have the grops so the script can run smoothly without errors

**Comment by fzman** [comment]
Permissions, oh yea groups dammit im so stupid

**Comment by ghost** [comment]
Glad I could help, I just spoted the error by the reeor message refering to me not having permissions to create a bouncer
