### ISSUE TITLE
Cause lag

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#1036]
I start my server running CraftBukkit 1.2.5-R2 :

[INFO] [Citizens] Unable to fetch player map from CraftEntity: players. Conflicting names will do funny things.

Citizens load succeful but cause lag and this error :

[WARN] Failed to query stty columnsjava.lang.InterruptedException
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:503)
at java.lang.UNIXProcess.waitFor(UNIXProcess.java:210)
at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:196)
at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:170)
at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:165)
at jline.internal.TerminalLineSettings.get(TerminalLineSettings.java:69)
at jline.internal.TerminalLineSettings.getProperty(TerminalLineSettings.java:89)
at jline.UnixTerminal.getWidth(UnixTerminal.java:75)
at jline.console.ConsoleReader.drawBuffer(ConsoleReader.java:610)
at jline.console.ConsoleReader.drawBuffer(ConsoleReader.java:629)
at jline.console.ConsoleReader.drawLine(ConsoleReader.java:357)
at org.bukkit.craftbukkit.util.TerminalConsoleHandler.flush(TerminalConsoleHandler.java:26)
at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:106)
at java.util.logging.Logger.log(Logger.java:522)
at java.util.logging.Logger.doLog(Logger.java:543)
at java.util.logging.Logger.logp(Logger.java:659)
at org.bukkit.craftbukkit.LoggerOutputStream.flush(LoggerOutputStream.java:27)
at java.io.PrintStream.write(PrintStream.java:482)
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
at java.io.PrintStream.write(PrintStream.java:527)
at java.io.PrintStream.print(PrintStream.java:669)
at java.io.PrintStream.println(PrintStream.java:806)
at net.minecraft.server.Packet.a(Packet.java:96)
at net.minecraft.server.NetworkManager.h(NetworkManager.java:149)
at net.minecraft.server.NetworkManager.c(NetworkManager.java:268)
at net.minecraft.server.NetworkReaderThread.run(SourceFile:76)

Sorry for my bad english... I'm french

**Comment by ammaraskar** [comment]
That error isn't from Citizens, its caused by the recent addition of jline in craftbukkit.
