### ISSUE TITLE
Error consule

### ISSUE THREAD

**Issue by davc** [CitizensDev/Citizens#1046]
8:03:21 [SEVERE] Error occurred while enabling Citizens v1.2 (Is it up to date?)
8:03:21 java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
8:03:21     at net.citizensnpcs.Economy.init(Economy.java:21)
8:03:21     at net.citizensnpcs.Citizens.onEnable(Citizens.java:122)
8:03:21     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
8:03:21     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
8:03:21     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
8:03:21     at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
8:03:21     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238)
8:03:21     at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:381)
8:03:21     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:368)
8:03:21     at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:197)
8:03:21     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
8:03:21     at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
8:03:21 Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
8:03:21     at java.net.URLClassLoader$1.run(Unknown Source)
8:03:21     at java.net.URLClassLoader$1.run(Unknown Source)
8:03:21     at java.security.AccessController.doPrivileged(Native Method)
8:03:21     at java.net.URLClassLoader.findClass(Unknown Source)
8:03:21     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
8:03:21     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
8:03:21     at java.lang.ClassLoader.loadClass(Unknown Source)
8:03:21     at java.lang.ClassLoader.loadClass(Unknown Source)
8:03:21     ... 12 more

if i use Citizens+valut

8:09:06 [INFO] [Vault] Enabling Vault v1.2.16-b184
8:09:06 [INFO] [Vault[Economy] Essentials Economy found: Waiting
8:09:06 [SEVERE] iConomy6 - If you are using Flatfile storage be aware that iCo6 has a CRITICAL bug which can wipe ALL iconomy data.
8:09:06 [SEVERE] if you're using Votifier, or any other plugin which handles economy data in a threaded manner your server is at risk!
8:09:06 [SEVERE] it is highly suggested to use SQL with iCo6 or to use an alternative economy plugin!
8:09:06 [INFO] [Vault[Economy] iConomy 6 found: Waiting

**Comment by Trewyy** [comment]
This is because in error one you did not have an economy plugin like iConomy, so while Citizens was looking for iConomy/Vault to hook, it couldn't find it, and it resorted to that error.

The error with iConomy saying you could corrupt your server with flatfile is because you should be using MySql to store money, and not flatfile or whatever you are using.
