### ISSUE TITLE
Denizen Interaction error?

### ISSUE THREAD

**Issue by tardreted** [CitizensDev/Citizens#1077]
I created a fully scripted quest denizen but every time anyone on my server right clicks the denizen it wont talk to us, it pops this up on the console.

26.06 22:38:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
26.06 22:38:11 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:601)
26.06 22:38:11 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
26.06 22:38:11 [Server] INFO at sun.reflect.GeneratedMethodAccessor441.invoke(Unknown Source)

I Have tried reloading the server, looking through the denizens config, i found no errors even  on the parser....not sure why this is happening.

**Comment by MinecraftAdmin** [comment]
On an unrelated note, can your denizens be pushed around by players, and their position altered?

**Comment by tardreted** [comment]
yes they can

**Comment by aufdemrand** [comment]
Actually, if you use /denizen stand [bookmark], they will attempt to hold position.

**Comment by MinecraftAdmin** [comment]
That command failed too. It appears the positions of normal npc's can also be altered and there is no fix in sight.
