### ISSUE TITLE
Server Log Error While Enabling Citizens

### ISSUE THREAD

**Issue by Thatotherjanitor** [CitizensDev/Citizens#1087]
Just got this mod. Looks really cool. Unfortunately, I tried to install it, but every time, there's an error that pops up on the log:

182 recipes
27 achievements
16:05:08 [INFO] Starting minecraft server version 1.2.5
16:05:08 [INFO] Loading properties
16:05:08 [INFO] Starting Minecraft server on *:25565
16:05:08 [INFO] This server is running CraftBukkit version git-Bukkit-1.2.5-R1.0
-b2149jnks (MC: 1.2.5) (Implementing API version 1.2.5-R1.0)
16:05:08 [INFO] [Citizens] Loading Citizens v1.2
16:05:08 [INFO] [Privileges] Loading Privileges v1.4.0-b45
16:05:08 [INFO] [DisguiseCraft] Loading DisguiseCraft v2.5
16:05:08 [INFO] [VanishNoPacket] Loading VanishNoPacket v3.10
16:05:08 [INFO] [Privileges] Enabling Privileges v1.4.0-b45
16:05:08 [INFO] [Privileges] Is now enabled.
16:05:08 [INFO] Preparing level "Derp2"
16:05:08 [INFO] Default game type: 0
16:05:09 [INFO] Preparing start region for level 0 (Seed: 2525617506084080286)
16:05:09 [WARNING] ----- Bukkit Auto Updater -----
16:05:09 [WARNING] Your version of CraftBukkit is out of date. Version 1.2.5-R4.
0 (build #2222) was released on Sun Jun 10 01:08:56 EDT 2012.
16:05:09 [WARNING] Details: http://dl.bukkit.org/downloads/craftbukkit/view/0114
9_1.2.5-R4.0/
16:05:09 [WARNING] Download: http://dl.bukkit.org/downloads/craftbukkit/get/0114
9_1.2.5-R4.0/craftbukkit.jar
16:05:09 [WARNING] ----- ------------------- -----
16:05:09 [INFO] Preparing start region for level 1 (Seed: 2525617506084080286)
16:05:10 [INFO] Preparing spawn area: 20%
16:05:10 [INFO] Preparing start region for level 2 (Seed: 2525617506084080286)
16:05:11 [INFO] Preparing spawn area: 57%
16:05:11 [INFO] [Citizens] Enabling Citizens v1.2
16:05:11 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester,
 trader, wizard
16:05:11 [SEVERE] Error occurred while enabling Citizens v1.2 (Is it up to date?
)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at net.citizensnpcs.Economy.init(Economy.java:21)
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:122)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:336)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232
)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
16:05:11 [INFO] [DisguiseCraft] Enabling DisguiseCraft v2.5
16:05:11 [INFO] The CraftBukkit jar has not been modified to support disguise PV
P. To learn about how to activate DisguiseCraft PVP, check the BukkitDev project
 description.
16:05:11 [INFO] DisguiseCraft version 2.5 is enabled!
16:05:11 [INFO] [VanishNoPacket] Enabling VanishNoPacket v3.10
16:05:11 [INFO] [VanishNoPacket] v3.10 loaded.
16:05:11 [INFO] Server permissions file permissions.yml is empty, ignoring it
16:05:11 [INFO] Done (3.028s)! For help, type "help" or "?"
16:05:11 [INFO] [Privileges] Removing old users from users.yml...
16:05:11 [INFO] [Privileges] ... done!

Any ideas?

**Comment by shrinerh** [comment]
I am having the exact same issue. It seems as though everyone else, on the other hand, has it working perfectly. There has to be something we are doing wrong, or some stupid detail that I overlooked. Any help would be appreciated.

**Comment by shrinerh** [comment]
Found the answer! Like I said, just some stupid detail. You have to have Vault installed. Its a simple standalone plugin that helps plugins such as citizens work.

http://dev.bukkit.org/server-mods/vault/
