### ISSUE TITLE
Chunk Unload Error

### ISSUE THREAD

**Issue by MadcowD** [CitizensDev/Citizens#11]
15:28:22 [SEVERE] Could not pass event CHUNK_UNLOAD to Citizens
java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.resources.npclib.creatures.Creatur
eTask
        at net.citizensnpcs.listeners.WorldListen.onChunkUnload(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$50.execute(JavaPluginLoader.java:591)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at net.minecraft.server.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:243)
        at net.minecraft.server.World.doTick(World.java:1719)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by aPunch** [comment]
Known bug in 1.0.9d. Caused by single quotes in your config files.
