### ISSUE TITLE
Citizens 1.x does not work wtih 1.3.1 bukkit

### ISSUE THREAD

**Issue by dogbig** [CitizensDev/Citizens#1107]
2012-08-02 13:53:06 [INFO] Done (10.766s)! For help, type "help" or "?"
2012-08-02 13:53:07 [INFO] [Citizens] Unable to fetch player map from CraftEntity: players. Conflicting names will do funny things.
2012-08-02 13:53:07 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.setGameMode(I)V
    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:18)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:73)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:153)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:279)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$3.run(Citizens.java:149)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:508)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:472)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:404)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by dpodp** [comment]
Getting the same error and noone can connect, server gets error and crashs when first person trys to go on, idk if citizens is whats causing it, but ik that i am getting this exception thrown as well.

**Comment by ghost** [comment]
Having the same problem

**Comment by ThornRage** [comment]
2012-08-02 06:19:50 [INFO] [Citizens] Unable to fetch player map from CraftEntity: players. Conflicting names will do funny things.
2012-08-02 06:19:50 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.setGameMode(I)V
    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:18)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:73)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:153)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:279)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$3.run(Citizens.java:149)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:508)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:472)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:404)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by XxCoolGamesxX** [comment]
Guys Go to http://ci.citizensnpcs.net/job/Citizens/70/ It update for 1.3.1.

**Comment by ThornRage** [comment]
Than you. It works. :)

**Comment by dogbig** [comment]
Found another issue: https://github.com/CitizensDev/Citizens/issues/1109
