### ISSUE TITLE
1.3.1 error when loading npc

### ISSUE THREAD

**Issue by psirusa** [CitizensDev/Citizens#1113]
Loading citizens 1.2 on the 1.3.1 Bukkit dev builds generates this error when attempting to load an npc.  The plugin loads when no npc files are present.  I realize that 1.x is no longer officially supported because of 2.x development, but I figured I'd give you the heads up on this in case you decide to update it for the current release.

18:31:39 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.setGameMode
(I)V
        at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java
:37)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java
:153)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:279)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$3.run(Citizens.java:149)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by sandrofigo** [comment]
same problem :(
