### ISSUE TITLE
Could not pass event EntityTargetEvent to Citizens

### ISSUE THREAD

**Issue by mudgw2** [CitizensDev/Citizens#1153]
Citizens 2.0 posted 9/2/12 results in this error:

2012-09-02 00:37:16 [INFO] [Citizens] Metrics started.
2012-09-02 00:37:16 [SEVERE] Could not pass event EntityTargetEvent to Citizens
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityTargetEvent(CraftEventFactory.java:464)
    at net.minecraft.server.PathfinderGoalMeleeAttack.c(PathfinderGoalMeleeAttack.java:59)
    at net.minecraft.server.PathfinderGoalSelector.a(PathfinderGoalSelector.java:62)
    at net.minecraft.server.EntityLiving.bc(EntityLiving.java:1216)
    at net.minecraft.server.EntityLiving.d(EntityLiving.java:1091)
    at net.minecraft.server.EntityIronGolem.d(EntityIronGolem.java:64)
    at net.minecraft.server.EntityLiving.h_(EntityLiving.java:447)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
    at net.minecraft.server.World.tickEntities(World.java:1125)
    at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.IllegalArgumentException: The validated object is null
    at org.apache.commons.lang.Validate.notNull(Validate.java:222)
    at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:143)
    at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:150)
    at net.citizensnpcs.EventListen.onEntityTarget(EventListen.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 20 more

Occured after adding sentry.jar and creating a sentry NPC for the first time.  The console spams this error.

**Comment by mudgw2** [comment]
MC Server vers and craftbukkit vers:
7:00:29 AM [INFO] Starting minecraft server version 1.3.2
7:00:29 AM [INFO] Default game type: SURVIVAL
7:00:30 AM [INFO] This server is running CraftBukkit version git-Bukkit-1.3.2-R0.1-4-gd08e620-b2358jnks (MC: 1.3.2) (Implementing API version 1.3.2-R0.2-SNAPSHOT)

**Comment by ghost** [comment]
Same error here, but we didn't spawn a sentry NPC. It just happened, using same Craftbukkit and server version.

**Comment by ImAPorpoise** [comment]
Same error on mine.

**Comment by Sk8Sanctified** [comment]
Similar error here, http://pastie.org/4660545 

I added the two types, CitiTrader and Denizen. 

Bukkit v1.3.2 r1.0

**Comment by jrbudda** [comment]
Fixed in latest builds

**Comment by Azure27** [comment]
having the same problems it happens when creating new npcs when there are already spawned npc sentries
