### ISSUE TITLE
Random errors at Citizens 2

### ISSUE THREAD

**Issue by Tombik** [CitizensDev/Citizens#1157]
Hi, i¨m getting this error sometimes:

2012-09-04 16:54:47 [SEVERE] Could not pass event EntityTargetEvent to Citizens
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityTargetEvent(CraftEventFactory.java:464)
at net.minecraft.server.PathfinderGoalMeleeAttack.c(PathfinderGoalMeleeAttack.java:59)
at net.minecraft.server.PathfinderGoalSelector.a(PathfinderGoalSelector.java:44)
at net.minecraft.server.EntityLiving.bc(EntityLiving.java:1216)
at net.minecraft.server.EntityLiving.d(EntityLiving.java:1091)
at net.minecraft.server.EntityMonster.d(EntityMonster.java:21)
at net.minecraft.server.EntityLiving.h_(EntityLiving.java:447)
at net.minecraft.server.EntityMonster.h_(EntityMonster.java:25)
at net.minecraft.server.EntityCreeper.h_(EntityCreeper.java:87)
at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
at net.minecraft.server.World.tickEntities(World.java:1125)
at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.IllegalArgumentException: The validated object is null
at org.apache.commons.lang.Validate.notNull(Validate.java:222)
at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:143)
at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:150)
at net.citizensnpcs.EventListen.onEntityTarget(EventListen.java:150)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
... 22 more

Running Citizens 2.0

**Comment by jrbudda** [comment]
Update to latest builds.
