### ISSUE TITLE
Blacksmith v1.1

### ISSUE THREAD

**Issue by mudgw2** [CitizensDev/Citizens#1159]
6:42:29 AM [INFO] [Blacksmith] Enabling Blacksmith v1.1
6:42:29 AM [SEVERE] Error occurred while enabling Blacksmith v1.1 (Is it up to date?)
java.lang.NoSuchMethodError: net.citizensnpcs.api.util.YamlStorage.load()V
at net.apunch.blacksmith.util.Settings.load(Settings.java:18)
at net.apunch.blacksmith.BlacksmithPlugin.onEnable(BlacksmithPlugin.java:40)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:265)
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:247)
at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:296)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:275)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:225)
at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

Minecraft Server 1.3.2
Craftbukkit 1.3.2-R0.1-4
Citizens 2.01

**Comment by jrbudda** [comment]
Be sure and grab the latest build from here http://ci.citizensnpcs.com/view/Characters/job/Blacksmith/ should fix this.
