### ISSUE TITLE
Can't Create new NPC Bug

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#128]
Bukkit Version: ? 1.8.1
Citizens Version: 1.0.9d
BUG!
I can't create ay NPCs

This error is shown:

Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
    at com.citizens.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:35)
    at com.citizens.npcs.NPCManager.register(NPCManager.java:46)
    at com.citizens.Citizens.setupNPCs(Citizens.java:305)
    at com.citizens.Citizens.access$0(Citizens.java:286)
    at com.citizens.Citizens$1.run(Citizens.java:120)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)

Plz help me...

**Comment by defaultsucks** [comment]
Only the latest dev builds of citizens work with the craftbukkit builds past #1092. Get yourself a dev build or downgrade your craftbukkit.
