### ISSUE TITLE
Issue when used with Spout

### ISSUE THREAD

**Issue by ImDeity** [CitizensDev/Citizens#143]
When using Spout build 381 and Craftbukkit 1190 with Citizens NPC plugin v 1.1, this message is spammed on creation and also when the server starts up (on startup, it goes through a "Reporting error to Citizens" cycle also):

```
05:49:42 [SEVERE] java.lang.ClassCastException
05:49:42 [SEVERE] java.lang.NullPointerException
05:49:42 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
05:49:42 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
05:49:42 [SEVERE]       at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
05:49:42 [SEVERE]       at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
05:49:42 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
05:49:42 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
05:49:42 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
05:49:42 [SEVERE]       at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
05:49:42 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
05:49:42 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
05:49:42 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
05:49:42 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
05:49:42 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:49:42 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
05:49:42 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
05:49:42 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
05:49:42 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
05:49:42 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
05:49:42 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
05:49:44 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
05:49:42 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
05:49:44 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
05:49:44 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
05:49:44 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
05:49:44 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
05:49:44 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
05:49:44 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
05:49:44 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
05:49:44 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
05:49:44 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
05:49:44 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
05:49:44 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
05:49:44 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
05:49:44 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
05:49:44 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
05:49:44 [SEVERE] Could not pass event PLAYER_TELEPORT to Spout
```

**Comment by defaultsucks** [comment]
This is a spout issue, not citizens'.

**Comment by ImDeity** [comment]
Thanks for the response. I have filed an issue with Spout here: https://github.com/SpoutDev/Spout/issues/576
