### ISSUE TITLE
Citizens 1.1 throwing exceptions w/ spout and mChat, etc?

### ISSUE THREAD

**Issue by hiro24** [CitizensDev/Citizens#146]
Getting the following messages in server log when a new citizen is created:

2011-09-25 04:44:15 [INFO] Creating empty config: /home/1.8/plugins/Essentials/userdata/smithy.yml
2011-09-25 04:44:15 [SEVERE] java.lang.NullPointerException
2011-09-25 04:44:15 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
2011-09-25 04:44:15 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
2011-09-25 04:44:15 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
2011-09-25 04:44:15 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-25 04:44:15 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-25 04:44:15 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-25 04:44:15 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-25 04:44:15 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-25 04:44:15 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
2011-09-25 04:44:15 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-09-25 04:44:15 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-09-25 04:44:15 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-09-25 04:44:15 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
2011-09-25 04:44:15 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 04:44:16 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information ha
s been included other than Citizens version information.
2011-09-25 04:44:15 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)

2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-09-25 04:44:16 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-25 04:44:16 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-25 04:44:16 [SEVERE] java.lang.ClassCastException
2011-09-25 04:44:16 [SEVERE] java.lang.NullPointerException
2011-09-25 04:44:16 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
2011-09-25 04:44:16 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
2011-09-25 04:44:16 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
2011-09-25 04:44:16 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-25 04:44:16 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
2011-09-25 04:44:16 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-09-25 04:44:16 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-09-25 04:44:16 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-09-25 04:44:16 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
2011-09-25 04:44:16 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 04:44:17 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 04:44:16 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2011-09-25 04:44:17 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-09-25 04:44:17 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-09-25 04:44:17 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)

2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-09-25 04:44:17 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-25 04:44:17 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-25 04:44:17 [SEVERE] Could not pass event PLAYER_TELEPORT to Spout
java.lang.ClassCastException

This happens every time we create a citizen.  Also, after a time, we began to get a lot of this:

2011-09-25 04:47:35 [SEVERE] java.lang.NullPointerException
2011-09-25 04:47:35 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
2011-09-25 04:47:35 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
2011-09-25 04:47:35 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
2011-09-25 04:47:35 [SEVERE]    at org.getspout.spout.player.SimpleAppearanceManager.setGlobalTitle(SimpleAppearanceManager.java:379)
2011-09-25 04:47:35 [SEVERE]    at net.D3GN.MiracleM4n.mChatEssentials.playerListener.onPlayerChat(playerListener.java:26)
2011-09-25 04:47:35 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$6.execute(JavaPluginLoader.java:279)
2011-09-25 04:47:35 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-25 04:47:35 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:726)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-09-25 04:47:35 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-25 04:47:35 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-25 04:47:35 [SEVERE] Could not pass event PLAYER_CHAT to mChatEssentials
java.lang.ClassCastException

We also began to get messages about the server being overloaded.  We're running the RB 1185, with citizens 1.1.  Any help would be appreciated.  ty.

**Comment by Jddegaetano** [comment]
I'm having this same issue, as are lots of other people. I use spout for at least 5 plugins. But my server is dependent on NPC's. Any help would be appreciated!

**Comment by defaultsucks** [comment]
It's a spout issue, not citizens'. Post this on their github.

**Comment by hiro24** [comment]
I fail to see how this is a spout issue when citizens is the only plugin that causes this error

**Comment by fullwall** [comment]
Fixed.
