### ISSUE TITLE
spout errors on startup

### ISSUE THREAD

**Issue by ferretlegs** [CitizensDev/Citizens#148]
similar to previous people i think.  here is some of it - this keeps going on throughout and ties up the whole server, i need to force stop, cannot stop gracefully.  perhaps spout version?  everything was deleted except npc-profiles, this is 1.1 offical.

2011-09-25 03:25:57 [INFO] [Citizens] NPC types loaded: blacksmith, quester, wizard, trader, guard, healer
2011-09-25 03:25:59 [INFO] [Citizens] Permissions system found (bPermissions v1.6.0)
2011-09-25 03:25:59 [INFO] [Citizens] version [1.1] loaded.
2011-09-25 03:25:59 [INFO] [Citizens] Economy plugin found (iConomy v5)
2011-09-25 03:25:59 [INFO] ChessCraft: Permissions detected
2011-09-25 03:25:59 [INFO] ChessCraft: loaded set Standard OK.
2011-09-25 03:25:59 [INFO] ChessCraft: loaded 1 saved boards.
2011-09-25 03:25:59 [INFO] ChessCraft: loaded 0 saved games.
2011-09-25 03:25:59 [INFO] ChessCraft version 0.2 is enabled!
2011-09-25 03:25:59 [INFO] [dynmap] Using Permissions 2.7.2 for access control
2011-09-25 03:26:01 [INFO] [dynmap] Loaded 12 shaders.
2011-09-25 03:26:02 [INFO] [dynmap] Loaded 56 perspectives.
2011-09-25 03:26:02 [INFO] [dynmap] Loaded 6 lightings.
2011-09-25 03:26:02 [INFO] [dynmap] Loaded 2 maps of world 'world'.
2011-09-25 03:26:02 [INFO] [dynmap] Loaded 2 maps of world 'world_nether'.
2011-09-25 03:26:02 [INFO] [dynmap] version 0.22.1 is enabled
2011-09-25 03:26:03 [INFO] Server permissions file permissions.yml is empty, ignoring it
2011-09-25 03:26:03 [INFO] Done (1.960s)! For help, type "help" or "?"
2011-09-25 03:26:03 [INFO] Reached end of stream
2011-09-25 03:26:03 [SEVERE] java.lang.NullPointerException
2011-09-25 03:26:03 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
2011-09-25 03:26:03 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
2011-09-25 03:26:03 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
2011-09-25 03:26:03 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-25 03:26:03 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-25 03:26:03 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-25 03:26:03 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-25 03:26:03 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-25 03:26:03 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-25 03:26:03 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-25 03:26:03 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-25 03:26:03 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 03:26:06 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 03:26:03 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
2011-09-25 03:26:06 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 03:26:07 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 03:26:06 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
2011-09-25 03:26:07 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 03:26:08 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 03:26:07 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
2011-09-25 03:26:08 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-09-25 03:26:08 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
2011-09-25 03:26:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-25 03:26:08 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-25 03:26:08 [SEVERE] java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
2011-09-25 03:26:08 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1013)
2011-09-25 03:26:08 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-25 03:26:08 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-25 03:26:08 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-25 03:26:08 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-25 03:26:08 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-25 03:26:08 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-25 03:26:08 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-25 03:26:08 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-25 03:26:08 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 03:26:10 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 03:26:08 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
2011-09-25 03:26:10 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 03:26:11 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 03:26:10 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
2011-09-25 03:26:11 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-25 03:26:12 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-25 03:26:11 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
2011-09-25 03:26:12 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-09-25 03:26:12 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
2011-09-25 03:26:12 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-25 03:26:12 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(

**Comment by defaultsucks** [comment]
It's a spout issue, not citizens'. Post this on their github.

**Comment by fullwall** [comment]
Fixed in latest build.
