### ISSUE TITLE
Players can't buy from NPCs or Create them.

### ISSUE THREAD

**Issue by Malific** [CitizensDev/Citizens#149]
CB 1185:
Citizens 1.1
PermissionsEX 1.14

Players can select the NPC Trader, but cannot pull up their inventory to buy from them.
typing /npc create <name> gives "you do not have permission" error.

As Op I have no trouble doing any of this.

All nodes are set according to the wiki posting here: http://wiki.citizensnpcs.net/index.php?title=Commands_and_Permissions#Toggle_Commands
and here: http://wiki.citizensnpcs.net/index.php?title=Trader

I didn't notice a node under your trader listing to allow players to buy and sell to/from the trader, only access to the /commands for modifying stock. Are your permissions wiki's up to date for 1.1 since it only came out a few hours ago?

Might be related but I doubt it: On server startup I receive these 2 errors for each npc on my server:

2011-09-25 03:53:58 [SEVERE] Could not pass event PLAYER_TELEPORT to Essentials
java.lang.NullPointerException
    at com.earth2me.essentials.EssentialsPlayerListener.onPlayerTeleport(EssentialsPlayerListener.java:355)
    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-25 03:53:58 [SEVERE] Could not pass event PLAYER_TELEPORT to Essentials
java.lang.NullPointerException
    at com.earth2me.essentials.JailPlayerListener.onPlayerTeleport(JailPlayerListener.java:52)
    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Download the latest dev build to fix permissionsEx compatibility. The essentials error needs to be fixed by Essentials.

**Comment by Malific** [comment]
Yeah, I'm not worried about the essentials errors I've always had them and they don't effect how anything functions, just spammy on the console.
