### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by liquidox** [CitizensDev/Citizens#150]
On default config, 1.1 startup errors

11:56:14 [SEVERE] Permission node 'citizens._' in plugin description file for Citizens v1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin._' contains invalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)
        at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescriptionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:138)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Odd. I don't get this error... can you try downloading a newer dev version?

**Comment by fullwall** [comment]
Got the error, @aPunch might be able to figure it out... :P

**Comment by liquidox** [comment]
Solved
