### ISSUE TITLE
Citizens/Spout Errors

### ISSUE THREAD

**Issue by Safetybrick** [CitizensDev/Citizens#165]
Hey guys, i just updated my server plugins and came across this error when updating Citizens to the latest plugin. after a little shifting of plugins iv isolated it between Spout and Citizens. i can have one of the other loaded on the server with out error but when both are loaded i get the follow. for spout i tried but the RB and the Dev build. for spout i cleared everything but the citizen jar and and npc-profile. from what i can tell it spams my console with this 12 times(same number of npcs i have). any ideas what may be causing this?

2011-09-26 00:08:21 [INFO] Reached end of stream
2011-09-26 00:08:21 [SEVERE] java.lang.NullPointerException
2011-09-26 00:08:21 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:142)
2011-09-26 00:08:21 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:1009)
2011-09-26 00:08:21 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1028)
2011-09-26 00:08:21 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-26 00:08:21 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-26 00:08:21 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-26 00:08:21 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-26 00:08:21 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-26 00:08:21 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-26 00:08:21 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-26 00:08:21 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-26 00:08:21 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:22 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:21 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
2011-09-26 00:08:22 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:23 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:22 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
2011-09-26 00:08:23 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:24 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:23 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
2011-09-26 00:08:24 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-09-26 00:08:24 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
2011-09-26 00:08:24 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-26 00:08:24 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-26 00:08:24 [SEVERE] java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
2011-09-26 00:08:24 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1029)
2011-09-26 00:08:24 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-26 00:08:24 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-26 00:08:24 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-26 00:08:24 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-26 00:08:24 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-26 00:08:24 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-26 00:08:24 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-26 00:08:24 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-26 00:08:24 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:26 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:24 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
2011-09-26 00:08:26 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:27 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:26 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
2011-09-26 00:08:27 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:28 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:27 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
2011-09-26 00:08:28 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-09-26 00:08:28 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
2011-09-26 00:08:28 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-26 00:08:28 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-26 00:08:28 [SEVERE] java.lang.NullPointerException
2011-09-26 00:08:28 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:142)
2011-09-26 00:08:28 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:1009)
2011-09-26 00:08:28 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1028)
2011-09-26 00:08:28 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
2011-09-26 00:08:28 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-26 00:08:28 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-26 00:08:28 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-26 00:08:28 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-26 00:08:28 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-26 00:08:28 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-26 00:08:28 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:29 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:28 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
2011-09-26 00:08:29 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:30 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:29 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
2011-09-26 00:08:30 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 00:08:31 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 00:08:30 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
2011-09-26 00:08:31 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-09-26 00:08:31 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
2011-09-26 00:08:31 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-26 00:08:31 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-26 00:08:31 [SEVERE] Could not pass event PLAYER_TELEPORT to Spout
java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1029)
    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Please download the latest dev build of Citizens.
