### ISSUE TITLE
Rightclick on Trader becomes a errorflood

### ISSUE THREAD

**Issue by Embolex** [CitizensDev/Citizens#173]
Hi.

i only clicking with right mouse button on the trader to select him.
It seems that nothing happens. But the console speaks for itself.
Here it is.:

2011-09-26 23:15:58 [INFO] Starting Minecraft server on _:25565
2011-09-26 23:15:58 [WARNING] *_*\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
2011-09-26 23:15:58 [WARNING] The server will make no attempt to authenticate usernames. Beware.
2011-09-26 23:15:58 [WARNING] While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
2011-09-26 23:15:58 [WARNING] To change this, set "online-mode" to "true" in the server.settings file.
2011-09-26 23:15:58 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1067-g6301507-b1185jnks (MC: 1.8.1)
2011-09-26 23:15:58 [INFO] [PermissionsEx] sql backend registered!
2011-09-26 23:15:58 [INFO] [PermissionsEx] file backend registered!
2011-09-26 23:15:58 [INFO] [PermissionsEx] PermissionEx plugin initialized.
2011-09-26 23:15:58 [INFO] [PermissionsEx] p2compat backend registered!
2011-09-26 23:15:58 [INFO] [PermissionsCompat] Compatibility Layer Initalized!
2011-09-26 23:15:59 [INFO] [PermissionsEx] Initializing file backend
2011-09-26 23:15:59 [INFO] [Register] Preferred method [null] not found, using first found.
2011-09-26 23:15:59 [INFO] [Register] Payment method found (BOSEconomy version: 0.7.0)
2011-09-26 23:15:59 [INFO] [Register] version 1.3 is enabled.
2011-09-26 23:15:59 [INFO] [XcraftGate v0.10d4] loaded 4 world configurations
2011-09-26 23:15:59 [INFO] [XcraftGate v0.10d4] loaded 0 gates
2011-09-26 23:15:59 [INFO] Preparing level "joioo"
2011-09-26 23:15:59 [INFO] Default game type: 0
2011-09-26 23:15:59 [INFO] Preparing start region for level 0 (Seed: 1908052920448567243)
2011-09-26 23:16:00 [INFO] Preparing start region for level 1 (Seed: -1630680439565084950)
2011-09-26 23:16:00 [INFO] Preparing spawn area: 4%
2011-09-26 23:16:00 [INFO] [XcraftGate v0.10d4] World 'joioo' detected. Applying config.
2011-09-26 23:16:02 [INFO] [XcraftGate v0.10d4] loaded 0 gates for world 'joioo'
2011-09-26 23:16:02 [INFO] [XcraftGate v0.10d4] World 'joioo_nether' detected. Applying config.
2011-09-26 23:16:03 [INFO] [XcraftGate v0.10d4] loaded 0 gates for world 'joioo_nether'
2011-09-26 23:16:03 [INFO] AutoHelp version 0.2 is enabled!
2011-09-26 23:16:03 [INFO] BOSEconomy: Located Permissions 2.7.7.
2011-09-26 23:16:03 [INFO] BOSEconomy v0.7.2 enabled.
2011-09-26 23:16:03 [INFO] ChairCraft 1.2.6 is enabled.
2011-09-26 23:16:03 [INFO] CraftBukkitUpToDate version 2.6.6 is enabled!
2011-09-26 23:16:03 [INFO] [PermissionsCompat] Compatibility layer enabled.
2011-09-26 23:16:03 [INFO] [XcraftGate v0.10d4] hooked into Permissions 2.7.7
2011-09-26 23:16:03 [INFO] [HELP] 0 extra help entries loaded
2011-09-26 23:16:03 [INFO] [HELP] Permissions enabled using: Permissions v2.7.7
2011-09-26 23:16:03 [INFO] [HELP] 0.3.2 enabled
2011-09-26 23:16:03 [INFO] [PermissionsEx] Superperms support enabled.
2011-09-26 23:16:03 [INFO] [PermissionsEx] v1.14 enabled
2011-09-26 23:16:03 [INFO] [PorteCoulissante] plugin version 1.2.4 by Captain_Chaos enabled
2011-09-26 23:16:03 [INFO] [RetractableBridge] plugin version 1.3.10 by Captain_Chaos enabled
2011-09-26 23:16:03 [INFO] Stargate v.0.6.9 is enabled.
2011-09-26 23:16:03 [INFO] [Stargate] Loaded 1 gate layouts
2011-09-26 23:16:03 [INFO] [Stargate] {joioo} Loaded 3 stargates with 0 set as always-on
2011-09-26 23:16:03 [INFO] [Stargate] {joioo_nether} No stargates for world 
2011-09-26 23:16:03 [INFO] [Stargate] Found Permissions (v2.7.7)
2011-09-26 23:16:03 [INFO] WorldEdit 4.6 enabled.
2011-09-26 23:16:03 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin for permissions.
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] Permission found - hooking into Permissions
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] is enabled!
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] loading last used skills...
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] loaded 2 settings entries!
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] loading playerdata...
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] loaded 2 playerdata entries!
2011-09-26 23:16:04 [INFO] [xLevel] version [1.5.1] finished loading!
2011-09-26 23:16:04 [INFO] [ChatManager] ChatManager enabled!
2011-09-26 23:16:04 [INFO] [Modifyworld] Modifyworld enabled!
2011-09-26 23:16:04 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
2011-09-26 23:16:04 [INFO] [Citizens] Permissions system found (PermissionsEx v1.14)
2011-09-26 23:16:04 [INFO] [Citizens] version [1.1] loaded.
2011-09-26 23:16:04 [INFO] [Citizens] Economy plugin found (BOSEconomy v0.7.0)
2011-09-26 23:16:04 [INFO] Server permissions file permissions.yml is empty, ignoring it
2011-09-26 23:16:04 [INFO] Done (0,530s)! For help, type "help" or "?"
2011-09-26 23:16:04 [INFO] Preparing start region for level 2 (Seed: 1508827087)
2011-09-26 23:16:05 [INFO] [Stargate] {Huuumuu} Loaded 1 stargates with 0 set as always-on
2011-09-26 23:16:05 [INFO] [XcraftGate v0.10d4] World 'Huuumuu' detected. Applying config.
2011-09-26 23:16:06 [INFO] [XcraftGate v0.10d4] loaded 0 gates for world 'Huuumuu'
2011-09-26 23:16:06 [INFO] [XcraftGate v0.10d4] loaded world Huuumuu (Environment: NORMAL, Seed: 1508827087, Generator: DEFAULT)
2011-09-26 23:16:06 [INFO] Preparing start region for level 3 (Seed: 1410605952214546606)
2011-09-26 23:16:07 [INFO] [Stargate] {Sky-o-Rama} Loaded 1 stargates with 0 set as always-on
2011-09-26 23:16:07 [INFO] [XcraftGate v0.10d4] World 'Sky-o-Rama' detected. Applying config.
2011-09-26 23:16:08 [INFO] [XcraftGate v0.10d4] loaded 0 gates for world 'Sky-o-Rama'
2011-09-26 23:16:08 [INFO] [XcraftGate v0.10d4] loaded world Sky-o-Rama (Environment: SKYLANDS, Seed: 1410605952214546606, Generator: DEFAULT)
2011-09-26 23:16:08 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?
2011-09-26 23:16:08 [INFO] [Citizens] Loaded 0 NPCs.
2011-09-26 23:16:08 [INFO] [Citizens] Loaded 0 quests.
2011-09-26 23:16:09 [INFO] CButD: CraftBukkit is up to Date
2011-09-26 23:16:13 [INFO] The automatic update-Check only work every 6 hours, the last check was 27 minutes ago.
2011-09-26 23:16:15 [INFO] /127.0.0.1:50445 lost connection
2011-09-26 23:16:16 [INFO] Embolex [/127.0.0.1:50447] logged in with entity id 919 at ([Sky-o-Rama] 162.4530816979552, 77.0, 7.380154449696597)
2011-09-26 23:16:23 [INFO] [AutoHelp] Searching active plugins' plugin.yml files for command help
2011-09-26 23:16:23 [INFO] [AutoHelp] Skipping command 'help', already has a help entry
2011-09-26 23:16:23 [INFO] [AutoHelp] 'Help' support enabled.
2011-09-26 23:16:36 [INFO] Reached end of stream
2011-09-26 23:17:08 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-26 23:17:18 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-26 23:17:08 [SEVERE] Could not pass event ENTITY_TARGET to Citizens
java.lang.NoClassDefFoundError: net/citizensnpcs/permissions/PermissionManager
    at net.citizensnpcs.traders.Trader.onRightClick(Trader.java:127)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:158)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:112)
    at org.bukkit.plugin.java.JavaPluginLoader$66.execute(JavaPluginLoader.java:705)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:321)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:902)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.permissions.PermissionManager
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more
2011-09-26 23:17:18 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?

When i´m Stopping the server and reopen where 0 Npcs loaded .. means my created trader is lost and i have to create him again.

And after i clicked on Trader and theres nothing happen .... no command citizens command will work ... for example: /npc equip, /npc reset, /trader list buy .... and more .... there is happening nothing too, same like right click on trader

Please Help me :) 
My Citizens.jar is Up-to-Date ... I´ve updated it one our ago. MC says me to do an update for Citizens.jar. Its now Citizens Dev #209

Sincerely, Embolex

**Comment by fullwall** [comment]
You need to update all type jars.

**Comment by Embolex** [comment]
i did
