### ISSUE TITLE
bPermissions errors (devbuild209 and others)

### ISSUE THREAD

**Issue by DanWard** [CitizensDev/Citizens#174]
09:55:26 [INFO] [Citizens] NPC types loaded: guard, healer, trader, wizard
09:55:26 [INFO] [Citizens] Permissions system found (bPermissions v1.7.2)
09:55:26 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
09:55:33 [INFO] [Citizens]
09:55:33 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
09:55:33 [INFO] [Citizens] Below is the stacktrace that has been transmitted to
the developers, no other information has been included other than Citizens versi
on information.
09:55:26 [SEVERE] Error occurred while enabling Citizens v1.1 (Is it up to date?
): net/citizensnpcs/PermissionManager
java.lang.NoClassDefFoundError: net/citizensnpcs/PermissionManager
        at net.citizensnpcs.guards.GuardCommands.addPermissions(GuardCommands.java:314)
        at net.citizensnpcs.permissions.PermissionManager.addPermissions(PermissionManager.java:113)
        at net.citizensnpcs.permissions.PermissionManager.<init>(PermissionManager.java:46)
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:102)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:920)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:173)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:156)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.PermissionManager
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more

Removed all plugins but bpermissions and returns the same result. Tried with bp v1.6.9-1.7.2

**Comment by fullwall** [comment]
Need to update all type jars as well.
