### ISSUE TITLE
Guards Unresponsive

### ISSUE THREAD

**Issue by jaseaman** [CitizensDev/Citizens#178]
I know that this feature has not been completely implemented.

Here are the list of commands i do to make the NPC TRY to kill mobs, however they do not, they just ignore that mob.

/npc create Joe
/toggle guard
/guard bouncer
/guard radius 50
/guard addflag 1 -m creeper
/guard addflag 2 -m skeleton
/guard addflag 3 -m spider
/guard addflag 4 -m zombie
/guard addflag 5 -m enderman

Thats what i do and ive cross referenced and YES the guard is set to agressive.

Any Ideas?

Thanks Myhijim

**Comment by jaseaman** [comment]
Do i need to add pathing?

**Comment by fullwall** [comment]
Shouldn't do... I'll look into it.

**Comment by Williamsson** [comment]
I'd also like to point out that I am experiencing the very same issue, and we're using
bukkit: RB 1185
Citizens 1.1

**Comment by jaseaman** [comment]
Yep same version, i was thinking it was just laggy but no.

Btw i do love the plugin, this guards would be perfect for my zombie survival :D

**Comment by fullwall** [comment]
Hmmm... very strange - I can't reproduce - perhaps try the latest dev build and see if you get the same results?

**Comment by jaseaman** [comment]
Please link?
Sorry i am quite new to this

**Comment by quickclay** [comment]
I also am getting the exact same issue, cb 1185, cit 1.1, PEX

**Comment by fullwall** [comment]
Stranger and stranger...

**Comment by Williamsson** [comment]
Solved it, there's a compatibility issue with some plugin. I removed a bunch plugin on my local server, and all of a sudden the npc, with bravery in his heart, charged at the skeleton with nothing but his fists. I fell in love with him, that handsome fella.

Aaaanyhow... Don't know what plugin it is yet, will implement them one at a time when I have time to. But it's not Citizens fault anyhow.

**Comment by jaseaman** [comment]
Okay Thanks But most of my plugins are essentail to my server :/

List:
-Residences
-MyWorlds/Multiverse
-Essentials
-Permissions
-Pail (Shoulnt do but cant be too sure :P)
-Turnstiles

And thats it as far as i can think of, i cant really check as im not at my server computer atm, but will add if there are anymore.

@Williamsson Did you remove any of these?

**Comment by jaseaman** [comment]
I believe it is an issue with multiworld at the moment, thats what i can see as the problem, not sure though.

**Comment by Williamsson** [comment]
The plugin I found to be the problem was MultiInv. I have no idea of why, but when it's installed the guards won't work.
If you have it too, remove it and test. Otherwise test it on a different server and remove plugins one by one.

@fullwall
I can haz cookie? :3

**Comment by jaseaman** [comment]
Hmmm I dont have Multi Inv but i will test the guards if i have time, of which i dont have now :/

**Comment by Realexa** [comment]
I don't have MultiInv but i dó have multiple worlds! I use Xcraftgate.
After a server restart i logged in right away and i saw a guard butcher 1 sheep (and there was some wool on the floor from a previous one, i flagged sheep for testing). But when i came online he finished the one off and then stopped.
Also, when i logged in, the console gave me a guard.jar specific error... with some permissions reference in it aswell (i just switched to PermissionsBukkit).

So i could imagen that Citizens (or the guard.jar) has issues locating on which world the npc is or something? And maybe it tried to check the group i was in when i logged in and thus came close?

**Comment by jaseaman** [comment]
Yeah that was my train of thought too, but even now on one of my worlds, when set to bouncer they wont even move

**Comment by fullwall** [comment]
@Realexa - if there's a permissionsmanager error, you likely need to update the rest of your type JARs
@myhijim - which citizens version are you using?
A plugin conflict would make sense - a multiworld plugin even more so if not using the latest dev builds.

**Comment by jaseaman** [comment]
1.1 
I cant update to the dev builds due to my server being on a different computer...
A shame if you ask me, infact my server just crashed then, mighty shame.

The Bouncers have now started to move around however, i did spawn 3 zombies infront of him and he didnt attack.

**Comment by Realexa** [comment]
I'm sorry.. i wasn't clear enough.
The error is a citizens error (and mainly on the guard and its flags) but it does say in its error something about a permission aswell.
Below the error pasted to make things more clear:

22:52:43 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoClassDefFoundError: net/citizensnpcs/permissions/PermissionManager
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:103)

```
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:85)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)

    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
```

terator.java:136)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:131)
        at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:
149)
        at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:38)
        at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:
63)
        at net.citizensnpcs.guards.GuardTask.handleTarget(GuardTask.java:116)
        at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:78)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.permissions.Permis
sionManager
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more
22:52:43 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoClassDefFoundError: net/citizensnpcs/permissions/PermissionManager
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:103)

```
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:85)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)

    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
```

terator.java:136)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:131)
        at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:
149)
        at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:38)
        at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:
63)
        at net.citizensnpcs.guards.GuardTask.handleTarget(GuardTask.java:116)
        at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:78)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by quickclay** [comment]
Of the multiworld plugins listed above, I also have XCraftGate.  I will test removing that to confirm it's the source of the compatibility problem.

**Comment by quickclay** [comment]
Regarding getting the dev builds, I get 404 errors on citizensnpcs.net.  Could you check on that, or host the latest dev build at BukkitDev?  Thanks!

**Comment by quickclay** [comment]
Problem with xCraftGate multiworld manager confirmed.  I unloaded XcraftGate and guards became responsive.  Unfortunately I need xCraftGate for my server.  Does the dev build of Citizens address this?  Thanks!

**Comment by quickclay** [comment]
Sorry for the several posts.  Strangely, after unloading xCraftGate, running the server, than reloading XCrafGate, guards now attack mobs properly?!

**Comment by Realexa** [comment]
@quickclay Which version of Xcraftgate do you use? I've got the latest one (3 days old, 0.10d4) but maybe the conflict doesnt exist in a different version? 

Then again... Williamson has the problem using a different multi-world addon (Multiverse) so i guess this problem occurs in any situation multiple worlds are loaded. :(

**Comment by jaseaman** [comment]
Get the latest dev builds here guys, just figured it out myself

http://ci.citizensnpcs.net/

**Comment by jaseaman** [comment]
Yeah there seems to be no support for multiworld

**Comment by Williamsson** [comment]
@Relaxea
No, not multiverse - Multi Inv, the plugin that sets different inventories per world.
Multiverse (2) works just fine with citizens.

**Comment by Realexa** [comment]
Thanks! Getting the latest build from http://ci.citizensnpcs.net/ fixed it for me!

**Comment by quickclay** [comment]
@Realexa, I have been using xCraftGate version 0.9.  I'll upgrade both it, and Citizens to latest dev build. Looks promising based on your above comment. :D

**Comment by jaseaman** [comment]
Ok well im still waiting to go to my server computer, mighty shame...

**Comment by quickclay** [comment]
The dev build looked promising, but after a short amount of time (maybe 15 minutes), Guards go back to being unresponsive with the dev build too.
Also, I noticed that they didn't return to their tile after chasing an enemy unless a path was set, but if set, they returned there after each kill, even if other mobs were present.

**Comment by Realexa** [comment]
I've been running the server for at least an hour now and the guards keep working.
The resetting is a bit off indeed, they often end up on a different tile. Make sure you update both the guard.jar as the citizens.jar (all of them actually) as different versions caused some errors for me.

In the later builds of today i think it works aswell, try a different build otherwise: http://jenkins.citizensnpcs.net:81/job/Citizens

**Comment by jaseaman** [comment]
ok thanks ill try it if my friend at the server computer responds... -_-

**Comment by jaseaman** [comment]
@quickclay
I am experiencing exactly the same after updating to the newest dev build
@fullwall
Found a solution yet?

**Comment by quickclay** [comment]
Likewise.  I still think it has to do with some sort of multi-world issue.

**Comment by Patolord** [comment]
same problem 
guard is unresponsive

**Comment by Patolord** [comment]
still waiting for a solution SIR DEVELOPER

**Comment by fullwall** [comment]
It's odd, because it works fine for me... :(

**Comment by Williamsson** [comment]
I suggest you all to remove all plugins but citizens, just as a test, and see if it works then.
As I mentioned before, I had issues with multiinv, see if it works.

If it does, I hope fullwall have some idea of why it's so.

I don't know if we're still having that issue, since we're currently switching worlds and are not using citizens right now.
I'll however come back if the issue is still there when we're done.

**Comment by Cixxar** [comment]
This is a problem for me also. please lookinto this
