### ISSUE TITLE
Build 212 Illegal argument exception

### ISSUE THREAD

**Issue by yottabyte** [CitizensDev/Citizens#187]
I'm not sure why this happens, but it shows up in my console every now and then

17:37:19 [WARNING] Task of 'Citizens' generated an exception
java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Unknown Source)
        at net.citizensnpcs.resources.npclib.creatures.DefaultSpawner.getRandomInt(DefaultSpawner.java:86)
        at net.citizensnpcs.resources.npclib.creatures.DefaultSpawner.spawn(DefaultSpawner.java:38)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.spawnCreature(CreatureTask.java:47)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.run(CreatureTask.java:39)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Fixed.
