### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jrcrit** [CitizensDev/Citizens#193]
2011-09-29 17:22:18 [SEVERE] Error occurred while enabling Citizens v1.1 (Is it up to date?): null; mapping values are not allowed here
mapping values are not allowed here
 in "<reader>", line 41, column 53:
    5px; padding: 0.4em; position: absolute; bot ... 
                ^

```
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:745)
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:307)
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:183)
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:564)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:124)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
at org.bukkit.util.config.Configuration.load(Configuration.java:82)
at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:32)
at net.citizensnpcs.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:26)
at net.citizensnpcs.properties.properties.UtilityProperties.initialize(UtilityProperties.java:21)
at net.citizensnpcs.properties.PropertyManager.registerProperties(PropertyManager.java:17)
at net.citizensnpcs.SettingsManager.setupVariables(SettingsManager.java:79)
at net.citizensnpcs.Citizens.onEnable(Citizens.java:80)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:920)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:173)
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:156)
at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
```

**Comment by jrcrit** [comment]
Experimental-Citizens using all so if i take the  citizens.yml and mob.yml out i get no loading up errors but when i go in game and type  /npc walk around for about 30sec i get this error 

2011-09-29 17:26:41 [WARNING] Task of 'Citizens' generated an exception
java.lang.IllegalArgumentException: n must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.citizensnpcs.resources.npclib.creatures.DefaultSpawner.getRandomInt(DefaultSpawner.java:86)
    at net.citizensnpcs.resources.npclib.creatures.DefaultSpawner.spawn(DefaultSpawner.java:38)
    at net.citizensnpcs.resources.npclib.creatures.CreatureTask.spawnCreature(CreatureTask.java:47)
    at net.citizensnpcs.resources.npclib.creatures.CreatureTask.run(CreatureTask.java:39)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by jrcrit** [comment]
quote " Experimental-Citizens using all so if i take the citizens.yml and mob.yml out i get no loading up errors but when i go in game and type /npc walk around for about 30sec i get this error  "

i use the v1.1 mob.yml and citizens.yml the Experimental-Citizens gives me the huge error when loading up if i use its ones

**Comment by jrcrit** [comment]
i am all-so using permissionsEx with v1.1 i need to be a mod or op with this Experimental-Citizens  it seems to be working fine expect for that small error

**Comment by jrcrit** [comment]
icon money does not seem to drop as you buy ?
