### ISSUE TITLE
Quest-Reward Error

### ISSUE THREAD

**Issue by TerraNetworkOrg** [CitizensDev/Citizens#202]
CB 1185
Spout 1.0.6 #381
Citizens 1.1 #223
-> Quester #223
PEX 1.14

I accepted the Quest: works fine!
I did the Quest: works fine!
I wanted to give it back: error in console:

2011-09-29 19:42:20 [INFO] [Citizens] Clearing objective 0
2011-09-29 19:42:25 [SEVERE] Could not pass event ENTITY_TARGET to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.rewards.ItemReward.grant(ItemReward.java:39)
    at net.citizensnpcs.questers.Quester.checkCompletion(Quester.java:161)
    at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:59)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:165)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:113)
    at org.bukkit.plugin.java.JavaPluginLoader$66.execute(JavaPluginLoader.java:705)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:321)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:902)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by TerraNetworkOrg** [comment]
My fault, had the wrong item id ...
