### ISSUE TITLE
Compatibility error with spout

### ISSUE THREAD

**Issue by danielfdsilva** [CitizensDev/Citizens#203]
Citizens version: 1.1
Spout version: 1.0.6

When i try to create a new citizen, it conflicts with spout and crashes the server.

Error:
2011-09-29 18:55:48 [SEVERE] java.lang.NullPointerException
2011-09-29 18:55:48 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:141)
2011-09-29 18:55:48 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:993)
2011-09-29 18:55:48 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1012)
2011-09-29 18:55:48 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-29 18:55:48 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-29 18:55:48 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-29 18:55:48 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-29 18:55:48 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-29 18:55:48 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-29 18:55:48 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-29 18:55:48 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-29 18:55:48 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-29 18:55:49 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-29 18:55:48 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)
2011-09-29 18:55:49 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-29 18:55:51 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-29 18:55:49 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
2011-09-29 18:55:51 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-29 18:55:56 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-29 18:55:51 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:135)
2011-09-29 18:55:56 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-09-29 18:55:56 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
2011-09-29 18:55:56 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-09-29 18:55:56 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-09-29 18:55:56 [SEVERE] java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
2011-09-29 18:55:56 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1013)
2011-09-29 18:55:56 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-09-29 18:55:56 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-09-29 18:55:56 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-09-29 18:55:56 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-09-29 18:55:56 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-09-29 18:55:56 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-09-29 18:55:56 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-09-29 18:55:56 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-09-29 18:55:56 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-09-29 18:55:57 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-09-29 18:55:56 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:308)

**Comment by TerraNetworkOrg** [comment]
Use the latest Dev-Builds, it works perfectly now!

**Comment by danielfdsilva** [comment]
nice, where can i find it?

**Comment by TerraNetworkOrg** [comment]
Citizens Dev Builds: http://ci.citizensnpcs.net/
Spout Dev Build: http://spout.in/plugindev

**Comment by scandragon** [comment]
Well I won't be adding the dev build of spout to my server, so at this time citizens is a nogo for me..
Too bad, seeing as our entire trading and tutorial system is depending heavily on citizens

**Comment by TerraNetworkOrg** [comment]
I know, dev-build and live-servers ...
On my testserver it works!
