### ISSUE TITLE
Problem with my Quests.yml

### ISSUE THREAD

**Issue by freeforfun** [CitizensDev/Citizens#218]
Citizens always give this error on start:

20:06:54 [INFO] [Citizens] Loaded 10 NPCs.
20:06:54 [INFO] [Citizens] An error has occurred, please wait while it is sent t
o the developers...
20:07:08 [INFO] [Citizens]
20:07:08 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net

20:07:08 [INFO] [Citizens] Below is the stacktrace that has been transmitted to
the developers, no other information has been included other than Citizens versi
on information.
20:06:54 [SCHWERWIEGEND] Could not pass event CUSTOM_EVENT to Citizens
java.lang.ExceptionInInitializerError
        at net.citizensnpcs.questers.listeners.QuesterCitizensListen.onCitizensE
nable(QuesterCitizensListen.java:18)
        at net.citizensnpcs.api.event.citizens.CitizensListener.onCustomEvent(Ci
tizensListener.java:30)
        at net.citizensnpcs.questers.listeners.QuesterCitizensListen.onCustomEve
nt(QuesterCitizensListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$93.execute(JavaPluginLoader.j
ava:897)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:338)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:139)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: unacceptable character #FFFD special characters are not allowed
in "<reader>", position 4394
        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.ja
va:68)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:159)
        at org.yaml.snakeyaml.reader.StreamReader.forward(StreamReader.java:89)
        at org.yaml.snakeyaml.reader.StreamReader.forward(StreamReader.java:79)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.ja
va:974)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.ja
va:237)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:18
3)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produ
ce(ParserImpl.java:200)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:104)

```
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseCons
```

tructor.java:124)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
        at org.bukkit.util.config.Configuration.load(Configuration.java:82)
        at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHa
ndler.java:32)
        at net.citizensnpcs.properties.ConfigurationHandler.<init>(Configuration
Handler.java:26)
        at net.citizensnpcs.questers.data.QuestProperties.<clinit>(QuestProperti
es.java:9)
        ... 11 more

When I delete my quests.yml it starts normal, but i can't find any mistake.

Here is my quests.yml: http://www.firegamer.de/quests.yml

Could you please help me?

**Comment by freeforfun** [comment]
Okay, i fixed it:

I changed every ":" to "-", every "ß" to "ss"
