### ISSUE TITLE
Error in Console possible compatibility issue

### ISSUE THREAD

**Issue by micdoodle8** [CitizensDev/Citizens#222]
Hey guys. I seem to get this spamming the console/log when I create a new NPC:

Creating empty config: /minecraft/plugins/Essentials/userdata/tinytim.yml
2011-10-03 07:15:43 [SEVERE] java.lang.NullPointerException
2011-10-03 07:15:43 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:142)
2011-10-03 07:15:43 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:1009)
2011-10-03 07:15:43 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1028)
2011-10-03 07:15:43 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-10-03 07:15:43 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-10-03 07:15:43 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-10-03 07:15:43 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-10-03 07:15:43 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-10-03 07:15:43 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
2011-10-03 07:15:43 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-03 07:15:43 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-10-03 07:15:43 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-03 07:15:43 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
2011-10-03 07:15:43 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-03 07:15:45 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-03 07:15:43 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-03 07:15:45 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-03 07:15:45 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-03 07:15:45 [SEVERE] java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
2011-10-03 07:15:45 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1029)
2011-10-03 07:15:45 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.updatePlayerEvent(SpoutPlayerListener.java:135)
2011-10-03 07:15:45 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:61)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-10-03 07:15:45 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
2011-10-03 07:15:45 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-03 07:15:45 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-10-03 07:15:45 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-03 07:15:45 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
2011-10-03 07:15:45 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-03 07:15:46 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-03 07:15:45 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-03 07:15:46 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-03 07:15:46 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-03 07:15:46 [SEVERE] java.lang.NullPointerException
2011-10-03 07:15:46 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.<init>(SpoutCraftPlayer.java:142)
2011-10-03 07:15:46 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.updateBukkitEntity(SpoutCraftPlayer.java:1009)
2011-10-03 07:15:46 [SEVERE]    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1028)
2011-10-03 07:15:46 [SEVERE]    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
2011-10-03 07:15:46 [SEVERE]    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
2011-10-03 07:15:46 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-03 07:15:46 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-10-03 07:15:46 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-03 07:15:46 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
2011-10-03 07:15:46 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-03 07:15:47 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-03 07:15:46 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2011-10-03 07:15:47 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-10-03 07:15:47 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-03 07:15:47 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-03 07:15:47 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-03 07:15:47 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-03 07:15:47 [SEVERE] Could not pass event PLAYER_TELEPORT to Spout
java.lang.ClassCastException: org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to org.getspout.spout.player.SpoutCraftPlayer
    at org.getspout.spout.player.SpoutCraftPlayer.getPlayer(SpoutCraftPlayer.java:1029)
    at org.getspout.spout.SpoutPlayerListener.onPlayerTeleport(SpoutPlayerListener.java:70)
    at org.bukkit.plugin.java.JavaPluginLoader$9.execute(JavaPluginLoader.java:300)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:269)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:32)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191)
    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517)
    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405)
    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

Thanks :D

**Comment by micdoodle8** [comment]
Plugins: ScizzrHome, iConomy, iAuction, BorderGuard, NoExp, WorldGuard, MagicCarpet, Cenotaph, HeroChat, Votifier, WorldEdit, uNether, ScheduledAnnouncer, Spout, BuyCraft, ThumbsApply, NarrowtuxLib, ModTRS, mcMMO, HeroicDeath, SkylandsPlus, SeedCraft, Minequery, mcbans, PlugMan, PermissionsEx, Essentials, EssentialsSpawn, DreamLand, LWC-Economy, LazyRoad, Modifyworld, Permissions, LWC, ChestShop, LogBlock, Citizens

**Comment by micdoodle8** [comment]
Whoops.... x.x Closed it by accident xD

**Comment by fullwall** [comment]
Need to download a new dev build.
