### ISSUE TITLE
Conflict Between Citizens and RyveMusic

### ISSUE THREAD

**Issue by nibbles** [CitizensDev/Citizens#225]
I've Disable RyveMusic for the time being since its not critical to the server.  However it would be nice to have both plugins play nice... Below is the error i recieve when both RyveMusic & Citizens are installed

<b>2011-10-03 15:58:48 [SEVERE] Error occurred while enabling RyveMusic v1.4.1 (Is it up to date?): com/citizens/Citizens
java.lang.NoClassDefFoundError: com/citizens/Citizens
    at com.bukkit.arthurh.RyveMusic.RyveMusic.onEnable(RyveMusic.java:196)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:920)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:173)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:156)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:410)
    at org.bukkit.Bukkit.reload(Bukkit.java:173)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:349)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:499)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:478)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: com.citizens.Citizens
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 16 more
2011-10-03 15:58:48 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-03 15:58:50 [INFO] [Citizens] 
2011-10-03 15:58:50 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
2011-10-03 15:58:50 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-03 15:58:50 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
2011-10-03 15:58:51 [INFO] [Citizens] version [1.1.1] loaded.
2011-10-03 15:58:51 [INFO] [Citizens] Economy plugin found (iConomy v5)</b>

I posted here first, but i will also let RyveMusic Devs know there is an issue

**Comment by fullwall** [comment]
RyveMusic needs to build against a newer version of Citizens.
