### ISSUE TITLE
what is the problem??

### ISSUE THREAD

**Issue by kvermaat** [CitizensDev/Citizens#244]
C:\Users\Kaspar\Desktop\Programmma's\Minecraft server\Minecraft 1.8.1 bukkit>"C:
\Program Files\Java\jre6\bin\java.exe" -Xms3072M -Xmx3072M -jar craftbukkit-0.0.
1-SNAPSHOT.jar
161 recipes
17 achievements
21:10:54 [INFO] Starting minecraft server version Beta 1.8.1
21:10:54 [INFO] Loading properties
21:10:54 [INFO] Starting Minecraft server on _:25565
21:10:54 [WARNING] *_*\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
21:10:54 [WARNING] The server will make no attempt to authenticate usernames. Be
ware.
21:10:54 [WARNING] While this makes the game possible to play without internet a
ccess, it also opens up the ability for hackers to connect with any username the
y choose.
21:10:54 [WARNING] To change this, set "online-mode" to "true" in the server.set
tings file.
21:10:54 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1020
-gb412283-b1124jnks (MC: 1.8.1)
21:10:54 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
21:10:54 [INFO] [PermissionsEx] sql backend registered!
21:10:54 [INFO] [PermissionsEx] file backend registered!
21:10:54 [INFO] [PermissionsEx] PermissionEx plugin initialized.
21:10:54 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
21:10:55 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
21:10:55 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
21:10:55 [INFO] [Permissions](Yeti) was initialized.
21:10:55 [INFO] [PermissionsEx] Initializing file backend
21:10:55 [INFO] [Permissions](Yeti) was initialized.
21:10:55 [INFO] [Permissions](Yeti) was initialized.
21:10:55 [INFO] [Permissions] version [3.1.6](Yeti)  loaded
21:10:55 [INFO] PhoenixTerrainMod v0.8.2 is now enabled
21:10:55 [INFO] SkylandsPlus 0.3.2: Enabled.
21:10:55 [INFO] Preparing level "world"
21:10:55 [INFO] Default game type: 0
21:10:55 [INFO] Preparing start region for level 0 (Seed: -5734136524723079545)
21:10:56 [INFO] Preparing start region for level 1 (Seed: -2196307643903802613)
21:10:56 [INFO] [BANK] succesfully loaded...
21:10:56 [INFO] Preparing start region for level 2 (Seed: -5734136524723079545)
21:10:57 [INFO] SkylandsPlus 0.3.2: Found Skylands world 'world_skylands'
21:10:57 [INFO] Preparing start region for level 3 (Seed: -5734136524723079545)
21:10:57 [INFO] DreamLand version 2.4 is enabled!
21:10:57 [INFO] Build 2.5.8 geladen Essentials van Zenexer, ementalo, Aelux, Bre
ttflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
21:10:57 [INFO] Essentials: Using config based permissions. Enable superperms in
 config.
21:10:57 [INFO] Build 2.5.8 geladen EssentialsChat van essentials team
21:10:57 [INFO] GroupManager - INFO - Scheduled Data Saving is set for every 10
minutes!
21:10:57 [INFO] GroupManager version 1.0(alpha-5) [Zombie-Version] is enabled!
21:10:57 [INFO] Build 2.5.8 geladen EssentialsSpawn van essentials team
21:10:58 [INFO] FoodTrees version 0.2 is Enabled!Made and Maintained by lookatme
go & Joshua Neicho!Enjoy!
21:10:58 [INFO] [iConomy - Celty] Enabled (12 ms)
21:10:58 [INFO] LightVote 1.59 initialized
21:10:58 [INFO] LightVote 1.59 scanning properties file.
21:10:58 [INFO] [PermissionsEx] Superperms support enabled.
21:10:58 [INFO] [PermissionsEx] v1.14 enabled
21:10:58 [INFO] Essentials: Using PermissionsEx based permissions.
21:10:58 [INFO] [Permissions] SQL Interface enabled!
21:10:58 [INFO] Stargate v.0.6.9 is enabled.
21:10:58 [INFO] [Stargate] Loaded 1 gate layouts
21:10:58 [INFO] [Stargate] {world} Loaded 10 stargates with 5 set as always-on
21:10:58 [INFO] [Stargate] {world_nether} Loaded 1 stargates with 7 set as alway
s-on
21:10:58 [INFO] [Stargate] {world_nightmare} Loaded 1 stargates with 9 set as al
ways-on
21:10:58 [INFO] [Stargate] {world_skylands} Loaded 1 stargates with 11 set as al
ways-on
21:10:58 [INFO] [VoxelSniper] Config loaded
21:10:58 [INFO] VoxelSniper version 5.019 is enabled! Snipe away.
21:10:58 [INFO] [WaterproofRedstone] Enabled.
21:10:58 [INFO] WirelessRedstone: WirelessRedstone version 1.2 BETA is loading..
.
21:10:58 [INFO] WirelessRedstone: Detected Permissions version 2.7.7
21:10:58 [INFO] WirelessRedstone: Registering Events...
21:10:58 [INFO] WirelessRedstone version 1.2 BETA is enabled!
21:10:58 [INFO] WorldEdit 4.6 enabled.
21:10:58 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin
 for permissions.
21:10:58 [INFO] WorldGuard: Permissions plugin detected! Using Permissions plugi
n for permissions.
21:10:58 [INFO] WorldGuard: (world) Single session is enforced.
21:10:58 [INFO] WorldGuard: (world) TNT ignition is PERMITTED.
21:10:58 [INFO] WorldGuard: (world) Lighters are PERMITTED.
21:10:58 [INFO] WorldGuard: (world) Lava fire is blocked.
21:10:58 [INFO] WorldGuard: (world) Fire spread is UNRESTRICTED.
21:10:58 [INFO] WorldGuard: Loaded configuration for world 'world"
21:10:58 [INFO] WorldGuard: (world_nether) Single session is enforced.
21:10:58 [INFO] WorldGuard: (world_nether) TNT ignition is PERMITTED.
21:10:58 [INFO] WorldGuard: (world_nether) Lighters are PERMITTED.
21:10:58 [INFO] WorldGuard: (world_nether) Lava fire is blocked.
21:10:58 [INFO] WorldGuard: (world_nether) Fire spread is UNRESTRICTED.
21:10:58 [INFO] WorldGuard: Loaded configuration for world 'world_nether"
21:10:58 [INFO] WorldGuard: (world_nightmare) Single session is enforced.
21:10:58 [INFO] WorldGuard: (world_nightmare) TNT ignition is PERMITTED.
21:10:58 [INFO] WorldGuard: (world_nightmare) Lighters are PERMITTED.
21:10:58 [INFO] WorldGuard: (world_nightmare) Lava fire is blocked.
21:10:58 [INFO] WorldGuard: (world_nightmare) Fire spread is UNRESTRICTED.
21:10:58 [INFO] WorldGuard: Loaded configuration for world 'world_nightmare"
21:10:58 [INFO] WorldGuard: (world_skylands) Single session is enforced.
21:10:58 [INFO] WorldGuard: (world_skylands) TNT ignition is PERMITTED.
21:10:58 [INFO] WorldGuard: (world_skylands) Lighters are PERMITTED.
21:10:58 [INFO] WorldGuard: (world_skylands) Lava fire is blocked.
21:10:58 [INFO] WorldGuard: (world_skylands) Fire spread is UNRESTRICTED.
21:10:58 [INFO] WorldGuard: Loaded configuration for world 'world_skylands"
21:10:58 [INFO] WorldGuard: 3 regions loaded for 'world'
21:10:58 [INFO] WorldGuard: 0 regions loaded for 'world_nether'
21:10:58 [INFO] WorldGuard: Unable to register missing event type SNOW_FORM
21:10:58 [INFO] WorldGuard 5.2.2 enabled.
21:10:58 [INFO] [Permissions] version [2.7.2](Yeti)  loaded
21:10:58 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin
 for permissions.
21:10:58 [INFO] WorldGuard: Permissions plugin detected! Using Permissions plugi
n for permissions.
21:10:58 [INFO] [Stargate] Found Permissions (v2.7.2)
21:10:58 [INFO] [Modifyworld] Modifyworld disabled. Check config.yml!
21:10:58 [INFO] [Modifyworld] Modifyworld disabled!
21:10:58 [INFO] [Permissions] version [2.7.7](Yeti)  loaded
21:10:58 [INFO] WorldEdit: Permissions plugin detected! Using Permissions plugin
 for permissions.
21:10:58 [INFO] WorldGuard: Permissions plugin detected! Using Permissions plugi
n for permissions.
21:10:59 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester,
 trader, wizard
21:10:59 [INFO] [Citizens] Permissions system found (PermissionsEx v1.14)
21:10:59 [INFO] [Citizens] version [1.1.1] loaded.
21:10:59 [INFO] [Citizens] Economy plugin found (iConomy v6)
21:10:59 [INFO] Done (0.373s)! For help, type "help" or "?"
21:10:59 [INFO] Reached end of stream
21:10:59 [INFO] Reached end of stream
21:10:59 [INFO] Reached end of stream
21:10:59 [INFO] Reached end of stream
21:10:59 [INFO] [Citizens] Loaded 66 NPCs.
21:10:59 [INFO] [Citizens] Loaded 0 quests.

**Comment by fullwall** [comment]
You need to update your craftbukkit.
