### ISSUE TITLE
1.1.2 says its 1.1.1?

### ISSUE THREAD

**Issue by Deathlysteve** [CitizensDev/Citizens#247]
INFORMATION:
Citizens: 1.1.2 (thinks its 1.1.1)
CB: 1240

I just downloaded 1.1.2, and now when I restart/reload my server, Citizens doesnt work. I looked in console and it said this:

2011-10-05 23:35:29 [INFO] [Citizens] NPC types loaded: quester, healer, blacksmith, trader, wizard, guard
2011-10-05 23:35:29 [INFO] [Citizens] Permissions system found (PermissionsBukkit v1.2)
2011-10-05 23:35:29 [SEVERE] Error occurred while enabling Citizens v1.1.1 (Is it up to date?): net/citizensnpcs/PermissionManager
java.lang.NoClassDefFoundError: net/citizensnpcs/PermissionManager
    at net.citizensnpcs.questers.QuesterCommands.addPermissions(QuesterCommands.java:259)
    at net.citizensnpcs.permissions.PermissionManager.addPermissions(PermissionManager.java:118)
    at net.citizensnpcs.permissions.PermissionManager.<init>(PermissionManager.java:51)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:103)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:941)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:416)
    at org.bukkit.Bukkit.reload(Bukkit.java:182)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:358)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.PermissionManager
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 24 more
2011-10-05 23:35:29 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-05 23:35:37 [INFO] [Citizens] 
2011-10-05 23:35:37 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
2011-10-05 23:35:37 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-05 23:35:37 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-05 23:35:42 [INFO] [Citizens] 
2011-10-05 23:35:42 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
2011-10-05 23:35:42 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-05 23:35:42 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-10-05 23:35:51 [INFO] [Citizens] 
2011-10-05 23:35:51 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
2011-10-05 23:35:51 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-10-05 23:35:51 [INFO] [Citizens] Economy plugin found (iConomy v6)

I noticed at the top of that it says: Error occurred while enabling Citizens v1.1.1 (Is it up to date?)
...so after i saw that it was 1.1.1, i redownloaded and reinstalled, still 1.1.1, i then checked in the 1.1.2 citizens.jar, and it says the version is 1.1.1.... uhm thats wrong?

maybe the download isnt right... help

**Comment by sshadow** [comment]
Getting the same issue and I just now downloaded it and upgraded.

**Comment by ghost** [comment]
Would you expect the plugins to update their version numbers automatically? NO! It's a mistake with the author, silly. And if it's really distracting you, edit the plugin.yml or whatever in the jar and change the version number to what ever you want.

**Comment by Deathlysteve** [comment]
i already tried that, it still didnt work.

**Comment by sshadow** [comment]
Hi ass, meet foot.Chris/Adminhttps://empirehostings.comFrom: Juze Sent: Fri, Oct 7, 2011 3:41 AMTo: sshadow CC:Subject: Re: [Citizens] 1.1.2 says its 1.1.1? (#247)Would you expect the plugins to update their version numbers automatically? NO! It's a mistake with the author, silly. And if it's really distracting you, edit the plugin.yml or whatever in the jar and change the version number to what ever you want.-- Reply to this email directly or view it on GitHub:https://github.com/CitizensDev/Citizens/issues/247#issuecomment-2319214

**Comment by fullwall** [comment]
It looks like just a version number error... the actual error is happening because you've updated your core but not the type JARs.
