### ISSUE TITLE
NPC's glitch into another and don't work anymore (same name)

### ISSUE THREAD

**Issue by Meph91** [CitizensDev/Citizens#262]
There is a problem with npc's with the same name.
They're glitching on one position and don't work anymore. Guards don't work before glitching even after upgrading to 1.1.2 and i can't select them. Even after downgrading there is this issue.

**Comment by Jogeta** [comment]
upgrade to the latest dev build

**Comment by Meph91** [comment]
And where can I get the latest dev build? All I see is the rec build.

**Comment by Jogeta** [comment]
http://citizensnpcs.net/

**Comment by Meph91** [comment]
With the Dev Build, the console gave me an error.

[SEVERE] Error occurred while enabling Citizens v1.1.2 (Is it up to date?): null; mapping values are not allowed here
mapping values are not allowed here
 in "<reader>", line 41, column 53:
    5px; padding: 0.4em; position: absolute; bot ... 
                ^

```
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:745)
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:307)
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:183)
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:564)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:124)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
at org.bukkit.util.config.Configuration.load(Configuration.java:82)
at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:31)
at net.citizensnpcs.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:25)
at net.citizensnpcs.properties.properties.UtilityProperties.initialize(UtilityProperties.java:21)
at net.citizensnpcs.properties.PropertyManager.registerProperties(PropertyManager.java:17)
at net.citizensnpcs.SettingsManager.setupVariables(SettingsManager.java:79)
at net.citizensnpcs.Citizens.onEnable(Citizens.java:81)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:941)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157)
at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
```

Even after deleting every Citizens file and put it in again.

**Comment by Jogeta** [comment]
im not sure about that one

**Comment by fullwall** [comment]
Incorrect config

**Comment by Meph91** [comment]
Why is it closed now? oO It was the config of your dev build, so what am I gonna do now? The problem is still there after going back to 1.1.2 and dev build isn't working at all.

**Comment by fullwall** [comment]
The npc merging issue is fixed in the dev build, but you have a config issue as well.
