### ISSUE TITLE
Entity error my server freeze out please fix fast :( (citizens 1.1.2,bukkit 1240)

### ISSUE THREAD

**Issue by dretax** [CitizensDev/Citizens#269]
[SEVERE] Could not pass event ENTITY_TARGET to Citizens
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at net.citizensnpcs.SettingsManager.getInt(SettingsManager.java:41)
    at net.citizensnpcs.wizards.Wizard.onRightClick(Wizard.java:260)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:165)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:113)
    at org.bukkit.plugin.java.JavaPluginLoader$68.execute(JavaPluginLoader.java:719)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:321)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:903)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by dretax** [comment]
http://pastebin.com/G42D4q9G Here is my log for more info what plugins are running on my server

**Comment by fullwall** [comment]
There's a config error in the wizards section. Quotes are put around a number somewhere in your config.
