### ISSUE TITLE
citizens wont load on start up

### ISSUE THREAD

**Issue by mickartz** [CitizensDev/Citizens#271]
2011-10-10 08:01:52 [SEVERE] Could not load 'plugins/Citizens.jar' in folder 'plugins': 
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:127)
    at java.util.jar.JarFile.<init>(JarFile.java:135)
    at java.util.jar.JarFile.<init>(JarFile.java:99)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:60)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:215)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:139)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:104)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by ghost** [comment]
i had this issue so i downloaded the experimental version with all the types and put the jar in first then ran server then put the types in the types folder and started server again.
So all i need to know now is, what are the differences between experimental version and the stable version?

**Comment by ghost** [comment]
ok forget about wut i said when u use the experimental one u cant spawn npcs =(

**Comment by TRULYTWIST3D** [comment]
yup very same issue here... i know i have the right build... i tried isolating it making sure it wasnt some random incompatibility... it just keeps spewing out this error

i really want this plugin lol... its just awesome

**Comment by fullwall** [comment]
That's an incorrect download. Try http://ci.citizensnpcs.net or BukkitDev.

**Comment by mickartz** [comment]
this is NOT resolved.. I have installed the file from the link suggested
same errors (ps this was teh EXACT file I had installed originally

2011-10-11 11:15:07 [SEVERE] Could not load 'plugins/Citizens.jar' in folder 'plugins': 
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:127)
    at java.util.jar.JarFile.<init>(JarFile.java:135)
    at java.util.jar.JarFile.<init>(JarFile.java:99)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:60)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:215)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:139)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:104)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by TRULYTWIST3D** [comment]
the link provided fixed mine...are you sure that your using the right bukkit build and theres no incompatibilities?... try temporarily removing all other plugins (except essentials if your using essentials)
and use build 1240
