### ISSUE TITLE
"NoSuchMethodError" Can't create NPCs

### ISSUE THREAD

**Issue by rc-traviolia** [CitizensDev/Citizens#278]
Here's my bug report
I'm Running:

2011-10-10 16:36:45 [INFO] Starting minecraft server version Beta 1.8.1
2011-10-10 16:36:45 [INFO] Loading properties
2011-10-10 16:36:45 [INFO] Starting Minecraft server on 67.231.253.169:25565
2011-10-10 16:36:45 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1067-g6301507-b1185jnks (MC: 1.8.1)
2011-10-10 16:36:45 [INFO] [Permissions](Yeti) was initialized.
2011-10-10 16:36:45 [INFO] [Permissions] version [3.1.6](Yeti)  loaded
2011-10-10 16:36:45 [INFO] Preparing level "JOTSMC"
2011-10-10 16:36:45 [INFO] Default game type: 0
2011-10-10 16:36:45 [INFO] Preparing start region for level 0 (Seed: 4945059210562742324)
2011-10-10 16:36:46 [INFO] Preparing start region for level 1 (Seed: 4945059210562742324)
2011-10-10 16:36:46 [INFO] RepairShop version 1.1 found and will use Permissions v3.1.6
2011-10-10 16:36:46 [INFO] RepairShop version 1.1 hooked successfully into iConomy!
2011-10-10 16:36:46 [INFO] RepairShop version 1.1 is enabled!
2011-10-10 16:36:46 [INFO] [iChat] Permissions 3.1.6 found
2011-10-10 16:36:46 [INFO] iChat (v2.4.2) enabled
2011-10-10 16:36:46 [INFO] [kaDiving] version 1.0 is enabled!
2011-10-10 16:36:46 [INFO] [iConomy - Celty] Enabled (15 ms)
2011-10-10 16:36:46 [INFO] [MobileAdmin] Loading server stats.
2011-10-10 16:36:46 [INFO] [MobileAdmin] Loading chat log.
2011-10-10 16:36:46 [INFO] [MobileAdmin] Loading users.
2011-10-10 16:36:46 [INFO] [MobileAdmin] Starting server...
2011-10-10 16:36:46 [INFO] [MobileAdmin] Version 3.2.1 is enabled!
2011-10-10 16:36:46 [INFO] [MobileAdmin] Server listening on *:5839
2011-10-10 16:36:46 [INFO] PickBoat version 0.3.6 is enabled!
2011-10-10 16:36:46 [INFO] [Tomb](version 0.7) Enabled
2011-10-10 16:36:46 [INFO] [Tomb] Successfully linked with Permissions.

-----------------------------------------Skipping ahead-------------------------------------------

2011-10-10 16:38:05 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
2011-10-10 16:38:05 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)2011-10-10 16:38:05 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)2011-10-10 16:38:05 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)2011-10-10 16:38:05 [SEVERE]   at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)2011-10-10 16:38:05 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-10 16:38:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)2011-10-10 16:38:05 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-10 16:38:05 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2011-10-10 16:38:05 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
2011-10-10 16:38:05 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
2011-10-10 16:38:05 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
2011-10-10 16:38:05 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-10-10 16:38:05 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-10 16:38:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)2011-10-10 16:38:05 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-10 16:38:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-10 16:38:31 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
2011-10-10 16:38:31 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
2011-10-10 16:38:31 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)2011-10-10 16:38:31 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)2011-10-10 16:38:31 [SEVERE]   at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)2011-10-10 16:38:31 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-10 16:38:31 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)2011-10-10 16:38:31 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-10 16:38:31 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2011-10-10 16:38:31 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
2011-10-10 16:38:31 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
2011-10-10 16:38:31 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
2011-10-10 16:38:31 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-10-10 16:38:31 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)2011-10-10 16:38:31 [SEVERE]  at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)2011-10-10 16:38:31 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-10 16:38:31 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-10 16:38:39 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2011-10-10 16:38:39 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-10 16:38:39 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-10-10 16:38:39 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-10 16:38:39 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
2011-10-10 16:38:39 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
2011-10-10 16:38:39 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
2011-10-10 16:38:39 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-10 16:38:39 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-10 16:38:39 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

EDIT: If the formatting is bad, blame my server's log... apparently it doesn't copy-paste well, i had to Ctrl + F to find all the 2011's and click on each one and hit enter to get it to look normal! I hope you guys can help!

**Comment by fullwall** [comment]
Incorrect RB for your Citizens version.
