### ISSUE TITLE
Quest Talknpc (delivery air)

### ISSUE THREAD

**Issue by Meph91** [CitizensDev/Citizens#286]
Tried do make a quest, so that someone must talk to another npc with the delivery objective. I have read that it would be possible. But he always says me, quest isn't completed and with /quest status the console give me:

2011-10-12 19:58:06 [SEVERE] java.lang.NullPointerException
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.utils.StringUtils.format(StringUtils.java:249)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.utils.StringUtils.format(StringUtils.java:245)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.utils.StringUtils.formatter(StringUtils.java:277)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.questers.quests.types.DeliveryQuest.getStatus(DeliveryQuest.java:65)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.questers.QuesterCommands.viewCurrentQuestStatus(QuesterCommands.java:415)
2011-10-12 19:58:06 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-12 19:58:06 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-10-12 19:58:06 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-10-12 19:58:06 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
2011-10-12 19:58:06 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
2011-10-12 19:58:06 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2011-10-12 19:58:06 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-12 19:58:06 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:358)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-12 19:58:06 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

This is my quest file:

Tutorial:
    texts:
        description: Go to the guard.
        completion: <g>Good.
        acceptance: <g>Alright.
    repeats: 1
    objectives:
        '0':
            '0':
                type: delivery
                item: 0
                npcdestination: 10
    rewards:
        '0':
            type: money
            money: 2
            give: true

**Comment by scandragon** [comment]
type: delivery
materialid: 0
amount: 1 #or so I assume. But an amount must be given

**Comment by Xaladon** [comment]
You can't give Airs. You're better off giving an item on quest acceptance (by preceding the actual objective with a 'move location' objective at the location of quest acceptance, which rewards an item) and having the player to hand in that item at the second npc, using the 'finishhere:' node.

Tutorial:
texts:
description: Go to the guard.
completion: Good.
acceptance: Alright.
repeats: 1
objectives:
'0':
'0':
type: move location
location:
x: [type x coordinate here]
y: [type y coordinate here]
z: [type z coordinate here]
world: [type world here]
amount: 10
rewards:
'0':
type: item
id: 339 (this is a Paper)
amount: 1
'1':
'0':
type: delivery
materialid: 339
amount: 1
npcdestination: 10
rewards:
'0':
type: money
money: 2
take: false

**Comment by scandragon** [comment]
You can indeed give airs.. You can also give 0 air, no problem there
Just tried making a quest with delivery of 0 airs (and also tested the new delay) on build #253
The fully working quest is here
http://pastebin.com/03ZTksv0

**Comment by Meph91** [comment]
I've tried this quest with build #253,but the quest doesn't end. Could it be a conflict,that the npc id 10 is a quester,too?

**Comment by Xaladon** [comment]
I tried that once, didn't work for me.. Strange. Might try it again.

**Comment by scandragon** [comment]
Meph91, did you try editing it according to my example on pastebin?
Simply replace the texts, quest name and npc id with yours, and the quest will work

**Comment by Meph91** [comment]
@scandragon: Yes, it was exactly your quest, except the npcdestination ID.

**Comment by Drehverschluss** [comment]
this error is fixed in the 271 build
