### ISSUE TITLE
Permissions 3.1 wont't work

### ISSUE THREAD

**Issue by FackTheCampers** [CitizensDev/Citizens#300]
Hey, i use (tried to use) citizens v 1.1.2 and my permissions doesn't work. I use Permissons 3.1 by yeti.
When I load the server i comes up: 
2011-10-15 15:02:07 [SEVERE] Permission node 'citizens._' in plugin description file for Citizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains invalid value
    at org.bukkit.permissions.Permission.extractChildren(Permission.java:216)
    at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescriptionFile.java:310)
    at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:264)
    at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:36)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:69)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:138)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:408)
    at org.bukkit.Bukkit.reload(Bukkit.java:173)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:755)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:720)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:713)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:91)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-15 15:02:08 [SEVERE] Permission node 'citizens._' in plugin description file for Citizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains invalid value
    at org.bukkit.permissions.Permission.extractChildren(Permission.java:216)
    at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescriptionFile.java:310)
    at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:264)
    at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:36)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:69)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:138)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:408)
    at org.bukkit.Bukkit.reload(Bukkit.java:173)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:755)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:720)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:713)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:91)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Any help, or do still Citizens support Permissions?
Sorry for bad english :p

**Comment by scandragon** [comment]
Support for the outdated Permissions was removed a while ago
Switch to a superperm plugin such as permissionsbukkit

**Comment by FackTheCampers** [comment]
Nah, I will stick to permissions. I don't understand why they took permissions supprt away though, many still use permissions.

**Comment by scandragon** [comment]
You need to read this: http://forums.bukkit.org/threads/public-announcement-for-permissions.33651/

And I quote:
Stop using Permissions

I will begin deleting all jar files that relate to Permissions 1 - 3, and hopefully (this may or may not happen, and I don't really care if it's a bad move, it's worse to leave this issue around) create a way to block the permissions plugin from even loading, very soon. Permissions was a temporary solution to a problem that has gone out of control.

Yes I have made threads on this subject so I'm not going too far into the details, the point is. Please migrate to SuperPerms immediately so that you are not left in the dark and when the upgrade time comes you are complaining.

**Comment by fullwall** [comment]
Citizens doesn't support Permissions 3.1, also you need to update your craftbukkit.
