### ISSUE TITLE
Citizens Update using too much memory?

### ISSUE THREAD

**Issue by robxu9** [CitizensDev/Citizens#307]
Started getting these today when I updated my Citizens from 1.1.1 to 1.1.2...

2011-10-18 18:48:51 [WARNING] Task of 'Citizens' generated an exception
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:640)
        at net.minecraft.server.NetworkManager.<init>(NetworkManager.java:69)
        at net.citizensnpcs.resources.npclib.NPCNetworkManager.<init>(NPCNetworkManager.java:14)
        at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:18)
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Can you try profiling with jprofiler?

**Comment by robxu9** [comment]
I don't have jprofiler... :-/

On Oct 21, 2011, at 6:30, fullwall
reply@reply.github.com
wrote:
