### ISSUE TITLE
Could not pass event CHUNK_LOAD to Citizens

### ISSUE THREAD

**Issue by liquidox** [CitizensDev/Citizens#311]
12:22:33 [SEVERE] Could not pass event CHUNK_LOAD to Citizens
java.lang.NullPointerException
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:69)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
        at net.citizensnpcs.listeners.WorldListen.onChunkLoad(WorldListen.java:72)
        at org.bukkit.plugin.java.JavaPluginLoader$52.execute(JavaPluginLoader.java:621)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:92)
        at net.minecraft.server.PlayerInstance.<init>(PlayerInstance.java:31)
        at net.minecraft.server.PlayerManager.a(PlayerManager.java:45)
        at net.minecraft.server.PlayerManager.addPlayer(PlayerManager.java:84)
        at net.minecraft.server.ServerConfigurationManager.c(ServerConfigurationManager.java:139)
        at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:121)
        at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:39)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:94)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Trying to spawn an npc in an invalid world.
