### ISSUE TITLE
I keep on getting this error when starting my server.

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#330]
161 recipes
17 achievements
17:31:27 [INFO] Starting minecraft server version Beta 1.8.1
17:31:27 [INFO] Loading properties
17:31:27 [INFO] Starting Minecraft server on 5.7.102.142:25565
17:31:27 [WARNING] ***\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
17:31:27 [WARNING] The server will make no attempt to authenticate usernames. Be
ware.
17:31:27 [WARNING] While this makes the game possible to play without internet a
ccess, it also opens up the ability for hackers to connect with any username the
y choose.
17:31:27 [WARNING] To change this, set "online-mode" to "true" in the server.set
tings file.
17:31:27 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1028
-g5cd469c-b1130jnks (MC: 1.8.1)
17:31:27 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
17:31:28 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
17:31:28 [SEVERE] Permission node 'citizens._' in plugin description file for Ci
tizens v1.1.1 is invalid
java.lang.IllegalArgumentException: Child 'citizens.admin.override._' contains i
nvalid value
        at org.bukkit.permissions.Permission.extractChildren(Permission.java:216
)
        at org.bukkit.permissions.Permission.loadPermission(Permission.java:193)

```
    at org.bukkit.plugin.PluginDescriptionFile.loadPermissions(PluginDescrip
```

tionFile.java:310)
        at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile
.java:264)
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.
java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:69)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:213)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:103)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:136)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
17:31:28 [INFO] Preparing level "James_Church"
17:31:28 [INFO] Default game type: 0
17:31:28 [INFO] Preparing start region for level 0 (Seed: 3365897261687280726)
17:31:29 [INFO] Preparing start region for level 1 (Seed: 7236955041452819472)
17:31:29 [INFO] Preparing spawn area: 20%
17:31:29 [INFO] Permission system not detected, defaulting to OP
17:31:29 [INFO] [ARG] Checking/loading files...
17:31:29 [INFO] [ARG] Loaded 0 items from Regions.txt
17:31:29 [INFO] [ARG] Loaded 0 items from FriendsList.txt
17:31:29 [INFO] [ARG] Loaded 0 items from LastOnline.txt
17:31:29 [INFO] [ARG] Scheduling tasks...
17:31:29 [INFO] AutoRegionGuard version 0.5 is enabled!
17:31:29 [INFO] Friendly Creepers has been enabled!
17:31:29 [INFO] Lockette version 1.4 is being enabled!  Yay!  (Core version 1.1)

17:31:29 [INFO] Lockette: Detected craftbukkit build [1130] ok.
17:31:29 [INFO] Lockette: Using ops file for admin permissions.
17:31:29 [INFO] Lockette: Ready to protect your containers.
17:31:29 [INFO] PermissionsBukkit v1.2 is now enabled
17:31:29 [INFO] [PhysicalShop] version 7 enabled
17:31:29 [INFO] [Citizens] No NPC types loaded.
17:31:29 [INFO] [Citizens] Permissions system found (PermissionsBukkit v1.2)
17:31:30 [INFO] [Citizens] version [1.1.2] loaded.
17:31:30 [INFO] Server permissions file permissions.yml is empty, ignoring it
17:31:30 [INFO] Done (0.191s)! For help, type "help" or "?"
17:31:30 [INFO] [Citizens] Loaded 0 NPCs.

**Comment by fullwall** [comment]
Using an old craftbukkit.
