### ISSUE TITLE
Can Not Spawn NPC's. 

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#331]
Alright, I've troubleshot this down to two things now. It's either an incompatability with a different mod (I was able to run this before, got rid of it over instability on 2GB of RAM) or its due to a recent Spoutcraft update, as I had this mod before the most recent version of Spout (1.0.2.115)  and Spoutcraft (Also 1.0.2.115). Now I've tried to solve possible incompatibilities by getting rid of mods I installed since I last had this mod. I may have over looked one though, so if someone could, just take a look at the following list for incompatibilities. The Server Log where errors occur are below the Mod List. Definitely Compatible Mods are mods I had during my original install of Citizens.
# Mod List

-Book Worm
-Chair Craft (Definitely Compatible)
-Multi World (No Portals)
-MyHome
-NetherBan (Definitely Compatible)
-RPG Overhead (Definitely Compatible)
-Spout (Already Mentioned)
-SpoutCoords
-Spyer Package (SpyerAdmin, SpyerAdminCommands and SpyerFun)
-The Werewolf (Definitely Compatible)
-WolfPound 1.1b1
-WorldEdit (Definitely Compatible)
-WorldGuard (Also Having Issues with this mod.)

This is the Server Log from the last time it was run:

[INFO] Starting minecraft server version Beta 1.8.1
2011-10-21 21:53:31 [INFO] Loading properties
2011-10-21 21:53:31 [INFO] Starting Minecraft server on _:25565
2011-10-21 21:53:31 [WARNING] *_*\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
2011-10-21 21:53:31 [WARNING] The server will make no attempt to authenticate usernames. Beware.
2011-10-21 21:53:31 [WARNING] While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
2011-10-21 21:53:31 [WARNING] To change this, set "online-mode" to "true" in the server.settings file.
2011-10-21 21:53:31 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1067-g6301507-b1185jnks (MC: 1.8.1)
2011-10-21 21:53:32 [INFO] [BaseBukkitPlugin 1.6] initialized
2011-10-21 21:53:32 [INFO] Spout 1.0.6.381 has been initialized
2011-10-21 21:53:32 [INFO] Preparing level "world"
2011-10-21 21:53:32 [INFO] Default game type: 0
2011-10-21 21:53:33 [INFO] Preparing start region for level 0 (Seed: 8356233760337247441)
2011-10-21 21:53:34 [INFO] New max size: 324
2011-10-21 21:53:34 [INFO] New max size: 400
2011-10-21 21:53:34 [INFO] New max size: 484
2011-10-21 21:53:34 [INFO] New max size: 784
2011-10-21 21:53:34 [INFO] New max size: 1444
2011-10-21 21:53:34 [INFO] New max size: 4096
2011-10-21 21:53:34 [INFO] New max size: 4356
2011-10-21 21:53:34 [INFO] Preparing spawn area: 69%
2011-10-21 21:53:35 [INFO] Preparing spawn area: 81%
2011-10-21 21:53:36 [INFO] Preparing spawn area: 93%
2011-10-21 21:53:36 [INFO] Preparing start region for level 1 (Seed: -2117929955373032386)
2011-10-21 21:53:37 [INFO] Preparing spawn area: 8%
2011-10-21 21:53:38 [INFO] ChairCraft 1.2.6 is enabled.
2011-10-21 21:53:38 [INFO] [MultiWorld] Enabling MultiWorld
2011-10-21 21:53:38 [INFO] [MultiWorld] No known permissions system detected! Defaulting to Op...
2011-10-21 21:53:38 [INFO] Preparing start region for level 2 (Seed: 8783513236775121935)
2011-10-21 21:53:39 [INFO] Preparing spawn area for AirCanada, 69%
2011-10-21 21:53:39 [INFO] Preparing start region for level 3 (Seed: 0)
2011-10-21 21:53:40 [INFO] Preparing spawn area for Creative, 97%
2011-10-21 21:53:40 [INFO] Preparing start region for level 4 (Seed: 0)
2011-10-21 21:53:41 [INFO] Preparing spawn area for Survive, 85%
2011-10-21 21:53:41 [INFO] Preparing start region for level 5 (Seed: 0)
2011-10-21 21:53:42 [INFO] Preparing spawn area for Legit, 93%
2011-10-21 21:53:42 [INFO] Preparing start region for level 6 (Seed: 1047656781357756648)
2011-10-21 21:53:43 [INFO] Preparing spawn area for ModernRP, 89%
2011-10-21 21:53:43 [INFO] [MultiWorld] load complete
2011-10-21 21:53:43 [INFO] [MultiWorld] v1.5.1 enabled.
2011-10-21 21:53:43 [INFO] Need to download 2 object(s)
2011-10-21 21:53:43 [INFO]  - Downloading file : http://stethoscopesmp.com/tkelly/lib/sqlite.jar
2011-10-21 21:53:44 [INFO] [MYHOME]: 0 homes loaded
2011-10-21 21:53:44 [WARNING] [MYHOME] A permission plugin isn't loaded.
2011-10-21 21:53:44 [WARNING] [MYHOME] 'Help' isn't detected. No /help support.
2011-10-21 21:53:44 [INFO] [MYHOME] MyHome 1.9.3 enabled
2011-10-21 21:53:44 [INFO] [NetherBan] Permission system not detected, defaulting to OP
2011-10-21 21:53:44 [INFO] [NetherBan] NetherBan Enabled. Torturing souls...
2011-10-21 21:53:44 [INFO] [RPGOverhead] plugin enabled, detecting RPGPlugins now
2011-10-21 21:53:44 [INFO] [SpoutCoords v0.6.1] is now enabled!
2011-10-21 21:53:45 [INFO] SpyerAdmin has completed updating the script successfully.
2011-10-21 21:53:45 [SEVERE] sun.org.mozilla.javascript.internal.WrappedException: Wrapped java.lang.ClassNotFoundException: com.earth2me.essentials.Console (<Unknown source>#115) in <Unknown source> at line number 115
2011-10-21 21:53:45 [INFO] SpyerAdminCommands module version 1.5 stable, a spying utility for administrators and moderators (CommandBook commands module), is active. Part of the Spyer package by [nickguletskii200]
2011-10-21 21:53:45 [INFO] SpyerFun module version 1.5_3 stable, a spying utility for normal players, is active. Part of the Spyer package by [nickguletskii200]
2011-10-21 21:53:45 [INFO] [WolfPound] - Version 1.1b1 Enabled
2011-10-21 21:53:45 [INFO] [AllPay] - Version 3.0 - using only an item based economy for WolfPound v1.1b1
2011-10-21 21:53:45 [INFO] WorldEdit 4.6 enabled.
2011-10-21 21:53:45 [INFO] WorldEdit: No known permissions plugin detected. Using configuration file for permissions.
2011-10-21 21:53:45 [SEVERE] Error occurred while enabling WorldGuard v5.3 (Is it up to date?): com.sk89q.bukkit.migration.PermissionsResolverManager.<init>(Lorg/bukkit/plugin/Plugin;Ljava/lang/String;Ljava/util/logging/Logger;)V
java.lang.NoSuchMethodError: com.sk89q.bukkit.migration.PermissionsResolverManager.<init>(Lorg/bukkit/plugin/Plugin;Ljava/lang/String;Ljava/util/logging/Logger;)V
    at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:134)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:920)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:173)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:156)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-21 21:53:45 [INFO] BookWorm 'Spout' support enabled.
2011-10-21 21:53:45 [INFO] BookWorm v1.7 loaded!
2011-10-21 21:53:45 [INFO] SpyerAdmin module version 1.5_3 stable, a spying utility for administrators and moderators (main module), is active. Part of the Spyer package by [nickguletskii200]
2011-10-21 21:53:45 [INFO] [BaseBukkitPlugin 1.6] Server version compatibility check succeeded
2011-10-21 21:53:45 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
2011-10-21 21:53:46 [INFO] [Citizens] version [1.1.2] loaded.
2011-10-21 21:53:46 [INFO] Server permissions file permissions.yml is empty, ignoring it
2011-10-21 21:53:46 [INFO] Done (1.318s)! For help, type "help" or "?"
2011-10-21 21:53:46 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-21 21:53:46 [INFO] [RPGPlugin] new rpg plugin found and will be enabled: TheWerewolf v2.2
2011-10-21 21:53:46 [INFO] [TheWerewolf] Permission system not detected, defaulting to OP
2011-10-21 21:53:46 [INFO] [TheWerewolf] added recipe for cure
2011-10-21 21:53:46 [INFO] GodxComplex [/192.168.0.104:4343] logged in with entity id 543 at ([world] -41.32465284061796, 27.0, -355.89928428016515)
2011-10-21 21:53:48 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?
2011-10-21 21:53:48 [INFO] Reading data
2011-10-21 21:53:48 [INFO] [Spout] Successfully authenticated GodxComplex's Spoutcraft client. Running client version: 1.0.6.564
2011-10-21 22:06:16 [INFO] Connection reset
2011-10-21 22:06:16 [INFO] GodxComplex lost connection: disconnect.quitting
2011-10-21 22:06:34 [INFO] Stopping server
2011-10-21 22:06:34 [INFO] ChairCraft 1.2.6 is disabled.
2011-10-21 22:06:34 [INFO] [MultiWorld] Disabled.
2011-10-21 22:06:34 [INFO] [NetherBan] NetherBan Disabled.

**Comment by Drehverschluss** [comment]
its so funny that i read this error about 10 times in this forum....

your running your server with CB#1317 or higher right?

Citizens only work with #1240

**Comment by ghost** [comment]
Thanks man. I wasn't sure and thought the update might be the problem, but many of my other mods still work, so I wasn't sure. Next time I'll check the support versions, it seemed very overwhelming and I wanted somebody who knew what they were talking about. Thanks a lot for the help, sorry for asking twice.
