### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by dennis6981** [CitizensDev/Citizens#346]
The Creating of waypoints works, but after a server reboot I get this error message and the waypoints are no longer loaded.

Bukkit Version : 1366
Citizens Version :  devBuild-280

12:48:53 [WARNING] Task of 'Citizens' generated an exception
java.lang.NumberFormatException: For input string: "MemorySection[path='0.basic.waypoints'"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1242)
    at java.lang.Double.parseDouble(Double.java:527)
    at net.citizensnpcs.properties.properties.BasicProperties.getWaypoints(BasicProperties.java:265)
    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:345)
    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:170)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:293)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fullwall** [comment]
Fixed, issue with new Bukkit configuration.
