### ISSUE TITLE
Allow any item for Wizard interaction

### ISSUE THREAD

**Issue by cortices** [CitizensDev/Citizens#348]
This is a suggestion. Please allow 'asterisk' in the settings field for wizard interact item. I don't want to use only a certain item, it is more flexible with an option for all.I get an error if I try to put 'asterisk' there currently.

**Comment by fullwall** [comment]
The latest build changes this.

**Comment by cortices** [comment]
The latest build of what? I have tried the experimental build with all the NPC types from the custom download page on the website and does not enable, java has a zip parsing error. If I use the stable build, I get the same problem as before. This is the error I get:

`[SEVERE] Could not pass event ENTITY_TARGET to Citizens
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at net.citizensnpcs.SettingsManager.getInt(SettingsManager.java:41)
    at net.citizensnpcs.wizards.Wizard.onRightClick(Wizard.java:260)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:165)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:113)
    at org.bukkit.plugin.java.JavaPluginLoader$68.execute(JavaPluginLoader.java:735)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:337)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:903)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)`
