### ISSUE TITLE
Console error on /npc create bob

### ISSUE THREAD

**Issue by fsmythe** [CitizensDev/Citizens#355]
On me (operator on server) doing /npc create bob

The server gave an error, and asked me to refer to the console. Here it is!

Thanks in advance for your help :)

2011-10-30 23:29:14 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
2011-10-30 23:29:14 [SEVERE]    at java.util.ArrayList.rangeCheck(Unknown Source)
2011-10-30 23:29:14 [SEVERE]    at java.util.ArrayList.get(Unknown Source)
2011-10-30 23:29:14 [SEVERE]    at com.iCo6.util.Common.formatted(Common.java:125)
2011-10-30 23:29:14 [SEVERE]    at com.iCo6.iConomy.format(iConomy.java:468)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.resources.register.payment.methods.iCo6.format(iCo6.java:44)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.economy.EconomyManager.format(EconomyManager.java:62)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.economy.EconomyManager.format(EconomyManager.java:57)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.utils.MessageUtils.getNoMoneyMessage(MessageUtils.java:80)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:221)
2011-10-30 23:29:14 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-10-30 23:29:14 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2011-10-30 23:29:14 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2011-10-30 23:29:14 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
2011-10-30 23:29:14 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
2011-10-30 23:29:14 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2011-10-30 23:29:14 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-10-30 23:29:14 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:355)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-10-30 23:29:14 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by fsmythe** [comment]
I have 

Essentials, essentialsspawn, MobBounty, WorldEdit, WorldGuard, Citizens, NoCheat

**Comment by fsmythe** [comment]
running a version higher than the required. Sorry, my bad.
