### ISSUE TITLE
ERROR when creating a new npc

### ISSUE THREAD

**Issue by RebDog75** [CitizensDev/Citizens#368]
Hello guys i'm getting these errors when i make a new citizen

18:01:28 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:439)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
18:01:28 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V
18:01:28 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
18:01:28 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
18:01:28 [SEVERE]   at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)
18:01:28 [SEVERE]   at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
18:01:28 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:01:28 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
18:01:28 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
18:01:28 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:597)
18:01:28 [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)
18:01:28 [SEVERE]   at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)
18:01:28 [SEVERE]   at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
18:01:28 [SEVERE]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:39)
18:01:28 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
18:01:28 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:353)
18:01:28 [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
18:01:28 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
18:01:28 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
18:01:28 [SEVERE]   at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
18:01:28 [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
18:01:28 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
18:01:28 [SEVERE]   at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
18:01:28 [SEVERE]   at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
18:01:28 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
18:01:28 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

> and this opens on my screen:

"please report this error: [see console]
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.<init>(Lnet/minecraft/server/WorldServer;)V"

**Comment by Witchlight** [comment]
im having the smae errors exactly ...... a response would be much appreciated.

**Comment by RebDog75** [comment]
i finally found what was wrong with it, the bukkit build is outdated, you should update your bukkit build to the latest recommended build.
