### ISSUE TITLE
Pathfinding not working

### ISSUE THREAD

**Issue by Chemox** [CitizensDev/Citizens#373]
Pathfinding doesn't work...
Due to this guards also don't react.
And other npc's won't walk around.
It gives this error in log:

<pre><code>
2011-11-06 23:34:56 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchFieldError: aQ
    at net.citizensnpcs.resources.npclib.PathNPC.getYawDifference(PathNPC.java:159)
    at net.citizensnpcs.resources.npclib.PathNPC.handleMove(PathNPC.java:79)
    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:62)
    at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
    at net.citizensnpcs.TickTask.run(TickTask.java:32)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:477)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:409)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:454)
</code></pre>

I run this plugin on Craftbukkit version git-Bukkit-0.0.0-1135-gff80f66-b6jnks
No other plugins are installed.

Thanks in advance.

**Comment by fullwall** [comment]
Your CraftBukkit version needs to be at least #1240.

**Comment by Chemox** [comment]
Ah I see...
Why did they based the 1.9.5 pre on older versions of bukkit -.-
