### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by liquidox** [CitizensDev/Citizens#374]
Build #312 (Nov 7, 2011 1:09:20 PM) 

08:13:05 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchFieldError: profiles
        at net.citizensnpcs.blacksmiths.BlacksmithProperties.isEnabled(BlacksmithProperties.java:50)
        at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:44)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:170)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:293)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by liquidox** [comment]
And related perhaps:

08:37:08 [SEVERE] java.lang.NoSuchFieldError: profiles
08:37:08 [SEVERE]       at net.citizensnpcs.blacksmiths.BlacksmithProperties.isEnabled(BlacksmithProperties.java:50)
08:37:08 [SEVERE]       at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:44)
08:37:08 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:170)
08:37:08 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
08:37:08 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
08:37:08 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:37:08 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
08:37:08 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:37:08 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:601)
08:37:08 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:531)
08:37:08 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:408)
08:37:08 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)
08:37:08 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
08:37:08 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
08:37:08 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:361)
08:37:08 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757)
08:37:08 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722)
08:37:08 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715)
08:37:08 [SEVERE]       at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
08:37:08 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
08:37:08 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
08:37:08 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
08:37:08 [SEVERE]       at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
08:37:08 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
08:37:08 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by liquidox** [comment]
Update Blacksmith.jar, oops <_<
