### ISSUE TITLE
Citizens dependency not working

### ISSUE THREAD

**Issue by yottabyte** [CitizensDev/Citizens#387]
``` java
00:47:27 [SEVERE] Could not load 'plugins\Actinidia.jar' in folder 'plugins': Ci
tizens
org.bukkit.plugin.UnknownDependencyException: Citizens
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:135)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:215)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:136)
        at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:411)
        at org.bukkit.Bukkit.reload(Bukkit.java:182)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
22)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:16
3)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:3
55)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:3
51)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:506)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:485)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
```

This was also happening with the CitizenSpout plugin http://dev.bukkit.org/server-mods/citizenspout/tickets/4-error-in-console-and-plugin-didnt-works/

Pretty severe error, not sure if it is because of Bukkit or Citizens.

**Comment by fullwall** [comment]
Have you tried using softdepend: ?

**Comment by yottabyte** [comment]
Indeed I have.

**Comment by spydercanopus** [comment]
Citizens without skins isn't much fun.  Is Citizens going to be updated to support that?  Or perhaps there is a workaround..?

**Comment by yottabyte** [comment]
I managed to work around it. Not sure if this bug is still there though
