### ISSUE TITLE
Citizens build 318 fail loading quest and crash server after 1st run

### ISSUE THREAD

**Issue by Mykekeul35** [CitizensDev/Citizens#392]
Hello !

First, the configuration of my personal server.

Craftbukkit build 1416
Citizens build 318

I've this error while launchin my server

INFO] Done (0,210s)! For help, type "help" or "?"
2011-11-15 21:19:06 [WARNING] Task of 'Citizens' generated an exception
java.lang.IllegalArgumentException: Delay cannot be less than 0
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:191)
    at net.citizensnpcs.resources.npclib.NPCSpawner.delayedRemove(NPCSpawner.java:58)
    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:67)
    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:345)
    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:170)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:294)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

And after, all my plugins fails... Example : 

2011-11-15 21:19:06 [WARNING] Task of 'NoLagg' generated an exception
java.lang.IllegalArgumentException: Delay cannot be less than 0
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:191)
    at net.citizensnpcs.resources.npclib.NPCSpawner.delayedRemove(NPCSpawner.java:58)
    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:67)
    at org.bukkit.craftbukkit.CraftWorld.getEntities(CraftWorld.java:518)
    at com.bergerkiller.bukkit.nolagg.StackFormer.update(StackFormer.java:120)
    at com.bergerkiller.bukkit.nolagg.NoLagg$2.run(NoLagg.java:143)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-11-15 21:19:06 [SEVERE] java.lang.IllegalArgumentException: Delay cannot be less than 0
2011-11-15 21:19:06 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206)
2011-11-15 21:19:06 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:191)
2011-11-15 21:19:06 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.delayedRemove(NPCSpawner.java:58)
2011-11-15 21:19:06 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:67)
2011-11-15 21:19:06 [SEVERE]    at org.bukkit.craftbukkit.CraftWorld.getEntities(CraftWorld.java:518)
2011-11-15 21:19:06 [SEVERE]    at org.CaiusTSM.ItemScanner.EntityScanner.run(EntityScanner.java:23)
2011-11-15 21:19:06 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-11-15 21:19:06 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
2011-11-15 21:19:06 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-11-15 21:19:06 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-11-15 21:19:08 [SEVERE] java.lang.IllegalArgumentException: Delay cannot be less than 0
2011-11-15 21:19:08 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206)
2011-11-15 21:19:08 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:191)
2011-11-15 21:19:08 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.delayedRemove(NPCSpawner.java:58)
2011-11-15 21:19:08 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:67)
2011-11-15 21:19:08 [SEVERE]    at org.bukkit.craftbukkit.CraftWorld.getEntities(CraftWorld.java:518)
2011-11-15 21:19:08 [SEVERE]    at org.CaiusTSM.ItemScanner.EntityScanner.run(EntityScanner.java:23)
2011-11-15 21:19:08 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-11-15 21:19:08 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
2011-11-15 21:19:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
2011-11-15 21:19:08 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

etc .....

But with Citizens build 317, no bug.

[INFO] Done (0,206s)! For help, type "help" or "?"
2011-11-15 21:25:00 [INFO] [Citizens] Loaded 49 NPCs.
2011-11-15 21:25:00 [INFO] [Citizens] Loaded 2 quests.
2011-11-15 21:25:38 [INFO]

 I'm not a dev but i think Citizens build 318 fail loading quests.

Sorry for my very bad english... i'm french...

**Comment by fullwall** [comment]
Sorry, fixed in #319.

**Comment by Mykekeul35** [comment]
No problem !  Build 319 work fine !
Thx a lot !
