### ISSUE TITLE
java.util.zip.ZipException

### ISSUE THREAD

**Issue by daufinsyd** [CitizensDev/Citizens#410]
13:44:32 [SEVERE] Could not load 'plugins/Citizens.jar' in folder 'plugins': 
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:131)
    at java.util.jar.JarFile.<init>(JarFile.java:150)
    at java.util.jar.JarFile.<init>(JarFile.java:114)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:62)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:215)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:141)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:420)
    at org.bukkit.Bukkit.reload(Bukkit.java:186)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:364)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:360)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:553)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:530)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

 Can you help me please ?

**Comment by IDragonfire** [comment]
Have you redownload the jar File?

**Comment by daufinsyd** [comment]
yes i redownloaded it 3 times

**Comment by IDragonfire** [comment]
Ok, where did you download it?

**Comment by daufinsyd** [comment]
here http://citizensnpcs.net/

**Comment by IDragonfire** [comment]
These site doesn't work ...
Use: http://dev.bukkit.org/server-mods/citizens/

**Comment by daufinsyd** [comment]
i redownloaded it here https://github.com/CitizensDev/Citizens/downloads as tar.gz and it works !
thank you

**Comment by IDragonfire** [comment]
That is a devlopment build (unstable) ...
If you want a stable build use:
http://dev.bukkit.org/server-mods/citizens/files/7-1-1-2/
(press Download)
Here a overview:
http://dev.bukkit.org/server-mods/citizens/files/

Why did you closed and reopened the issue?

**Comment by daufinsyd** [comment]
But when i write /toggle guard or trader ..... 
the console returned me invalid npc type ?

**Comment by IDragonfire** [comment]
Look into "plugins\Citizens\types"
There must be some jars,
like "Guard.jar".
The console must print:
"[Citizens] NPC types loaded: blacksmith, guard, ..."

**Comment by daufinsyd** [comment]
It works perfectly. Thank you  a lot !

**Comment by IDragonfire** [comment]
Dont forget to close these issue ;)
