### ISSUE TITLE
Task of 'Citizens' generated an exception

### ISSUE THREAD

**Issue by JoneKone** [CitizensDev/Citizens#422]
23:27:59 [WARNING] Task of 'Citizens' generated an exception
java.lang.IllegalAccessError: tried to access field net.minecraft.server.EntityLiving.aQ from class net.citizensnpcs.resources.npclib.PathNPC
        at net.citizensnpcs.resources.npclib.PathNPC.getYawDifference(PathNPC.java:159)
        at net.citizensnpcs.resources.npclib.PathNPC.handleMove(PathNPC.java:79)
        at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:62)
        at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
        at net.citizensnpcs.TickTask.run(TickTask.java:32)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by Mykekeul35** [comment]
Update to the lastest citizens build : http://ci.citizensnpcs.net/
