### ISSUE TITLE
Always prints "The command was not recognized. See /npc help for a list of commands."

### ISSUE THREAD

**Issue by DeathCamel57** [CitizensDev/Citizens#425]
When I join the server, my previously created npcs are gone. Here is a copy of the log file:
<code>
17:37:20 [INFO] [Citizens] NPC types loaded: wizard, quester, blacksmith, healer, trader, guard
17:37:21 [SEVERE] Error occurred while enabling Citizens v1.1.1 (Is it up to date?): null
java.lang.ExceptionInInitializerError
    at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:32)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:88)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:183)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:176)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:159)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:337)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:161)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: while parsing a flow mapping
 in "<reader>", line 1, column 1:
    {
    ^
expected ',' or '}', but got Value
 in "<reader>", line 3, column 10:
        texts:
             ^

```
at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowMappingKey.produce(ParserImpl.java:735)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
at org.bukkit.util.config.Configuration.load(Configuration.java:89)
at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:31)
at net.citizensnpcs.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:25)
at net.citizensnpcs.questers.data.QuestProperties.<clinit>(QuestProperties.java:9)
... 12 more
```

17:37:21 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
17:37:22 [INFO] [Citizens] 
17:37:22 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
17:37:22 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
</code>
after about 5 minutes of being online (without npcs) it crashes.
how would I go about fixing this?

**Comment by fullwall** [comment]
You have an invalid quests.yml.
