### ISSUE TITLE
Server crash when killing guard with bow+arrow

### ISSUE THREAD

**Issue by CountVonCraft** [CitizensDev/Citizens#426]
When a guard is killed by someone with a bow and arrow it returns this error.

(This has been tested on both my live server, and test server just running GM and Citizens)

2011-11-28 23:31:06 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 225, Size: 225
2011-11-28 23:31:06 [SEVERE]    at java.util.ArrayList.rangeCheck(ArrayList.java:571)
2011-11-28 23:31:06 [SEVERE]    at java.util.ArrayList.remove(ArrayList.java:412)
2011-11-28 23:31:06 [SEVERE]    at net.minecraft.server.World.tickEntities(World.java:1151)
2011-11-28 23:31:06 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:507)
2011-11-28 23:31:06 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
2011-11-28 23:31:06 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-11-28 23:31:06 [SEVERE] Unexpected exception
java.lang.IndexOutOfBoundsException: Index: 225, Size: 225
    at java.util.ArrayList.rangeCheck(ArrayList.java:571)
    at java.util.ArrayList.remove(ArrayList.java:412)
    at net.minecraft.server.World.tickEntities(World.java:1151)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:507)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by Sdrubs** [comment]
I have the same problem.

**Comment by nexitem** [comment]
Yep same problem here!

**Comment by IDragonfire** [comment]
is that the whole log?

**Comment by nexitem** [comment]
just test it out yourself, kill a npc creature with an arrow, and he will cry. ( arrow in the knee? anyone? )

**Comment by IDragonfire** [comment]
Arm have no pc xd

**Comment by Coloniacraft** [comment]
Me too :P Sucks ass. Now I have to tell the users not to kill NPC's with arrows....or ban the items. ROFL

**Comment by IDragonfire** [comment]
K
I test it today

**Comment by IDragonfire** [comment]
Confirm bug,
I search for the reason^^

**Comment by IDragonfire** [comment]
Ok.
the reason for the error is in NPCSpawner.despawnNPC ...
Bukkit throw a exception if Citizens try to remove the NPC :-(
If i remove "getWorldServer(npc.getWorld()).removeEntity(npc.getHandle())" I get no exceptions ...

**Comment by IDragonfire** [comment]
Can you make a backup and test these jar?

https://github.com/downloads/IDragonfire/Citizens/Citizens.jar

Changes:
https://github.com/IDragonfire/Citizens/commit/82add5ef47ce31ffe9f699a19c5f11204740f8d5
(sry for formatting)

**Comment by IDragonfire** [comment]
The reason:

Guard.onDamage is called twice if you shot with an arrow ..
with sword it is called only one time ...

http://forums.bukkit.org/threads/differentiating-between-projectile-and-normal-damage.43893/

**Comment by nexitem** [comment]
Thank you very much dragonfire, this fixed it. :)

**Comment by ghost** [comment]
I'm having this same issue, but with the dev builds of Citizens that work with 1.1

**Comment by SupaYoshi** [comment]
Same here! Bukkit dev 1714 till 1798 - here
https://github.com/CitizensDev/Citizens/issues/660

**Comment by ghost** [comment]
I'd love to just recompile the lastest build of citizens with the same hotfix that IDragonfire set, but I keep getting classpath errors on runtime for the compiled JARs, so I'm at a loss

**Comment by IDragonfire** [comment]
that was a hotfix for 1.0 only ... I though the citizens devs fix these in newer versions :(

**Comment by ghost** [comment]
I don't think they even merged yours in because there were still a few other issues that had to be ironed out. Still, the source I was grabbing had some issues, so I talked to Fullwall and he coded up a fix for it fast. I will say this much, out of all the devs I've dealt with, he is by far the nicest and most patient when it comes to working with others to sort out issues. Also, there's a new release today for Citizens, and I am fairly certain the fix for this is included now.
