### ISSUE TITLE
For some reason, Citizens spams the console with an error.

### ISSUE THREAD

**Issue by DeathCamel57** [CitizensDev/Citizens#427]
The error is:
<code>
06:48:36 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
06:48:36 [INFO] [Citizens] 
06:48:36 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
06:48:36 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
06:48:36 [SEVERE] Could not pass event PLAYER_MOVE to Citizens
java.util.NoSuchElementException
    at java.util.ArrayDeque.removeFirst(ArrayDeque.java:278)
    at java.util.ArrayDeque.pop(ArrayDeque.java:507)
    at net.citizensnpcs.questers.quests.Objectives$ObjectiveCycler.cycle(Objectives.java:49)
    at net.citizensnpcs.questers.quests.progress.QuestProgress.next(QuestProgress.java:37)
    at net.citizensnpcs.questers.quests.progress.QuestProgress.cycle(QuestProgress.java:29)
    at net.citizensnpcs.questers.quests.progress.QuestProgress.setStep(QuestProgress.java:57)
    at net.citizensnpcs.questers.data.PlayerProfile.load(PlayerProfile.java:191)
    at net.citizensnpcs.questers.data.PlayerProfile.<init>(PlayerProfile.java:30)
    at net.citizensnpcs.questers.data.PlayerProfile.getProfile(PlayerProfile.java:40)
    at net.citizensnpcs.questers.data.PlayerProfile.getProfile(PlayerProfile.java:50)
    at net.citizensnpcs.questers.QuestManager.getProfile(QuestManager.java:90)
    at net.citizensnpcs.questers.QuestManager.hasQuest(QuestManager.java:98)
    at net.citizensnpcs.questers.QuestManager.incrementQuest(QuestManager.java:106)
    at net.citizensnpcs.questers.listeners.QuesterPlayerListen.onPlayerMove(QuesterPlayerListen.java:32)
    at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:302)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:180)
    at net.minecraft.server.Packet10Flying.a(SourceFile:126)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
</code>
this gets printed about once a second. What does it mean and what would I do to get my citizens to be viewable again?

**Comment by fullwall** [comment]
What version are you using?

**Comment by ghost** [comment]
i have this problem to. im using citizens devBuild-327 and craftbukkit 1597
