### ISSUE TITLE
Task of 'Citizens' generated an exception

### ISSUE THREAD

**Issue by minecrafterzeroone** [CitizensDev/Citizens#431]
2011-12-01 21:32:39 [INFO] Starting minecraft server version 1.0.1
2011-12-01 21:32:39 [INFO] Loading properties
2011-12-01 21:32:39 [INFO] Starting Minecraft server on *:25565
2011-12-01 21:32:39 [INFO] This server is running Craftbukkit version git-Bukkit-1.8.1-R4-72-ge9ecf57-b1547jnks (MC: 1.0.1) (Implementing API version 1.0.0-R1-SNAPSHOT)
2011-12-01 21:32:39 [INFO] [Waypoint] Initialising configurations.
2011-12-01 21:32:39 [INFO] ControllerBlock: 1.18 by Hell_Fire
2011-12-01 21:32:40 [INFO] ControllerBlock: Using IRON_BLOCK (42) as ControllerBlock, loaded 0 disallowed types from config
2011-12-01 21:32:40 [INFO] [Register] Preferred method [null] not found, using first found.
2011-12-01 21:32:40 [INFO] [Register] version 1.5 is enabled.
2011-12-01 21:32:40 [INFO] [Pail] Initializing...
2011-12-01 21:32:40 [INFO] [Pail] Setting up themes...
2011-12-01 21:32:40 [INFO] [Pail] Loading interface...
2011-12-01 21:32:40 [INFO] [Pail] Registering events...
2011-12-01 21:32:40 [INFO] [Pail] Setting up window...
2011-12-01 21:32:40 [INFO] [Pail] Pail 0.7.5 Enabled
2011-12-01 21:32:40 [INFO] [Safe Creeper] Safe Creeper V0.3.2 Enabled
2011-12-01 21:32:40 [INFO] Preparing level "World One"
2011-12-01 21:32:40 [INFO] Default game type: 0
2011-12-01 21:32:40 [INFO] Preparing start region for level 0 (Seed: 8738280163328226804)
2011-12-01 21:32:41 [INFO] Preparing start region for level 1 (Seed: 8738280163328226804)
2011-12-01 21:32:41 [INFO] Preparing spawn area: 48%
2011-12-01 21:32:41 [INFO] Preparing start region for level 2 (Seed: 2844915138274702363)
2011-12-01 21:32:42 [INFO] AnyReg v0.5 by DiddiZ (fixed by FlingeR) enabled
2011-12-01 21:32:42 [INFO] ClayGen version 1.5.2 is enabled!
2011-12-01 21:32:42 [INFO] ControllerBlock: Enabling full redstone check
2011-12-01 21:32:42 [INFO] ControllerBlock: Events registered
2011-12-01 21:32:42 [INFO] CraftBukkitUpToDate version 2.7.1 is enabled!
2011-12-01 21:32:42 [INFO] [DwarfForge] Restored 3 active Forges.
2011-12-01 21:32:42 [INFO] [DwarfForge] Version 1.7.1 enabled.
2011-12-01 21:32:42 [INFO] EasySwitch v1.0 by lionking23 now enabled.
2011-12-01 21:32:42 [INFO] [iConomy - Celty] Enabled (15 ms)
2011-12-01 21:32:42 [INFO] [lib24time] v1.1 enabled
2011-12-01 21:32:42 [INFO] [LightSensor](By Rahazan) - v0.1 loaded.
2011-12-01 21:32:42 [INFO] [MagicTorches] Initializing MagicTorches.
2011-12-01 21:32:42 [INFO] [MagicTorches] MiniDB found or created. Loading DB.
2011-12-01 21:32:42 [INFO] [MagicTorches] Plugin initialized.
2011-12-01 21:32:42 [INFO] [MoneyDrop] Startup complete.
2011-12-01 21:32:42 [INFO] PailPlus v0.2 beta enabled
2011-12-01 21:32:42 [INFO] SecretSwitch 1.2 Enabled.
2011-12-01 21:32:42 [INFO] [SecretSwitch] Permission plugin not detected, defaulting to everyone.
2011-12-01 21:32:42 [INFO] [StreetLamps] MANUALLY enabled
2011-12-01 21:32:42 [INFO] [StreetLamps] POWER enabled
2011-12-01 21:32:42 [INFO] [StreetLamps] DAYTIME enabled
2011-12-01 21:32:42 [INFO] [StreetLamps] WEATHER enabled
2011-12-01 21:32:42 [INFO] [StreetLamps] CLUSTER enabled
2011-12-01 21:32:43 [INFO] [StreetLamps] loaded 2/2 pole for World One
2011-12-01 21:32:43 [INFO] [StreetLamps] loaded 1/1 pendant for World One
2011-12-01 21:32:43 [INFO] [StreetLamps] loaded 0 LampController for World One
2011-12-01 21:32:43 [INFO] [StreetLamps] loaded 0 LampController for World One_nether
2011-12-01 21:32:43 [INFO] [StreetLamps] loaded 0 LampController for World One_the_end
2011-12-01 21:32:43 [INFO] StreetLamps 0.8.2 is enabled
2011-12-01 21:32:43 [INFO] TreeAssist 2.0 Enabled
2011-12-01 21:32:43 [INFO] [Waypoint] Reading configurations.
2011-12-01 21:32:43 [INFO] [Waypoint] Configuration succesfully loaded.
2011-12-01 21:32:43 [INFO] [Waypoint] No Permissions plugin detected. Using OP
2011-12-01 21:32:43 [INFO] [Waypoint] Enabled version 1.6.0
2011-12-01 21:32:43 [INFO] [Waypoint] Saved all configurations.
2011-12-01 21:32:43 [INFO] [Waypoint] Checking for updates..
2011-12-01 21:32:46 [INFO] [Waypoint] Error while checking for updates. (It could be a dev build.)
2011-12-01 21:32:46 [INFO] [Waypoint] Warps: loaded permission groups: Default, Mod, Admin
2011-12-01 21:32:46 [INFO] [Waypoint] No worlds to be loaded.
2011-12-01 21:32:46 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
2011-12-01 21:32:47 [INFO] CButD: CraftBukkit is Outdate, try to download new version
2011-12-01 21:32:47 [INFO] [Citizens] version [1.1.2] loaded.
2011-12-01 21:32:47 [INFO] [Citizens] Economy plugin found (iConomy v6)
2011-12-01 21:32:47 [INFO] [dynmap] Using Bukkit Permissions (superperms) for access control
2011-12-01 21:32:47 [INFO] [dynmap] Loaded 12 shaders.
2011-12-01 21:32:47 [INFO] [dynmap] Loaded 56 perspectives.
2011-12-01 21:32:47 [INFO] [dynmap] Loaded 7 lightings.
2011-12-01 21:32:47 [INFO] [dynmap] Loaded 2 maps of world 'World One'.
2011-12-01 21:32:47 [INFO] [dynmap] Loaded 2 maps of world 'World One_nether'.
2011-12-01 21:32:47 [INFO] [dynmap] Loaded 2 maps of world 'World One_the_end'.
2011-12-01 21:32:47 [INFO] [dynmap] Dynmap WebServer started on null:25566
2011-12-01 21:32:47 [INFO] [dynmap] version 0.25.1-624 is enabled
2011-12-01 21:32:47 [INFO] [Register] Payment method found (iConomy version: 6)
2011-12-01 21:32:47 [INFO] Server permissions file permissions.yml is empty, ignoring it
2011-12-01 21:32:47 [INFO] Done (0.758s)! For help, type "help" or "?"
2011-12-01 21:32:48 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/Packet17
    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:28)
    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more
2011-12-01 21:32:48 [INFO] ControllerBlock: Loaded v1 data - 0 ControllerBlocks loaded
2011-12-01 21:32:52 [INFO] The automatic update-Check only work every 6 hours, the last check was 113 minutes ago.
2011-12-01 21:32:53 [INFO] [MoneyDrop] Connected to Register. Item pickups functional.

been testing the new dev bukkit and this error came up likly needs to be fixed before the new release

**Comment by ghost** [comment]
i have this same problem.

**Comment by AbsoluteMonkey** [comment]
And I have this same problem as well.

**Comment by IDragonfire** [comment]
NoClassDefFoundError is a hind for a version conflict ...
can you post your Citizens and Bukkit Version?

**Comment by ghost** [comment]
my citezens build is: 1.1.2 
and my bukkit build is: 1550
my error is exactly the same. so i have a feeling minecrafterzeroone has same citezens. but the bukkit build is:1547 acording to this log.

**Comment by minecrafterzeroone** [comment]
it was clearly in the log was it not

**Comment by minecrafterzeroone** [comment]
b1547

-b1547jnks jenkins deva build im testing citizens with it and it broke out of nowhere before this change it was fine

**Comment by minecrafterzeroone** [comment]
changing to 1550 to contuinue testing my plugins

**Comment by minecrafterzeroone** [comment]
same error on Cbukkit 1550dev

2011-12-03 18:15:47 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/Packet17
    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:28)
    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more

**Comment by minecrafterzeroone** [comment]
current citizens build 1.1. 2
i know dev versions are not supported and to ask for the citizens team to keep up with each dev release would be asking for way to much i am just reporting the error to help maybe point them twords an issue so thier next release might go smoothly its easiest to catch these things early so they can compair what changed in bukkit and what they need to change in citizens

**Comment by Ares513** [comment]
It works fine for me at the dev build, albeit a few bugs

ci.citizensnpcs,.net

**Comment by ghost** [comment]
thank you. starts up without an error now.

**Comment by minecrafterzeroone** [comment]
bukkit build 1557 citizens Build #325

2011-12-04 22:06:54 [SEVERE] Error occurred while enabling Citizens v1.1.2 (Is it up to date?): net/citizensnpcs/api/event/citizens/CitizensEvent
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/citizens/CitizensEvent
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.citizensnpcs.questers.QuesterType.getCommands(QuesterType.java:27)
    at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:49)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:304)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:184)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:167)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:337)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:161)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.citizens.CitizensEvent
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more

**Comment by Mykekeul35** [comment]
Craftbukkit 1561 with citizens dev build 325 working but few bug. Are you sure to have the Citizens dev build 325 minecrafterzeroone ?

**Comment by minecrafterzeroone** [comment]
i do now and it does work it took downloading the expermental version to get it to work no problems found yet

**Comment by minecrafterzeroone** [comment]
solved in new build 325
