### ISSUE TITLE
Won't let me create Npc's

### ISSUE THREAD

**Issue by flamemaaster3457** [CitizensDev/Citizens#433]
09:46 PM [SEVERE] java.lang.NullPointerException 
09:46 PM [SEVERE] at net.minecraft.server.NetworkListenThread.a(SourceFile:63) 
09:46 PM [SEVERE] at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:146) 
09:46 PM [SEVERE] at net.minecraft.server.Packet254GetInfo.a(SourceFile:16) 
09:46 PM [SEVERE] at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
09:46 PM [SEVERE] at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:46) 
09:46 PM [SEVERE] at net.minecraft.server.NetworkListenThread.a(SourceFile:94) 
09:46 PM [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516) 
09:46 PM [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414) 
09:46 PM [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:457) 
09:46 PM [INFO] /192.168.1.106:54920 lost connection 
09:46 PM [INFO] /192.168.1.106:54929 lost connection 
09:46 PM [INFO] flamemaster3457 [/192.168.1.106:54932] logged in with entity id 476 at ([World] 489.18988478379487, 87.0, -955.4051012016203) 
09:46 PM [WARNING] Can't keep up! Did the system time change, or is the server overloaded? 
09:46 PM [WARNING] Can't keep up! Did the system time change, or is the server overloaded? 
09:46 PM [WARNING] Can't keep up! Did the system time change, or is the server overloaded? 
09:46 PM [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/Packet17 
09:46 PM [SEVERE] at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:24) 
09:46 PM [SEVERE] at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15) 
09:46 PM [SEVERE] at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:29) 
09:46 PM [SEVERE] at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162) 
09:46 PM [SEVERE] at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:191) 
09:46 PM [SEVERE] at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:223) 
09:46 PM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
09:46 PM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
09:46 PM [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
09:46 PM [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source) 
09:46 PM [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:517) 
09:46 PM [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:405) 
09:46 PM [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers... 
09:46 PM [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information. 
09:46 PM [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:200) 
09:46 PM [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40) 
09:46 PM [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) 
09:46 PM [SEVERE] at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:370) 
09:46 PM [SEVERE] at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756) 
09:46 PM [SEVERE] at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721) 
09:46 PM [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714) 
09:46 PM [SEVERE] at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33) 
09:46 PM [SEVERE] at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
09:46 PM [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92) 
09:46 PM [SEVERE] at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
09:46 PM [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516) 
09:46 PM [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414) 
09:46 PM [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:457) 
09:46 PM [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17 
09:46 PM [SEVERE] at java.net.URLClassLoader$1.run(Unknown Source) 
09:46 PM [SEVERE] at java.security.AccessController.doPrivileged(Native Method) 
09:46 PM [SEVERE] at java.net.URLClassLoader.findClass(Unknown Source) 
09:46 PM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36) 
09:46 PM [SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24) 

Server is running newest bukkit update, and newest Citizen's update. Citizen's was working, but for some reason now it isnt. Please help, thanks.
09:46 PM [SEVERE] at java.lang.ClassLoader.loadClass(Unknown Source) 
09:46 PM [SEVERE] ... 26 more

**Comment by Ashtheking** [comment]
Pretty sure the latest craftbukkit renamed Packet17 to Packet17EntityLocationAction

**Comment by JohnSVK** [comment]
I have the same issue now. Anybody know how to fix this or just need to wait for new version?

**Comment by Ares513** [comment]
Dev version,  works fine, albeit more than a few bugs
ci.citizensnpcs.net

**Comment by flamemaaster3457** [comment]
I tried that. Same error. It says same java error. Any suggestions? I'm running bukkit #1550 dev build. I'm pretty sure.

**Comment by Mykekeul35** [comment]
i'm running craftbukkit 1561 and citizend dev build 325 and no bug like you. Try to update all your plugins
