### ISSUE TITLE
Citizens won't load

### ISSUE THREAD

**Issue by kosciCZ** [CitizensDev/Citizens#436]
Hi, we are using latest build of Citizens , and latest build of bukkit and we get this error while enabling citizens

2011-12-04 18:02:21 [SEVERE] Error occurred while enabling Citizens v1.1.2 (Is it up to date?): net/citizensnpcs/api/event/citizens/CitizensEvent
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/citizens/CitizensEvent
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at net.citizensnpcs.questers.QuesterType.getCommands(QuesterType.java:27)
    at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:49)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:304)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:182)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:165)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:337)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:161)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.citizens.CitizensEvent
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 38 more

and in game , every time i try to use some command for citizens (like /npc create x) i get Command not recognized, try /npc help , which dont work

**Comment by Mykekeul35** [comment]
Try the lastest dev build of citizens at : http://ci.citizensnpcs.net/
Citizens 1.1.2 isn't compatible with minecraft 1.0.0

**Comment by kosciCZ** [comment]
Whoa, this is a blast from the past, closing this, as this surely isn't relevant anymore.
