### ISSUE TITLE
Task of 'Citizens' generated an exception

### ISSUE THREAD

**Issue by tickleman** [CitizensDev/Citizens#443]
When I start my server, Citizens can't enable (I can't see any of my NPCs).
Craftbukkit #1560
May be a craftbukkit temporary limitation, but in case of...:

13:41:47 [WARNING] Task of 'Citizens' generated an exception
java.lang.SecurityException: sealing violation: package net.minecraft.server is sealed
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:244)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:221)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:32)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:334)
        at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:28)
        at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15)
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:290)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:137)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by Mykekeul35** [comment]
Citizens 1.1.2 isn't compatible with minecraft 1.0. Try the lastest build at http://ci.citizensnpcs.net/ . No "Task of 'Citizens' generated an exception" but everything isn't working.

**Comment by Destreyf** [comment]
@tickleman:

If i may intrude, my recommendation is to use build 325 or 324, i have had success getting everything working you can find it by going here:

http://jenkins.citizensnpcs.net:81/job/Citizens/325/artifact/bin/
http://jenkins.citizensnpcs.net:81/job/Citizens/324/artifact/bin/

If you look, it will have some files listed, you'll have to download those, you can use the "(all files in zip)" link on that page to download, if you then take the files INSIDE the bin directory, (Citizens.jar and the types/ folder) and upload them into the plugins directory, it should work with existing configurations.
