### ISSUE TITLE
Error using /npc create

### ISSUE THREAD

**Issue by mmeyer724** [CitizensDev/Citizens#450]
Here's an image of what happens in-game: http://gyazo.com/e34aa8c8298c349fdf34c8eb1ecc6bfd.png

All I typed was "/npc create Helper"

I am running craftbukkit build #1566 (upgrading that soon).

Here's a list a plugins I have installed: http://gyazo.com/b78a5f21104e6cf8c6c36d5764197d98.png

Here's the console report...
2011-12-09 13:27:47 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/Packet17

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:28)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)

2011-12-09 13:27:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2011-12-09 13:27:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)

2011-12-09 13:27:47 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)

2011-12-09 13:27:47 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

2011-12-09 13:27:47 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)

2011-12-09 13:27:47 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:374)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:521)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)

2011-12-09 13:27:47 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-09 13:27:47 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17

2011-12-09 13:27:47 [SEVERE]    at java.net.URLClassLoader$1.run(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at java.net.URLClassLoader$1.run(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at java.security.AccessController.doPrivileged(Native Method)

2011-12-09 13:27:47 [SEVERE]    at java.net.URLClassLoader.findClass(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)

2011-12-09 13:27:47 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)

2011-12-09 13:27:47 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)

2011-12-09 13:27:47 [SEVERE]    ... 26 more

**Comment by Mykekeul35** [comment]
Have you got the lastest build af citizens ? http://ci.citizensnpcs.net/

**Comment by mmeyer724** [comment]
Ok I just updated to the newest build.

Now every time I try to use a command it says...http://gyazo.com/26bace2faec128a0e8334909f91eac1c

Pretty much it doesn't recognize any commands for me.

I tried /npc, /npc create Test, /npc help, nothing works.

**Comment by fullwall** [comment]
Update to 1.1.3.
