### ISSUE TITLE
Guard Issues

### ISSUE THREAD

**Issue by Sdrubs** [CitizensDev/Citizens#452]
Well,the guards aren't working well
1- I've already ''deleted'' all plugins to test only citizens - Doesn't work
2- other npc commands doesn't work after setting up bouncer: Ex. /npc talkclose - /npc lookat
3:
/npc create [name]
/toggle guard
/guard bouncer
/guard addflag 1 -m spider
/guard addflag 2 -m zombie
/guard addflag 3 -m skeleton

But the guard don't move,don't look anyone,don't even talk with players,
what's the matter?
btw,there is a new error:
00:30:22 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.f(Lnet/mi
necraft/server/Entity;)Z
        at net.citizensnpcs.resources.npclib.PathNPC.isInSight(PathNPC.java:252)

```
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:1
```

09)
        at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:57)
        at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
        at net.citizensnpcs.TickTask.run(TickTask.java:32)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
00:30:22 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.f(Lnet/mi
necraft/server/Entity;)Z
        at net.citizensnpcs.resources.npclib.PathNPC.isInSight(PathNPC.java:252)

```
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:1
```

09)
        at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:57)
        at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
        at net.citizensnpcs.TickTask.run(TickTask.java:32)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
00:30:22 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.f(Lnet/mi
necraft/server/Entity;)Z
        at net.citizensnpcs.resources.npclib.PathNPC.isInSight(PathNPC.java:252)

```
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:1
```

09)
        at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:57)
        at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
        at net.citizensnpcs.TickTask.run(TickTask.java:32)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
00:30:22 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.f(Lnet/mi
necraft/server/Entity;)Z
        at net.citizensnpcs.resources.npclib.PathNPC.isInSight(PathNPC.java:252)

```
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:1
```

09)
        at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:57)
        at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:101)
        at net.citizensnpcs.TickTask.run(TickTask.java:32)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
00:30:29 [INFO] The automatic update-Check only work every 6 hours, the last che
ck was 261 minutes ago.

**Comment by Cixxar** [comment]
i dont get these errors BUT i have the same problems getting guards to work
