### ISSUE TITLE
Error on bukkit shut down

### ISSUE THREAD

**Issue by mmeyer724** [CitizensDev/Citizens#454]
I'm getting this error when I shut my server down:

I'm using the newest version of bukkit and citizens.

2011-12-10 09:15:05 [INFO] [Citizens] Report this error ASAP.

2011-12-10 09:15:05 [SEVERE] java.lang.NullPointerException

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Settings.getBoolean(Settings.java:35)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.utils.Web.disableErrorReporting(Web.java:111)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Citizens.onDisable(Citizens.java:152)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:190)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:978)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:296)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:289)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:181)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:370)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-10 09:15:05 [INFO] [Citizens] Report this error ASAP.

2011-12-10 09:15:05 [SEVERE] java.lang.NullPointerException

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Settings.getBoolean(Settings.java:35)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<init>(CreatureNPCType.java:57)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<clinit>(CreatureNPCType.java:23)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.Class.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.System$2.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.getKeyUniverse(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.<init>(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureTask.<clinit>(CreatureTask.java:22)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Citizens.onDisable(Citizens.java:155)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:190)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:978)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:296)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:289)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:181)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:370)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-10 09:15:05 [INFO] [Citizens] Report this error ASAP.

2011-12-10 09:15:05 [SEVERE] java.lang.NullPointerException

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Settings.getInt(Settings.java:45)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<init>(CreatureNPCType.java:58)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<clinit>(CreatureNPCType.java:23)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.Class.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.System$2.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.getKeyUniverse(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.<init>(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureTask.<clinit>(CreatureTask.java:22)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Citizens.onDisable(Citizens.java:155)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:190)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:978)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:296)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:289)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:181)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:370)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-10 09:15:05 [INFO] [Citizens] Report this error ASAP.

2011-12-10 09:15:05 [SEVERE] java.lang.NullPointerException

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Settings.getInt(Settings.java:45)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<init>(CreatureNPCType.java:59)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<clinit>(CreatureNPCType.java:23)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.Class.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.System$2.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.getKeyUniverse(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.<init>(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureTask.<clinit>(CreatureTask.java:22)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Citizens.onDisable(Citizens.java:155)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:190)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:978)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:296)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:289)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:181)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:370)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-10 09:15:05 [INFO] [Citizens] Report this error ASAP.

2011-12-10 09:15:05 [SEVERE] java.lang.NullPointerException

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Settings.getString(Settings.java:55)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<init>(CreatureNPCType.java:60)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<clinit>(CreatureNPCType.java:23)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.Class.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.lang.System$2.getEnumConstantsShared(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.getKeyUniverse(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at java.util.EnumMap.<init>(Unknown Source)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.resources.npclib.creatures.CreatureTask.<clinit>(CreatureTask.java:22)

2011-12-10 09:15:05 [SEVERE]    at net.citizensnpcs.Citizens.onDisable(Citizens.java:155)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:190)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:978)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:296)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:289)

2011-12-10 09:15:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:181)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:370)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)

2011-12-10 09:15:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-10 09:15:05 [INFO] [Citizens] version [devBuild-] disabled.

**Comment by mmeyer724** [comment]
There is also this error:

2011-12-10 09:16:40 [SEVERE] Error occurred while enabling Citizens v1.1.2 (Is it up to date?): net/citizensnpcs/api/event/citizens/CitizensEvent

java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/citizens/CitizensEvent

```
at java.lang.ClassLoader.defineClass1(Native Method)

at java.lang.ClassLoader.defineClass(Unknown Source)

at java.security.SecureClassLoader.defineClass(Unknown Source)

at java.net.URLClassLoader.defineClass(Unknown Source)

at java.net.URLClassLoader.access$100(Unknown Source)

at java.net.URLClassLoader$1.run(Unknown Source)

at java.net.URLClassLoader$1.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at java.net.URLClassLoader.findClass(Unknown Source)

at java.lang.ClassLoader.loadClass(Unknown Source)

at java.net.FactoryURLClassLoader.loadClass(Unknown Source)

at java.lang.ClassLoader.loadClass(Unknown Source)

at java.lang.ClassLoader.defineClass1(Native Method)

at java.lang.ClassLoader.defineClass(Unknown Source)

at java.security.SecureClassLoader.defineClass(Unknown Source)

at java.net.URLClassLoader.defineClass(Unknown Source)

at java.net.URLClassLoader.access$100(Unknown Source)

at java.net.URLClassLoader$1.run(Unknown Source)

at java.net.URLClassLoader$1.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at java.net.URLClassLoader.findClass(Unknown Source)

at java.lang.ClassLoader.loadClass(Unknown Source)

at java.net.FactoryURLClassLoader.loadClass(Unknown Source)

at java.lang.ClassLoader.loadClass(Unknown Source)

at net.citizensnpcs.questers.QuesterType.getCommands(QuesterType.java:27)

at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:49)

at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:304)

at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)

at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:186)

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:169)

at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:342)

at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:329)

at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:165)

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:393)

at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
```

Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.citizens.CitizensEvent

```
at java.net.URLClassLoader$1.run(Unknown Source)

at java.net.URLClassLoader$1.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at java.net.URLClassLoader.findClass(Unknown Source)

at java.lang.ClassLoader.loadClass(Unknown Source)

at java.net.FactoryURLClassLoader.loadClass(Unknown Source)

at java.lang.ClassLoader.loadClass(Unknown Source)

... 38 more
```

**Comment by fullwall** [comment]
Update type JARs and remove quotes from your config.
