### ISSUE TITLE
error when creating npc

### ISSUE THREAD

**Issue by Deimos161** [CitizensDev/Citizens#463]
2011-12-12 18:32:09 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/Packet17

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:28)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:15)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:31)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:164)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:193)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)

2011-12-12 18:32:09 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2011-12-12 18:32:09 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

2011-12-12 18:32:09 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2011-12-12 18:32:09 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:522)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:406)

2011-12-12 18:32:09 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:202)

2011-12-12 18:32:09 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

2011-12-12 18:32:09 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)

2011-12-12 18:32:09 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:378)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)

2011-12-12 18:32:09 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

2011-12-12 18:32:09 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17

2011-12-12 18:32:09 [SEVERE]    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)

2011-12-12 18:32:09 [SEVERE]    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)

2011-12-12 18:32:09 [SEVERE]    at java.security.AccessController.doPrivileged(Native Method)

2011-12-12 18:32:09 [SEVERE]    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)

2011-12-12 18:32:09 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)

2011-12-12 18:32:09 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)

2011-12-12 18:32:09 [SEVERE]    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)

2011-12-12 18:32:09 [SEVERE]    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)

**Comment by Gilbertamy** [comment]
I have something like this problem too. I cannot create NPCs at all. Please forgive me if I'm not supposed to post it here. Using Craftbukkit 1772 (M.C. 1.1) and BOSEconomy. It charges the amount right but then I get an error.

2012-01-15 19:07:14 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.resources.npclib.CraftNPC.(CraftNPC.java:17)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-01-15 19:07:14 [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-01-15 19:07:14 [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2012-01-15 19:07:14 [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-01-15 19:07:14 [SEVERE] at java.lang.reflect.Method.invoke(Method.java:601)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-01-15 19:07:14 [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2012-01-15 19:07:14 [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-01-15 19:07:14 [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-01-15 19:07:14 [SEVERE] at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:768)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:728)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:721)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:96)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:535)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
2012-01-15 19:07:14 [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Gilbertamy** [comment]
I'm sorry, of course it isn't working, I'm using the dev craftbukkit build. :P sorry
