### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MegMeg7** [CitizensDev/Citizens#465]
## Craftbukkit R1 // Citizens R: 1.1.3 for CB 1.0.0-R1

Hello !

I receive this message when I try to hit a mob generate by Citizens :

2011-12-13 20:26:47 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at net.citizensnpcs.resources.npclib.HumanNPC.getOwner(HumanNPC.java:126)
    at net.citizensnpcs.resources.npclib.NPCManager.faceEntity(NPCManager.java:64)
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:322)
    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:206)
    at net.citizensnpcs.resources.npclib.creatures.CreatureNPC.doTick(CreatureNPC.java:39)
    at net.citizensnpcs.resources.npclib.creatures.EvilCreatureNPC.doTick(EvilCreatureNPC.java:50)
    at net.citizensnpcs.resources.npclib.creatures.CreatureTask$CreatureTick.run(CreatureTask.java:106)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-13 20:26:47 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at net.citizensnpcs.resources.npclib.HumanNPC.getOwner(HumanNPC.java:126)
    at net.citizensnpcs.resources.npclib.NPCManager.faceEntity(NPCManager.java:64)
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:322)
    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:206)
    at net.citizensnpcs.resources.npclib.creatures.CreatureNPC.doTick(CreatureNPC.java:39)
    at net.citizensnpcs.resources.npclib.creatures.EvilCreatureNPC.doTick(EvilCreatureNPC.java:50)
    at net.citizensnpcs.resources.npclib.creatures.CreatureTask$CreatureTick.run(CreatureTask.java:106)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

Thank you !

**Comment by fullwall** [comment]
Fixed in latest dev build.
