### ISSUE TITLE
Basic move quest spams server console and crashes the plugin

### ISSUE THREAD

**Issue by Craigdb** [CitizensDev/Citizens#467]
Unfortunately, I don't currently have a log of the errors that are spamming the console, as follows:
2011-12-14 13:25:27 [SEVERE] Could not pass event PLAYER_MOVE to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.quests.progress.QuestProgress.updateProgress(QuestProgress.java:77)
    at net.citizensnpcs.questers.QuestManager.incrementQuest(QuestManager.java:138)
    at net.citizensnpcs.questers.listeners.QuesterPlayerListen.onPlayerMove(QuesterPlayerListen.java:32)
    at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:302)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:181)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:671)
    at net.minecraft.server.Packet10Flying.a(SourceFile:126)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-14 13:25:27 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-12-14 13:25:28 [INFO] [Citizens] 
2011-12-14 13:25:28 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net
2011-12-14 13:25:28 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
2011-12-14 13:25:28 [SEVERE] Could not pass event CUSTOM_EVENT to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.quests.progress.QuestProgress.updateProgress(QuestProgress.java:77)
    at net.citizensnpcs.questers.QuestManager.incrementQuest(QuestManager.java:138)
    at net.citizensnpcs.questers.listeners.QuesterCitizensListen.onCustomEvent(QuesterCitizensListen.java:37)
    at org.bukkit.plugin.java.JavaPluginLoader$96.execute(JavaPluginLoader.java:934)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:104)
    at org.bukkit.plugin.java.JavaPluginLoader$68.execute(JavaPluginLoader.java:735)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:79)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:337)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:902)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-14 13:25:28 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2011-12-14 13:25:28 [INFO] [Citizens] 
2011-12-14 13:25:28 [INFO] [Citizens] Citizens Error Reporting - Powered by CreeperHost.net

The config of the quest I created in the Quests.yml to verify it is set up correctly.

"Honeyhint1":
    requirements:
        '0':
            type: quest
            quest: 'Lets find honeydew'
            times: -1
    texts:
        description: "You say your looking for a dwarf?"
        completion: "<delay=100>Why don't you go and ask there?"
        acceptance: "I Think I saw him escorted away...<br><delay=40> to the prison...<br><delay=40> by town guards."
    repeats: 100
    objectives:
        '0':
            type: move distance
            amount: 0
            finishhere: true

The premise is... this is designed to be a 'hint' for another quest that is active (still haven't found anything more about allowing multiple quests, but I will deal with that later, there is a ticket for that as well) it checks that the player has the required quest active or it doesn't lauch (which in itself I saw issues, again will deal with later) and offers a hint as to what to do. The quest is a stupid little search using the Yogs Characters, where Xephos wants you to find Honeydew for him. That quest is not related to the issue as I have tested this config independantly of the other quest.

Everything works fine until you move, which is triggering the move distance setting, maybe I just haven't set it correctly. Any help appreciated.

**Comment by darkwarriors** [comment]
move distance

amount:0?

what are u menaing with that? 0 blocks? what moving quest is it if player has to move about 0 blocks?

**Comment by Craigdb** [comment]
the idea is that this was simply a hint for a bigger quest, therefor the requirement is simply to talk to this character to get the hint and complete that 'miniquest'. So once you talk to them the quest finishes. It is not supposed to be an true quest. I tried setting the move distance to 1, thinking that 0 could be a problem but I still get the same errors. I have worked around this for now and got the main quest working, as the other big problem with the idea I had is that you cannot be assigned a new quest if you are currently on one.
Here is a run down of what I wanted.

Talk to Xephos, he wants you to find another Honeydew... there are then a few other NPCs around the world... when talked to, they give suggestions on where to find Honeydew. Obviously, it would be a pain for players that stumble on Honeydew without talking to the 'hint' NPCs if they have to go back, find all the hint characters and complete those requirements just so they can progress (which is why I didn't put that section in the 'requirements'). The hints are supposed to be optional, so I made these miniquests. They are SUPPOSED to check if you have the main quest, and only give their miniquest to players if they are doing the main quest. It seems the quest system hasn't been geared to allow for these possiblities, but if it can be done, that would open up SOOOO many more options for creating really good quests and make citizens that much more of an 'essencial' plugin for RPG servers. Maybe it does work, but in another way than what I came up with. I'm open to all feedback regarding this. This is my first quest so I make no claims to knowing how the system really works.
