### ISSUE TITLE
Error while parsing a block mapping... [Quests bug]

### ISSUE THREAD

**Issue by Lextao** [CitizensDev/Citizens#470]
Im getting this at startup...

[SEVERE] while parsing a block mapping 
in "<string>", line 222, column 9:  
description: "<14>-=== MisiÃ³n:< ...  
^  
expected <block end>, but found Scalar  
in "<string>", line 223, column 22:  
completion: "<14>-=== MisiÃ³n Completada ===- ...  
^  
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480) 
2011-12-14 16:50:29 [SEVERE] at org.yaml.snakeyaml.Yaml.load(Yaml.java:399) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109) 
2011-12-14 16:50:29 [SEVERE] at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:37) 
2011-12-14 16:50:29 [SEVERE] at net.citizensnpcs.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:30) 
2011-12-14 16:50:29 [SEVERE] at net.citizensnpcs.questers.data.QuestProperties.<clinit>(QuestProperties.java:9) 
2011-12-14 16:50:29 [SEVERE] at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:32) 
2011-12-14 16:50:29 [SEVERE] at net.citizensnpcs.Citizens.onEnable(Citizens.java:85) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:968) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:186) 
2011-12-14 16:50:29 [SEVERE] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:169) 
2011-12-14 16:50:29 [SEVERE] at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:348) 
2011-12-14 16:50:29 [SEVERE] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:335) 
2011-12-14 16:50:29 [SEVERE] at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:165) 
2011-12-14 16:50:29 [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:399) 
2011-12-14 16:50:29 [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:457) 

This is my QUEST.YML: http://pastebin.com/V2W3vWt5
This happened back in 1.8.1 using 1.1.2 version of Citizens, it is still there using 1.1.3...
Can someone tell me what is causing it? :$

**Comment by Sdrubs** [comment]
There is a problem in your .yml,use YML online parser (http://yaml-online-parser.appspot.com/) and paster ALL the quest.yml,it gonna say all errors,after fixed i believe it gonna work normaly

**Comment by fullwall** [comment]
Perhaps you didn't close the quote? Try the link above anyway.
