### ISSUE TITLE
Error: Command Not Found. Use /npc help for commands

### ISSUE THREAD

**Issue by madyson0915** [CitizensDev/Citizens#472]
I have the latest updates of CB and citizens.
other plugins: 
- AutoEnchanter
  -BanHammer
  -Blockhat
  -Colors
  -Creative Gates
  -Essentials
  -Falsebook
  -Pet Creeper
  -World Edit
  -World Guard
  -Seats
  -Mob Rider

Java Error report:

18:42:46 [SEVERE] Error occurred while enabling Citizens v1.1.2 (Is it up to date?): net/citizensnpcs/api/event/citizens/CitizensEvent
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/citizens/CitizensEvent
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.citizensnpcs.questers.QuesterType.getCommands(QuesterType.java:27)
    at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:49)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:304)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:968)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:186)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:169)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:348)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:335)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:165)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:399)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.citizens.CitizensEvent
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 38 more
18:42:46 [INFO] [CreativeGates v1.3.2] === ENABLE START ===
18:42:46 [INFO] [CreativeGates v1.3.2] No permission plugin detected. Defaulting to native bukkit permissions.
18:42:46 [INFO] [CreativeGates v1.3.2] === ENABLE DONE (Took 123ms) ===
18:42:46 [WARNING] Server permissions file permissions.yml is not valid YAML.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
    at org.bukkit.craftbukkit.CraftServer.loadCustomPermissions(CraftServer.java:456)

**Comment by fullwall** [comment]
You need to update your type jars.
