### ISSUE TITLE
Could not load 'plugins\Citizens.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by vader07d** [CitizensDev/Citizens#474]
23:26:43 [SEVERE] Could not load 'plugins\Citizens.jar' in folder 'plugins':
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:62)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:215)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:151)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:127)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:145)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by fullwall** [comment]
Invalid download. Try 1.1.3 from devbukkit.
