### ISSUE TITLE
Guard Crash

### ISSUE THREAD

**Issue by Sdrubs** [CitizensDev/Citizens#482]
The Plugin citizens crashes when a guard is killed (Bouncer one),
Last RB - Bukkit
## Citizens - 1.1.3

Log error:
07:47 PM [SEVERE] java.lang.IndexOutOfBoundsException: Index: 251, Size: 251 
07:47 PM [SEVERE] at java.util.ArrayList.rangeCheck(Unknown Source) 
07:47 PM [SEVERE] at java.util.ArrayList.remove(Unknown Source) 
07:47 PM [SEVERE] at net.minecraft.server.World.tickEntities(World.java:1153) 
07:47 PM [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:518) 
07:47 PM [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425) 
07:47 PM [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:457) 
07:47 PM [SEVERE] Unexpected exception

**Comment by Avaryan** [comment]
Same issue I was just about to report. Here is the error I got.
2011-12-17 20:31:09 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 136, Size: 136
2011-12-17 20:31:09 [SEVERE]    at java.util.ArrayList.rangeCheck(Unknown Source)
2011-12-17 20:31:09 [SEVERE]    at java.util.ArrayList.remove(Unknown Source)
2011-12-17 20:31:09 [SEVERE]    at net.minecraft.server.World.tickEntities(World.java:1153)
2011-12-17 20:31:09 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:518)
2011-12-17 20:31:09 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
2011-12-17 20:31:09 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-17 20:31:09 [SEVERE] Unexpected exception
java.lang.IndexOutOfBoundsException: Index: 136, Size: 136
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.remove(Unknown Source)
    at net.minecraft.server.World.tickEntities(World.java:1153)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:518)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by mmuziek** [comment]
well it happens only on the first bouncer .
mabe removing it and placing a new bouncer will solve the problem . well atleast it did with me. but i dont use guards because they are buggy  failing to attack groups or they do not walk back to their station.and such

**Comment by Sdrubs** [comment]
Nope,if you add him again it doesn't work after all,it crashes the server if you kill the guard with a bow,and yes,the guard doesn't go back to his place... but at least he can attack the enemy '-'
