### ISSUE TITLE
Server crashing issue relating to citizens saving

### ISSUE THREAD

**Issue by paully104** [CitizensDev/Citizens#507]
[Citizens] Saved.
2011-12-20 05:11:56 [INFO] [Citizens] Saving npc files to disk...
2011-12-20 05:11:56 [SEVERE] java.io.IOException: There is not enough space on the disk
2011-12-20 05:11:56 [SEVERE]    at java.io.FileOutputStream.writeBytes(Native Method)
2011-12-20 05:11:56 [SEVERE]    at java.io.FileOutputStream.write(Unknown Source)
2011-12-20 05:11:56 [SEVERE]    at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
2011-12-20 05:11:56 [SEVERE]    at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
2011-12-20 05:11:56 [SEVERE]    at sun.nio.cs.StreamEncoder.close(Unknown Source)
2011-12-20 05:11:56 [SEVERE]    at java.io.OutputStreamWriter.close(Unknown Source)
2011-12-20 05:11:56 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:61)
2011-12-20 05:11:56 [SEVERE]    at net.citizensnpcs.properties.CachedYAMLHandler.save(CachedYAMLHandler.java:61)
2011-12-20 05:11:56 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.saveState(PropertyManager.java:110)
2011-12-20 05:11:56 [SEVERE]    at net.citizensnpcs.Citizens$1.run(Citizens.java:120)
2011-12-20 05:11:56 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-12-20 05:11:56 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
2011-12-20 05:11:56 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
2011-12-20 05:11:56 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-20 05:11:56 [INFO] [Citizens] Saved.
2011-12-20 06:11:56 [INFO] [Citizens] Saving npc files to disk...
2011-12-20 06:11:56 [SEVERE] java.io.IOException: There is not enough space on the disk
2011-12-20 06:11:56 [SEVERE]    at java.io.FileOutputStream.writeBytes(Native Method)
2011-12-20 06:11:56 [SEVERE]    at java.io.FileOutputStream.write(Unknown Source)
2011-12-20 06:11:56 [SEVERE]    at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
2011-12-20 06:11:56 [SEVERE]    at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
2011-12-20 06:11:56 [SEVERE]    at sun.nio.cs.StreamEncoder.close(Unknown Source)
2011-12-20 06:11:56 [SEVERE]    at java.io.OutputStreamWriter.close(Unknown Source)
2011-12-20 06:11:56 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:61)
2011-12-20 06:11:56 [SEVERE]    at net.citizensnpcs.properties.CachedYAMLHandler.save(CachedYAMLHandler.java:61)
2011-12-20 06:11:56 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.saveState(PropertyManager.java:110)
2011-12-20 06:11:56 [SEVERE]    at net.citizensnpcs.Citizens$1.run(Citizens.java:120)
2011-12-20 06:11:56 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2011-12-20 06:11:56 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
2011-12-20 06:11:56 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
2011-12-20 06:11:56 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-20 06:11:56

**Comment by mmuziek** [comment]
as the error says
there is not enought space on ur drive to save the NPCs

**Comment by fullwall** [comment]
Not enough disk space.
