### ISSUE TITLE
Citizens Bugging Out

### ISSUE THREAD

**Issue by HuntorWorks** [CitizensDev/Citizens#53]
Ok, i have had nothing but headaches with this plugin currently.  It installs just fine, and can use all commands and creates NPCs fine.  But they keep disappearing,  when i log out and back in or when i restart my server.  Also on 1 occasion they were cloned and instead of having 2 of one type of npc, i ended up with 5 some how.  When i go to select the NPC with the ID command,  it says no npc found with that ID, and i created it not 10 mins ago,  and when i use /npc list no NPC's show up. 

I get this error in my log, 

2011-08-31 11:25:17 [SEVERE] Could not pass event ENTITY_DAMAGE to Citizens
java.lang.NoClassDefFoundError: Could not initialize class com.citizens.CreatureTask
    at com.citizens.listeners.EntityListen.onEntityDamage(EntityListen.java:47)
    at org.bukkit.plugin.java.JavaPluginLoader$59.execute(JavaPluginLoader.java:656)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.Entity.burn(Entity.java:652)
    at net.minecraft.server.Entity.move(Entity.java:601)
    at net.minecraft.server.EntityLiving.a(EntityLiving.java:582)
    at net.minecraft.server.EntityLiving.v(EntityLiving.java:704)
    at net.minecraft.server.EntityMonster.v(EntityMonster.java:26)
    at net.minecraft.server.EntitySkeleton.v(EntitySkeleton.java:45)
    at net.minecraft.server.EntityLiving.m_(EntityLiving.java:218)
    at net.minecraft.server.EntityMonster.m_(EntityMonster.java:30)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1212)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:48)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1194)
    at net.minecraft.server.World.cleanUp(World.java:1110)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:450)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by aPunch** [comment]
1. Remove all single quotes from config files. To avoid even more headaches, delete all config files and let them regenerate.
2. NPCs disappearing is a known bug.
3. We have traced NPC duplication down to being a conflict with Spout. Are you running Spout and plugins that use Spout?

**Comment by HuntorWorks** [comment]
Yes,  and since have removed spout and citizens spout. 

Also just to mention, i know questers and guards are bugged,  but i cant right click for healers either,  even when i change the id number in the config file.  Ive tested multiple items,  healer is leveled up,  and cant even seem to set the right economy settings up to use with iConomy 5 

Also, is there a permission node to allow other players to interact, becasuse they cant seem to either.

**Comment by aPunch** [comment]
Healers need to be left-clicked to work. I'm thinking about changing this in 1.1.

The node for using healers is citizens.healer.use.heal

**Comment by HuntorWorks** [comment]
OK,  but i try and click with the selected item ID in the config file and nothing happens. Just them spamming there texts at me.   Is the node the same format for all types of npc's etc

citizens.blacksmith.use.*
citizens.quester.use*
etc ...

**Comment by aPunch** [comment]
I don't know what you are asking. I thought you were having trouble with healers yet you are posting nodes for blacksmiths/questers? Could you clarify?

**Comment by HuntorWorks** [comment]
All the NPC's do not work!  I was asking for all nodes.  But have since abandoned citizens plugin, becasue it does not work on my server for some reason.

**Comment by aPunch** [comment]
Oh. https://github.com/fullwall/Citizens/wiki has all of the 1.0.9d permissions nodes. Questers/Guards don't have nodes because they are not finished and are unsupported until v1.1.
