### ISSUE TITLE
Citizens Reload Error

### ISSUE THREAD

**Issue by HuntorWorks** [CitizensDev/Citizens#54]
When i try to reload i get this error:

2011-08-31 14:42:24 [INFO] [Citizens] Reloading configuration settings....
2011-08-31 14:42:24 [SEVERE] while scanning an alias
 in "<reader>", line 10, column 23:
            select-items: *
                          ^
expected alphabetic or numeric character, but found but found 

 in "<reader>", line 10, column 24:
            select-items: *
                           ^

2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.scanAnchor(ScannerImpl.java:1156)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchAlias(ScannerImpl.java:782)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:313)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:183)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:592)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:124)
2011-08-31 14:42:24 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
2011-08-31 14:42:24 [SEVERE]    at org.bukkit.util.config.Configuration.load(Configuration.java:82)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.properties.ConfigurationHandler.load(ConfigurationHandler.java:55)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:33)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.properties.properties.UtilityProperties.initialize(UtilityProperties.java:21)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.commands.commands.BasicCommands.reload(BasicCommands.java:98)
2011-08-31 14:42:24 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-08-31 14:42:24 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2011-08-31 14:42:24 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2011-08-31 14:42:24 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:518)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.resources.sk89q.CommandsManager.execute(CommandsManager.java:404)
2011-08-31 14:42:24 [SEVERE]    at com.citizens.Citizens.onCommand(Citizens.java:196)
2011-08-31 14:42:24 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
2011-08-31 14:42:24 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:129)
2011-08-31 14:42:24 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:352)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:737)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:701)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:694)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
2011-08-31 14:42:24 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by aPunch** [comment]
Add single quotes are the select-items setting.
