### ISSUE TITLE
Cititzens npc creating error! on minecraft 1.0.0

### ISSUE THREAD

**Issue by exmo911** [CitizensDev/Citizens#548]
If i type /npc create BoB it come a error on the console CITIZENS VERSION:1.1.2| BUKKIT  VERSIOn:
First im start my server its say:[WARNING] Task of 'Citizens' generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/Packet17EntityLocationAction
    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:31)
    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:51)
    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:16)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:284)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:134)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:482)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17EntityLocationAction
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more
And when i type /npc create BoB it say:[SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/Packet17EntityLocationAction
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:31)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.npclib.PathNPC.<init>(PathNPC.java:51)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:16)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2011-12-29 13:46:20 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-12-29 13:46:20 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2011-12-29 13:46:20 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2011-12-29 13:46:20 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2011-12-29 13:46:20 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
2011-12-29 13:46:20 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:364)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:756)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:721)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
2011-12-29 13:46:20 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-29 13:46:20 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet17EntityLocationAction
2011-12-29 13:46:20 [SEVERE]    at java.net.URLClassLoader$1.run(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    at java.security.AccessController.doPrivileged(Native Method)
2011-12-29 13:46:20 [SEVERE]    at java.net.URLClassLoader.findClass(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
2011-12-29 13:46:20 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
2011-12-29 13:46:20 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2011-12-29 13:46:20 [SEVERE]    ... 27 more 
PLz ansver and fix that!

**Comment by IDragonfire** [comment]
What bukkit version did you use?

**Comment by notcam45** [comment]
Make sure you have to current version of bukkit and citizens!

**Comment by exmo911** [comment]
Oo sorry im gonna fix that but not now i on my phone not computer sorry 
guys! :(

**Comment by IDragonfire** [comment]
https://github.com/CitizensDev/Citizens/issues/426#issuecomment-3313462
