### ISSUE TITLE
Killing npcs with arrows

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#57]
Every time an NPC is shot and killed with a bow and arrows (I've only tried this on guard bouncers) it freezes the server. All players get disconnected, the console is still up, no reloads work at all. It has to be shut down and restarted. Right when the NPC dies it displays this error in the console:

2011-08-24 03:47:38 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 178, Size: 178
2011-08-24 03:47:38 [SEVERE]     at java.util.ArrayList.RangeCheck(Unknown Source)
2011-08-24 03:47:38 [SEVERE]     at java.util.ArrayList.remove(Unknown Source)
2011-08-24 03:47:38 [SEVERE]     at net.minecraft.server.World.cleanUp(World.java:1120)
2011-08-24 03:47:38 [SEVERE]     at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:450)
2011-08-24 03:47:38 [SEVERE]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
2011-08-24 03:47:38 [SEVERE]     at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-08-24 03:47:38 [SEVERE] Unexpected exception
java.lang.IndexOutOfBoundsException: Index: 178, Size: 178
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.remove(Unknown Source)
    at net.minecraft.server.World.cleanUp(World.java:1120)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:450)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by fullwall** [comment]
Hmmm... that is extremely odd.

**Comment by mbsuperstar1** [comment]
What version of citizens is this with? I cannot create on the latest.

**Comment by defaultsucks** [comment]
This is on 1.0.9d

**Comment by aPunch** [comment]
Those who are using developmental builds report that this is no longer an issue.
