### ISSUE TITLE
Could not load plugins/Citizens.jar

### ISSUE THREAD

**Issue by Plexico** [CitizensDev/Citizens#578]
Could not load 'plugins/Citizens.jar' in folder 'plugins':java.util.zip.ZipException:error in opening zip file at java.util.zip.ZipFile.open(Native Method) at java.util.zip.ZipFile.<init>(Unknown Source)  at java.util.zip.ZipFile.<init>(Unknown Source) at java.util.zip.ZipFile.<init>(Unknown Source)at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:62) at org.bukkit.plugin.SimplePluginManager.loadpluginSimplePluginManager..java:136atorg.bukkit.craftbukkit.CraftServer.loadPlugins<CraftServer.java.127)atnet.minecraft.server.ServerConfigurationManager.<init<ServerConfigureationManager.java:52atnet.minecraft.server.MinecraftServer.init(MinecraftServer,jaja:145atnet.minecraft.server.MinecraftServer.run(MinecraftServer.java:399)atnet.minecraft.server.ThreadServerApplication.run(SourceFile:457

**Comment by MrRedLogan** [comment]
i also have this problem and i cant find a workaround =/

**Comment by Plexico** [comment]
Thank god I'm not alone

**Comment by Plexico** [comment]
Come on! It's been five hours please someone reply!

**Comment by MrRedLogan** [comment]
ok. I think the conflicting plugin is Multiverse

**Comment by intelnavi** [comment]
Removed multiverse and still have this problem.  So much for the stable version.
