### ISSUE TITLE
Quest does not finish.

### ISSUE THREAD

**Issue by Spl1tz** [CitizensDev/Citizens#584]
Hi i'm having an issue where my quest does not complete when having done all the objectives.
It doesn't count my collectibles (whenever i check it with /quest status) or when reaching over 300 melons it won't say anything at all.
This is the quest config.

"Melon affinity":
    texts:
        description: "Want to earn money? Well there is a food shortage in the Castle so i need men to farm me 300 melon slices. They'll be rewarded greatly!"
        completion: "Quest completed! Go get your reward."
        acceptance: "Quest accepted."
    repeats: -1
    objectives:
        '0':
            '0':
                type: collect
                materialid: 360
                amount: 300
                optional: False
                finishhere: True
                message: "Good job! That will keep food stocks filled for another month. Here is your reward."
    rewards:
        '0':
            type: money
            money: 150
        '1':
            type: item
            id: 357
            amount: 10
            take: True

**Comment by Mykekeul35** [comment]
Have you test with 

finishhere: False

?

**Comment by Spl1tz** [comment]
Yes i have just now and the quest still doesn't count the items i pick up...

**Comment by DreadBoy** [comment]
I have the same isssue. I used example2, but it doesn't count stones I pickup. Can anybody help, please?

**Comment by Fireelf15** [comment]
You need to change it to a delivery quest, then it does not need to count blocks as you get them but when you bring them back. Stones are also weird blocks, they are smooth stone when mined but turn into cobblestone, thus they don't work either way.

**Comment by DreadBoy** [comment]
Thank you for answer but this plugin just doesn't work for me. :S My bukkit version is 1.0.1-R1 and Citizens version is 1.1.3 and half of things just doesn't work. For example I assign a quest:
Wheat:
    texts:
        description: You need to bring me some wheat!
        completion: <g>Thank you! Give me that wheat please.
        acceptance: <g>Challenge <y>accepted<g>.
    repeats: 10
    objectives:
        '0':
            type: move location
            location: 268 64 -122
            amount: 2
            time: 1
            message: A voice echoes... "Splendid, now bring it back!"
        '1':
            type: delivery
            npcdestination: 15
            materialid: 296
            amount: 64
    rewards:
        '0':
            type: item
            id: 296
            amount: 64
        '1':
            type: money
            money: 100
Yaml parser doesn't find any errors and I can normally assign quest to quester but when I check it's status it says error and check conzole and console besides mess which I don't understand put out "Can't assign MOVE_PLAYER" or something similar. I double check versions of Citizens and Bukkit. Also pickup and brake block quests doesn't work but place block quest does work. This is a bit strange if you ask me. :S

EDIT: I pasted error message.
java.lang.NullPointerException
        at net.citizensnpcs.questers.quests.progress.QuestProgress.updateProgress(QuestProgress.java:77)
        at net.citizensnpcs.questers.QuestManager.incrementQuest(QuestManager.java:138)
        at net.citizensnpcs.questers.listeners.QuesterPlayerListen.onPlayerMove(QuesterPlayerListen.java:32)
        at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:307)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:182)
        at net.minecraft.server.Packet10Flying.a(SourceFile:126)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

EDIT2: Sorry guys for bothering you, I figured it out. My location was written wrongly. -.-

**Comment by Spl1tz** [comment]
Quester is broker imo...
