### ISSUE TITLE
Russian text problem

### ISSUE THREAD

**Issue by VcSaJen** [CitizensDev/Citizens#588]
When russian text in name or text of NPC, when server restart it change to "????????" and SEVERE error.
Is is not happens before.

Original text: Я злой! Я очень злой!
Changed to: ? ??????! ? ????? ??????!

2012-01-07 18:28:51 [SEVERE] mapping keys are not allowed here
 in "<string>", line 57, column 11:
        text: ? ??????!;? ????? ??????!
              ^

2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchKey(ScannerImpl.java:682)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:298)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:591)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
2012-01-07 18:28:51 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
2012-01-07 18:28:51 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
2012-01-07 18:28:51 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
2012-01-07 18:28:51 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
2012-01-07 18:28:51 [SEVERE]    at net.citizensnpcs.properties.CachedYAMLHandler.load(CachedYAMLHandler.java:40)
2012-01-07 18:28:51 [SEVERE]    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:271)
2012-01-07 18:28:51 [SEVERE]    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
2012-01-07 18:28:51 [SEVERE]    at net.citizensnpcs.Citizens$2.run(Citizens.java:134)
2012-01-07 18:28:51 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
2012-01-07 18:28:51 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
2012-01-07 18:28:51 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
2012-01-07 18:28:51 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by onotoleonide** [comment]
I have the same problem, which encoding Citizens using?

**Comment by DaveDee** [comment]
Пересохраните файлы конфига в UTF-8, после этого текст будет сохраняться нормально. Этот принцип работает и с другими плагинами.

**Comment by bormoshka** [comment]
В том то и дело что не помогает. Потом при сохранении плагин сам создаёт копии старых записей с нпс, только с именем  
 name: ?????? вместо     name: Бармен

В этом случае не прокатило, короче.

**Comment by DaveDee** [comment]
у нас все работает, этот способ подходит практически для всех плагинов, которые не имеют каких-то встроенных левых валидаторов, напрочь не признающих кириллицу. Возможно такое прокатывает только на юниксах...

**Comment by onotoleonide** [comment]
у меня норм, у вас БОРМОШКОПРОБЛЕМЫ
