### ISSUE TITLE
Citizens generated an exception

### ISSUE THREAD

**Issue by gummby8** [CitizensDev/Citizens#594]
2012-01-09 03:37:20 [WARNING] Task of 'Citizens' generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between worlds or to null
    at org.bukkit.Location.distance(Location.java:364)
    at net.citizensnpcs.resources.npclib.PathNPC.distance(PathNPC.java:95)
    at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:325)
    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:206)
    at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:84)
    at net.citizensnpcs.TickTask.run(TickTask.java:31)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

Something about distance between worlds. Citizens supports multiworlds. I can never seem to narrow down what is causing this as it happens completely randomly. It causes every citizens to stop functioning completely and just stand there idle

**Comment by Farwaykorse** [comment]
Have you set a path for some npc's?
If so, there isn't accidentally one that switches worlds? Or that has a waypoint in a different world than its current location? (Check the waypoints, in plugins/Citizens/npc-profiles.yml)

**Comment by gummby8** [comment]
No i confirmed it is an error generated when a guard is targeting a player (living or dead) and the player changes worlds. It is a serious problem in my eyes concidering it is supposed to support multiword. Rather than crash the plugin the guard should just drop his target and reset
