### ISSUE TITLE
Please update to Bukkit 1.1

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#615]
Bukkit 1.1 is out, yay :P
However citizens fails to load - there was some API changes in Minecraft Server.

2012-01-13 01:04:18 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
        at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
        at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
        at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
        at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:284)
        at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
        at net.citizensnpcs.Citizens$2.run(Citizens.java:134)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:500)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Please update to latest API, thanks ;)
I will look at this and try to fix it :)

**Comment by snitride** [comment]
same error here.

**Comment by BlockCat** [comment]
The recommended build isn't released yet so there is no point in asking for an update.

**Comment by ghost** [comment]
Ok, fixed. Citizens for 1.1 released :D!
Thanks :)

**Comment by TyphoonNL** [comment]
how did you fixed it?

**Comment by ghost** [comment]
Get code from github and compile it :P

**Comment by SupaYoshi** [comment]
macer1 ;) please how to compile !

**Comment by ghost** [comment]
Getting the same problem :3 help to compile too please!

**Comment by spydercanopus** [comment]
I'm not seeing the 1.1 version on the dev bukkit website.

**Comment by fullwall** [comment]
There's a test version on the thread a page or so back.

**Comment by ecasmb** [comment]
Probably..
This will help some people..
http://ci.citizensnpcs.net/
