### ISSUE TITLE
Citizens crashing & Guard bugs

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#63]
I wasn't sure whether to post this as two seperate issues, but I think they're connected. I downloaded the latest dev build #99 of citizens 1.1 because in the custom 1.1 build from your website right clicking on traders and opening up stocking crashed my client. That however is fixed in the latest build. I was just messing around with guards and flags and when I start the server, a bouncer guard with defined flags for mobs goes and attacks the first mob he sees (ex. a creeper). I'm not exactly sure but I think right after he kills the npc this error is displayed in the console:

2011-09-02 11:15:04 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
    at com.google.common.collect.Iterables.filter(Iterables.java:493)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(Unknown Source)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:136)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:131)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagList.process(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(Unknown Source)
    at net.citizensnpcs.guards.GuardTask.handleTarget(Unknown Source)
    at net.citizensnpcs.guards.GuardTask.run(Unknown Source)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:428)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

After this, the guard just remains in the same spot instead of going back to his original one. After that I started messing with flags again, assigned one guard an -a flag for everything and tried reloading citizens only with /citizens reload it froze the server with this error in the console:

2011-09-02 11:26:49 [SEVERE] java.lang.OutOfMemoryError: Java heap space
2011-09-02 11:26:50 [SEVERE]    at java.util.Arrays.copyOfRange(Unknown Source)
2011-09-02 11:26:50 [SEVERE]    at java.lang.String.<init>(Unknown Source)
2011-09-02 11:26:52 [SEVERE]    at java.lang.StringBuilder.toString(Unknown Source)
2011-09-02 11:26:52 [SEVERE]    at org.yaml.snakeyaml.reader.StreamReader.getMark(StreamReader.java:74)
2011-09-02 11:26:52 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:767)
2011-09-02 11:26:52 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:307)
2011-09-02 11:26:53 [SEVERE]    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:183)
2011-09-02 11:26:53 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:564)
2011-09-02 11:26:53 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
2011-09-02 11:26:53 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
2011-09-02 11:26:53 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
2011-09-02 11:26:54 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-09-02 11:26:54 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-09-02 11:26:54 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-09-02 11:26:54 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-09-02 11:26:54 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-09-02 11:26:55 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-09-02 11:26:55 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-09-02 11:26:55 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2011-09-02 11:26:55 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2011-09-02 11:26:55 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
2011-09-02 11:26:55 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
2011-09-02 11:26:56 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:124)
2011-09-02 11:26:56 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
2011-09-02 11:26:56 [SEVERE]    at org.bukkit.util.config.Configuration.load(Configuration.java:82)
2011-09-02 11:26:56 [SEVERE]    at net.citizensnpcs.properties.CachedYAMLHandler.load(Unknown Source)
2011-09-02 11:26:56 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.loadAll(Unknown Source)
2011-09-02 11:26:56 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.reload(Unknown Source)
2011-09-02 11:26:56 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2011-09-02 11:26:58 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2011-09-02 11:26:58 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2011-09-02 11:26:58 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)

Now my citizens doesn't load at all, no matter what I do. This error is displayed upon reloading it all:

2011-09-02 11:29:16 [SEVERE] Error occurred while enabling Citizens v1.1 (Is it up to date?): Java heap space
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOfRange(Unknown Source)
    at java.lang.String.<init>(Unknown Source)
    at java.lang.StringBuilder.toString(Unknown Source)
    at org.yaml.snakeyaml.reader.StreamReader.getMark(StreamReader.java:74)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:767)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:307)
    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:183)
    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:564)
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:163)
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:124)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:264)
    at org.bukkit.util.config.Configuration.load(Configuration.java:82)
    at net.citizensnpcs.properties.CachedYAMLHandler.load(Unknown Source)
    at net.citizensnpcs.properties.CachedYAMLHandler.<init>(Unknown Source)
    at net.citizensnpcs.properties.PropertyManager.<clinit>(Unknown Source)
    at net.citizensnpcs.blacksmiths.BlacksmithType.getProperties(Unknown Source)
    at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(Unknown Source)
    at net.citizensnpcs.Citizens.loadNPCTypes(Unknown Source)
    at net.citizensnpcs.Citizens.onEnable(Unknown Source)

And this one is displayed when shutting the server down:

2011-09-02 11:29:47 [SEVERE] Error occurred while disabling Citizens v1.1 (Is it up to date?): Could not initialize class net.citizensnpcs.properties.PropertyManager
java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.properties.PropertyManager
    at net.citizensnpcs.Citizens.onDisable(Unknown Source)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:128)
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:906)
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:294)
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:287)
    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:173)
    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:314)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:393)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by defaultsucks** [comment]
Update: I just checked my npc-profiles.yml and it's over 4 megabytes in size, spammed with lines like this:

```
        '37506':
            location: mainworld,-393.0,67.0,-106.0,0.0,0.0
            delay: '0'
        '42859':
            location: mainworld,-401.0,67.0,-104.0,0.0,0.0
            delay: '0'
        '25744':
            location: mainworld,-393.0,67.0,-106.0,0.0,0.0
            delay: '0'
        '41868':
            location: mainworld,-393.0,67.0,-106.0,0.0,0.0
            delay: '0'
```

I'm completely positive I didn't add all of these waypoints. This made the file 138,086 lines long.

**Comment by defaultsucks** [comment]
After cleaning the file of these bogus waypoints citizens started up just fine, however there appears to be a problem with adding an -a flag to guards. These are the errors:

2011-09-02 11:51:36 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
    at com.google.common.collect.Iterables.filter(Iterables.java:493)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(Unknown Source)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:136)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:131)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagList.process(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(Unknown Source)
    at net.citizensnpcs.guards.GuardTask.handleTarget(Unknown Source)
    at net.citizensnpcs.guards.GuardTask.run(Unknown Source)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:428)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-09-02 11:51:36 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
    at com.google.common.collect.Iterables.filter(Iterables.java:493)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(Unknown Source)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:136)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:131)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagList.process(Unknown Source)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(Unknown Source)
    at net.citizensnpcs.guards.GuardTask.handleTarget(Unknown Source)
    at net.citizensnpcs.guards.GuardTask.run(Unknown Source)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:428)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by fullwall** [comment]
Should be fixed now.
