### ISSUE TITLE
Startup Error on 1.1 Server

### ISSUE THREAD

**Issue by Krglok** [CitizensDev/Citizens#630]
2012-01-15 18:25:30 [INFO] Starting minecraft server version 1.1
:::
2012-01-15 18:25:39 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:284)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:134)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:500)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Xevets** [comment]
Same error here. I'm running a new 1.1 install of bukkit and citizens.

**Comment by Krglok** [comment]
I think i found the issue for the error :(
there are no CB 1.1.x   release.
the download data are :
1.1.3  Release Semi-normal 14 Dec 2011 CB 1.0.1-R1 Citizens1.1.3.zip 
the download said last revision  on CB 1.0.1-R1

sorry, sometimes i cannot read exakly :(

**Comment by andrewmunro** [comment]
Download the latest source code and compile.

**Comment by l1amm** [comment]
synestry, mind posting a compiled one? Where do you see the source lol ?

**Comment by andrewmunro** [comment]
If you don't know how to compile your own, you can always get the latest dev-builds from http://ci.citizensnpcs.net/

Just download the citizens.jar from the latest build and pop it in your plugins folder (you don't need the blacksmith-wizard jars unless you want them).

**Comment by Krglok** [comment]
I followed the links on your page to -> SOURCE :)
the #360 startup without any error , thx :)
