### ISSUE TITLE
[!] Shooting a Guard NPC with an arrow from outside its attack radius causes server crash.

### ISSUE THREAD

**Issue by EarlyLegend** [CitizensDev/Citizens#633]
When I shoot a guard NPC from outside of its attack range, the server immediately throws this error, and then it crashes. No exceptions :(

<code>
22:00:12 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 94, Size: 94
22:00:12 [SEVERE]       at java.util.ArrayList.rangeCheck(Unknown Source)
22:00:12 [SEVERE]       at java.util.ArrayList.remove(Unknown Source)
22:00:12 [SEVERE]       at net.minecraft.server.World.tickEntities(World.java:1153)
22:00:12 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:518)
22:00:12 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
22:00:12 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
22:00:12 [SEVERE] Unexpected exception
java.lang.IndexOutOfBoundsException: Index: 94, Size: 94
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.remove(Unknown Source)
        at net.minecraft.server.World.tickEntities(World.java:1153)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:518)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
</code>

Hopefully this can get fixed, so I can utilise the full potential of the Citizens plugin on my server - thanks!

**Comment by EarlyLegend** [comment]
I should add that this is for minecraft version 1.0 and server version 1.0.1.
