### ISSUE TITLE
Cannot Create NPC's 1.1

### ISSUE THREAD

**Issue by NumbedShot** [CitizensDev/Citizens#639]
2012-01-18 19:55:42 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-01-18 19:55:42 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-01-18 19:55:42 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2012-01-18 19:55:42 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-01-18 19:55:42 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:616)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-01-18 19:55:42 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2012-01-18 19:55:42 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-01-18 19:55:42 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-01-18 19:55:42 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:385)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-01-18 19:55:42 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by qutmattb** [comment]
Yeah i got the same thing!

**Comment by Felipegas360** [comment]
Yes 
Eu tambme tenho esse problema!

**Comment by Serverfrog** [comment]
Same issue as https://github.com/CitizensDev/Citizens/issues/646

**Comment by NumbedShot** [comment]
This was posted before 646. With the full log.

**Comment by Serverfrog** [comment]
I have also copy past the whole text that i typed there... its fyi :D have the same problem and there is the workaround
