### ISSUE TITLE
1.1 error every time the server is shut down

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#65]
Every time the server is shut down it displays this error in the console:

2011-09-02 11:58:43 [SEVERE] Could not pass event CUSTOM_EVENT to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.PlayerProfile.saveAll(Unknown Source)
    at net.citizensnpcs.questers.listeners.QuesterCitizensListen.onCitizensDisable(Unknown Source)
    at net.citizensnpcs.api.event.citizens.CitizensListener.onCustomEvent(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$88.execute(JavaPluginLoader.java:862)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.citizensnpcs.Citizens.onDisable(Unknown Source)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:128)
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:906)
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:294)
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:287)
    at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:173)
    at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:314)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:393)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by fullwall** [comment]
Should be fixed in my next commit.
