### ISSUE TITLE
Citizens NPC Spawn Error.

### ISSUE THREAD

**Issue by Ieroy** [CitizensDev/Citizens#657]
05:34 PM [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V 
05:34 PM [SEVERE] at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17) 
05:34 PM [SEVERE] at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75) 
05:34 PM [SEVERE] at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159) 
05:34 PM [SEVERE] at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189) 
05:34 PM [SEVERE] at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226) 
05:34 PM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
05:34 PM [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
05:34 PM [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
05:34 PM [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source) 
05:34 PM [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530) 
05:34 PM [SEVERE] at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407) 
05:34 PM [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:200) 
05:34 PM [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40) 
05:34 PM [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) 
05:34 PM [SEVERE] at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:385) 
05:34 PM [SEVERE] at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777) 
05:34 PM [SEVERE] at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737) 
05:34 PM [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725) 
05:34 PM [SEVERE] at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33) 
05:34 PM [SEVERE] at net.minecraft.server.NetworkManager.b(NetworkManager.java:226) 
05:34 PM [SEVERE] at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100) 
05:34 PM [SEVERE] at net.minecraft.server.NetworkListenThread.a(SourceFile:108) 
05:34 PM [SEVERE] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536) 
05:34 PM [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434) 
05:34 PM [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Ieroy** [comment]
I typed /npc create bob

And this appeared in the console.

**Comment by Winters-nyx** [comment]
I'm having the same issue, Just installed it w/o any editing/config.

I typed: /npc create bot1

((Plz help! I love citizens and I must have them again!))

**Comment by BloodMist** [comment]
Damn, I have same problem. How can this be fixed?

**Comment by sebastian192** [comment]
I have the same problem...

**Comment by BloodMist** [comment]
I used a different build package, and the error stopped. I looked for awhile, but I cant remember the post i found. But I found the issue for this error. It is simply your using the wrong build for citizens that doesn't correspond with the craft bukkit build your using. Hope this helps anyone that is still having this issue.
