### ISSUE TITLE
Can't create a character!

### ISSUE THREAD

**Issue by Carmadon** [CitizensDev/Citizens#659]
Command  /npc create doesn't work!

Console looks like this after this command:

16:21:41 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
16:21:41 [SEVERE]       at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
16:21:41 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
16:21:41 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
16:21:41 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
16:21:41 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
16:21:41 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:21:41 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
16:21:41 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:21:41 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:616)
16:21:41 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
16:21:41 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
16:21:41 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
16:21:41 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
16:21:41 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:21:41 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:385)
16:21:41 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
16:21:41 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
16:21:41 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
16:21:41 [SEVERE]       at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
16:21:41 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
16:21:41 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
16:21:41 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
16:21:41 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
16:21:41 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
16:21:41 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

Using Craftbukkit version git-Bukkit-1.0.1-R1-79-g241b6f1-b1772jnks (MC: 1.1) (Implementing API version 1.1-R1-SNAPSHOT)

**Comment by BloodMist** [comment]
I get this error as well. Any help?

**Comment by sebastian192** [comment]
Download a older version :)
That should help :)
