### ISSUE TITLE
[Severe] Error occurred while enabling Citizens v1.1.4

### ISSUE THREAD

**Issue by clucky** [CitizensDev/Citizens#667]
09:58:29 [INFO] [Citizens] Loading Citizens v1.1.4.
09:58:29 [INFO] [Citizens] NPC types loaded: healer, blacksmith, trader, wizard, quester, guard
09:58:29 [SEVERE] Error occurred while enabling Citizens v1.1.4 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at net.citizensnpcs.healers.HealerType.registerEvents(HealerType.java:27)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 23 more
09:58:29 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...

**Comment by Fureniku** [comment]
Another one:

Error occurred while enabling Citizens v1.1.4 (Is it up to date?): org.bukkit.event.EventHandler missing element event
java.lang.annotation.IncompleteAnnotationException: org.bukkit.event.EventHandler missing element event
    at sun.reflect.annotation.AnnotationInvocationHandler.invoke(Unknown Source)
    at $Proxy18.event(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:990)
    at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:432)
    at net.citizensnpcs.npctypes.NPCTypeManager.registerEvents(NPCTypeManager.java:36)
    at net.citizensnpcs.traders.TraderType.registerEvents(TraderType.java:27)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:232)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1034)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:252)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:190)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:173)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

EDIT: Just looked at it again, think it might be me actually (I'm using an older CB) . Still bumping for the other error above though :)

**Comment by ghost** [comment]
[INFO] [Citizens] NPC types loaded: quester, wizard, trader, blacksmith, healer, guard
2012-01-25 19:08:20 [SEVERE] Error occurred while enabling Citizens v1.1.4 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:34)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 24 more

Getting the same error here. :/

**Comment by Armarr** [comment]
same
25.01 21:51:48 [Server] Startup Done (8.659s)! For help, type "help" or "?"
25.01 21:51:47 [Server] INFO [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
25.01 21:51:47 [Server] INFO [Citizens] An error occurred whilst sending your error report.
25.01 21:51:47 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
25.01 21:51:47 [Server] INFO [Citizens] An error has occurred, please wait while it is sent to the developers...
25.01 21:51:47 [Server] INFO    ... 24 more
25.01 21:51:47 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
25.01 21:51:47 [Server] INFO    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
25.01 21:51:47 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
25.01 21:51:47 [Server] INFO    at java.security.AccessController.doPrivileged(Native Method)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
25.01 21:51:47 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
25.01 21:51:47 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
25.01 21:51:47 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
25.01 21:51:47 [Server] INFO    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
25.01 21:51:47 [Server] INFO    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
25.01 21:51:47 [Server] INFO    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
25.01 21:51:47 [Server] INFO    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
25.01 21:51:47 [Server] INFO    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
25.01 21:51:47 [Server] INFO    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
25.01 21:51:47 [Server] INFO    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
25.01 21:51:47 [Server] INFO    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
25.01 21:51:47 [Server] INFO    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
25.01 21:51:47 [Server] INFO    at net.citizensnpcs.healers.HealerType.registerEvents(HealerType.java:27)
25.01 21:51:47 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
25.01 21:51:47 [Server] INFO    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
25.01 21:51:47 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
25.01 21:51:47 [Server] INFO    at java.security.AccessController.doPrivileged(Native Method)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
25.01 21:51:47 [Server] INFO    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
25.01 21:51:47 [Server] INFO    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
25.01 21:51:47 [Server] INFO    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
25.01 21:51:47 [Server] INFO    at java.lang.ClassLoader.defineClass1(Native Method)
25.01 21:51:47 [Server] INFO java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
25.01 21:51:47 [Server] SEVERE Error occurred while enabling Citizens v1.1.4 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
25.01 21:51:47 [Server] INFO LWC: Latest version: b615
25.01 21:51:47 [Server] INFO [Citizens] Writing default setting general.pathing.realistic.
25.01 21:51:47 [Server] INFO [Citizens] NPC types loaded: healer, trader, wizard, guard, quester, blacksmith
25.01 21:51:47 [Server] INFO [Citizens] Loading Citizens v1.1.4.

**Comment by Loserman778** [comment]
Use pastebin

**Comment by vaqu** [comment]
[SEVERE] Could not pass event net.citizensnpcs.api.event.NPCTargetEvent to Citizens
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1028)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:327)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:327)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:923)
    at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
    ... 18 more
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.inventory.CraftInventory.getItem(CraftInventory.java:30)
    at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.getHelmet(CraftInventoryPlayer.java:33)
    at net.citizensnpcs.traders.TraderTask.clonePlayerInventory(TraderTask.java:331)
    at net.citizensnpcs.traders.TraderTask.<init>(TraderTask.java:44)
    at net.citizensnpcs.traders.Trader.onRightClick(Trader.java:157)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:91)
    ... 23 more

**Comment by clucky** [comment]
This still doesn't work for me.

07:13:17 [SEVERE] Error occurred while enabling Citizens v1.1.5 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at net.citizensnpcs.healers.HealerType.registerEvents(HealerType.java:27)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 23 more
07:13:17 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...

**Comment by Armarr** [comment]
I had to delete the old config and redo NPC's to fix this issue.

**Comment by clucky** [comment]
Thank you, when I get back to my computer I will try this and see if it works and reply back

**Comment by clucky** [comment]
This didn't fix the problem
