### ISSUE TITLE
Citizens/towny chat conflict?

### ISSUE THREAD

**Issue by arriej** [CitizensDev/Citizens#673]
hello,

getting this error when doing a npc command

[SEVERE] Could not pass event org.bukkit.event.player.PlayerCommandPreprocessEvent to TownyChat
java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.TownySettings.chatChannelExists(Ljava/lang/String;)Z
    at com.palmergames.bukkit.TownyChat.event.TownyPlayerHighestListener.onPlayerCommandPreprocess(TownyPlayerHighestListener.java:54)
    at org.bukkit.plugin.java.JavaPluginLoader$5.execute(JavaPluginLoader.java:298)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:453)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:770)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

maybe its only townychat i dont know,

tnx

**Comment by azak1r** [comment]
seems to me it is more a townychat related error then a citizens error. what is the log saying above the [SEVERE] message?
