### ISSUE TITLE
Missing NPCs on latest release for 1.1

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens#692]
I'm seeing some NPCs are missing, although when you approach the location they are set in, they will still initiate dialog.

**Comment by FePython** [comment]
im missing all of my NPCs there still on the file in the citizen folder but there not showing up in game when i try and spawn a  new one i get this error

2012-01-30 02:14:56 [SEVERE] java.lang.NoSuchMethodError: net.minecraft.server.ItemInWorldManager.a(I)V
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.<init>(CraftNPC.java:17)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCSpawner.spawnNPC(NPCSpawner.java:75)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:159)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:189)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-01-30 02:14:56 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-01-30 02:14:56 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-01-30 02:14:56 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-01-30 02:14:56 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-01-30 02:14:56 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:200)
2012-01-30 02:14:56 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-01-30 02:14:56 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-01-30 02:14:56 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
2012-01-30 02:14:56 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:178)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-01-30 02:14:56 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:587)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-01-30 02:14:56 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by kripts** [comment]
Are you both running on the latest Craftbukkit RB? and Citizens 1.1.5?

**Comment by FePython** [comment]
yeah i have the latest CB RB and 1.1.5 but for whatever reason a few of my NPCs just will not reload after a retart of the server or a relogin sometimes. these are some of the things i have tryed

recreating the NPC
Moving the NPC (see if it was an XYZ error)
Removed the NPC creating new ones then remaking them (to see if it was the NPC #)

non of those seam to fix it its always the same 6 NPCs that create the error tonight im going to try remaking them with a new name see if thats creating a problem though i cant see how "Boff, Flim, and Nalrod" would create errors at all but its worth a try to see if its looking for a NPC with that name in a bugged file or w/e lol

**Comment by FePython** [comment]
alright so i tryed just making another npc new name, new location, new ID number and still it happens to those 3 NPC's here is a screen shot of what it looks like when there starting to bug out. they can also stop looking at you and prevent you from selecting them

<a href="http://tinypic.com?ref=142bszq" target="_blank"><img src="http://i39.tinypic.com/142bszq.png" border="0" alt="Image and video hosting by TinyPic"></a>

as you can see in this photo there are what looks like 2NPCs in the same place one with no name and will not move one with a name and looks at you. if i do /citizens clean the ghost one goes away, for now but it does come back. some times they ghost one is not there but the main one does not turn to look at you. also you cant select the NPC at all (on my server i have the selection item as a book) i can select any NPC but the 3 that act like this (side note in the photo thats Boff 1 of the NPC's that is being gliched and name2 the one with the new name, Id and location that i put in to see if that would fix anything, which it did not) id gladly give you the IP of my server if going in and looking at it your self helps. i did notest that 'sometimes' not always. if i stand stil (almost like AFK) for a min or two they will go away (to save on server ram??) when i move they will reapear and be there and working and no ghost but this only happens some times
