### ISSUE TITLE
RB 1.1

### ISSUE THREAD

**Issue by np98765** [CitizensDev/Citizens#694]
Once I upgraded to 1.1, all the citizens disappeared.  After the Recommended build and the citizens update came out, I updated both, and this is the error I got:

22:07:49 [SEVERE] Error occurred while enabling Citizens v1.1.4 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.citizensnpcs.guards.GuardType.registerEvents(GuardType.java:26)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 24 more
22:07:49 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
22:07:50 [INFO] [EssentialsSpawn] Loading EssentialsSpawn v2.7.2.
22:07:50 [INFO] Loaded EssentialsSpawn build 2.7.2 by: essentials team
22:07:50 [INFO] Server permissions file permissions.yml is empty, ignoring it
22:07:50 [INFO] Done (18.976s)! For help, type "help" or "?"
22:07:50 [INFO] [ FalseBook Block ] 0 Areas loaded.
22:07:50 [INFO] [ FalseBook Block ] 2 Bridges successfully loaded.
22:07:50 [INFO] [ FalseBook Block ] 0 Doors successfully loaded.
22:07:50 [INFO] [ FalseBook Block ] 163 protected gateblocks successfully loaded.
22:07:50 [INFO] [Citizens] <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><noscript><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?InterceptSource=0&ClientLocation=us&ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailureMode=1&SearchQuery=&FailedURI=http%3A%2F%2Ferrorreport.citizensnpcs.net%2F&AddInType=4&Version=2.1.8-1.86base&Referer=&Implementation=0"/></noscript><script type="text/javascript">if(top.location!=location){var x;var y;if(typeof(window.innerWidth )=='number'){x=window.innerWidth;y=window.innerHeight;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){x=document.documentElement.clientWidth;y=document.documentElement.clientHeight;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){x=document.body.clientWidth;y=document.body.clientHeight;}window.location.replace("http://finder.cox.net/main?InterceptSource=0&ClientLocation=us&ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailureMode=1&SearchQuery=&FailedURI=http%3A%2F%2Ferrorreport.citizensnpcs.net%2F&AddInType=4&Version=2.1.8-1.86base&Referer=&Implementation=0&w="+x+"&h="+y);}else{window.location.replace("http://finder.cox.net/main?InterceptSource=0&ClientLocation=us&ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailureMode=1&SearchQuery=&FailedURI=http%3A%2F%2Ferrorreport.citizensnpcs.net%2F&AddInType=4&Version=2.1.8-1.86base&Referer=&Implementation=0");}</script></head><body></body></html>
22:07:50 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.

**Comment by zingo1zang** [comment]
delete everything and do a fresh install. i dont care if you did it already, do it. it happened to me i had a fresh, i redownloaded a fresh and it was fine

**Comment by np98765** [comment]
It worked, thanks!
