### ISSUE TITLE
Error whilst starting Citizens

### ISSUE THREAD

**Issue by MadcowD** [CitizensDev/Citizens#7]
15:21:31 [SEVERE] Error occurred while enabling Citizens v1.1 (Is it up to date?): null
java.lang.ExceptionInInitializerError
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at java.lang.Class.getEnumConstantsShared(Unknown Source)
        at java.lang.System$2.getEnumConstantsShared(Unknown Source)
        at java.util.EnumMap.getKeyUniverse(Unknown Source)
        at java.util.EnumMap.<init>(Unknown Source)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.<clinit>(Unknown Source)
        at net.citizensnpcs.Citizens.onEnable(Unknown Source)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:885)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at net.citizensnpcs.SettingsManager.getBoolean(Unknown Source)
        at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<init>(Unknown Source)
        at net.citizensnpcs.resources.npclib.creatures.CreatureNPCType.<clinit>(Unknown Source)
        ... 20 more

**Comment by aPunch** [comment]
Known 1.0.9d bug, caused by single quotes in your config files. Delete you configs and let them regen OR remove all single quotes.
