### ISSUE TITLE
Waypoints Not Working

### ISSUE THREAD

**Issue by cryptodechange** [CitizensDev/Citizens#706]
So after reinstalling the plugin and so forth, I cannot for the life of me get waypoints to work. I notice this console message randomly popping up while I try and work it also.

There's also some weird behavior which involve NPCs appearing half in the ground when I start editing waypoints using /npc waypoints.

The error message:

19:08:50 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getPlayer()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
    at net.citizensnpcs.resources.npclib.PathNPC.handleMove(PathNPC.java:146)
    at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:213)
    at net.citizensnpcs.resources.npclib.HumanNPC.doTick(HumanNPC.java:84)
    at net.citizensnpcs.TickTask.run(TickTask.java:30)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by cryptodechange** [comment]
Though doing /npc copy fixes this.

**Comment by Oehkcfl** [comment]
The no such method error was solved for me by grabbing the CB 1.1r3 build.
