### ISSUE TITLE
NoSuchMethod Error

### ISSUE THREAD

**Issue by Oehkcfl** [CitizensDev/Citizens#709]
When an evil NPC attacks me, this pops into the log: ( I can reproduce this every time)

23:18:09 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getPlayer()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
        at net.citizensnpcs.resources.npclib.PathNPC.isHoldingBow(PathNPC.java:171)
        at net.citizensnpcs.resources.npclib.PathNPC.isWithinAttackRange(PathNPC.java:182)
        at net.citizensnpcs.resources.npclib.PathNPC.updateTarget(PathNPC.java:327)
        at net.citizensnpcs.resources.npclib.PathNPC.moveTick(PathNPC.java:206)
        at net.citizensnpcs.resources.npclib.creatures.CreatureNPC.doTick(CreatureNPC.java:39)
        at net.citizensnpcs.resources.npclib.creatures.EvilCreatureNPC.doTick(EvilCreatureNPC.java:50)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask$CreatureTick.run(CreatureTask.java:106)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by cryptodechange** [comment]
Me too (but with Guards/Bouncers), I believe this was caused by the recent Bukkit updates. I downgraded to the previous version and the errors were no longer present.

**Comment by Oehkcfl** [comment]
Noticed there were several very recent updates to CB rb. I will make sure I have the most recent, and see if this still exists.

**Comment by zackb1079** [comment]
I have also been getting this error as of the Bukkit update to 1.1 R2. If this could be fixed soon that would be great. Our server is just about ready to go live and citizens is the only plugin at the moment giving me an error, and I'd prefer to be safe rather than sorry. Thanks :)

EDIT: This also destroys my NPC Paths and I'm afraid to try and set them at the moment.

**Comment by ghost** [comment]
FOR R3...

Here is the fixed jar: http://cl.ly/DmYa

You can do this instead: 

`import org.bukkit.craftbukkit.entity.CraftPlayer;`
`public CraftPlayer getPlayer() {
        return (CraftPlayer) getBukkitEntity();
    }`

Edit: oops was beaten to by devs.

**Comment by Oehkcfl** [comment]
No need to. It seems that CB 1.1r3 fixed my issues with this. I will test pathing now and see where I'm at.
