### ISSUE TITLE
Error Making an NPC with 1.1.5

### ISSUE THREAD

**Issue by Phealoon** [CitizensDev/Citizens#725]
I got this error after installing and running a fresh new version:

2012-01-31 02:06:07 [INFO] [Citizens] Creating new config file at phealoon.yml.
2012-01-31 02:06:24 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:177)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-01-31 02:06:24 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-01-31 02:06:24 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-01-31 02:06:24 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-01-31 02:06:24 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-01-31 02:06:24 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:193)
2012-01-31 02:06:24 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-01-31 02:06:24 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-01-31 02:06:24 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
2012-01-31 02:06:24 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:178)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-01-31 02:06:24 [SEVERE]    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:587)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-01-31 02:06:24 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-01-31 02:06:25 [WARNING] Task of 'OKChat' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:15)
    at org.bukkit.craftbukkit.CraftWorld.getPlayers(CraftWorld.java:565)
    at net.kalmanolah.okchat.OKFunctions.parseCommonVariables(OKFunctions.java:109)
    at net.kalmanolah.okchat.OKPlayerList.formatPlayerListPlayer(OKPlayerList.java:24)
    at net.kalmanolah.okchat.OKPlayerList$1.run(OKPlayerList.java:47)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:502)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

-Phea

**Comment by Nihilhalla** [comment]
I am having a similar issue, only with my server log, it would appear that citizens is also causing other plugins to crash...

**Comment by CallMeJinx** [comment]
Same thing. Also closes other plugins and eventually crashing the server :/

**Comment by Nihilhalla** [comment]
after doing some research it appears that this bug showed up during the 1.1 r2 bukkit update, i'd love to see what this issue is being caused by, my best guess is that when bukkit changed all of its events around in the 1.1 update that one of the event hooks got broken, although this makes little sense because citizens 1.1.4 worked just fine with RB1.1R1 and i downloaded RB1.1R3 at the same time i downloaded 1.1.5 and citizens crashed all the things.

Edit: i should add that i do not get this error, until i make an npc, if my npc profiles.yml is empty i do not get the error, if all lines are commented out i get no error, until i attempt to make an npc, or have an npc in the npc-profiles.yml i get no error from citizens

**Comment by Phealoon** [comment]
@ Rainmakerx

Do you have spout on your server. I discovered that another bug that makes the NPC's un-clickable after I die was caused from spout. I wonder if there is a conflict there?

-Phea

**Comment by Nihilhalla** [comment]
I do have spout, but prior to RB1.1R3 and 1.1.5 citizens my npcs worked more or less fine except for guards which seemed to do nothing at all, i did on occasion have to use /citizens clean to clear some ghosted npc copies allowing me to access my npcs again, but other than that it was smooth

**Comment by Nihilhalla** [comment]
Ok, so i was derping pretty hard it seems, the wrapper that was controlling the server was still set to launch the old jar for R1, testing new R3 jar now,

**Comment by Nihilhalla** [comment]
Tested R3 Jar, turns out that was the issue, so make sure you are using the RB1.1-R3 craftbukkit jar with the 1.1.5 jar for citizens, and everything should be fine. Note that i say "should".

**Comment by fullwall** [comment]
Bukkit mismatch.
