### ISSUE TITLE
Can't find the reason why :(

### ISSUE THREAD

**Issue by johan-bjareholt** [CitizensDev/Citizens#733]
I have been having problems with Citizens the latest week.

My terminal says this at startup:

17:37:35 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1556
17:37:35 [SEVERE]   at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
17:37:35 [SEVERE]   at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
17:37:35 [SEVERE]   at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
17:37:35 [SEVERE]   at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:37)
17:37:35 [SEVERE]   at net.citizensnpcs.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:30)
17:37:35 [SEVERE]   at net.citizensnpcs.questers.data.QuestProperties.<clinit>(QuestProperties.java:9)
17:37:35 [SEVERE]   at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:32)
17:37:35 [SEVERE]   at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
17:37:35 [SEVERE]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
17:37:35 [SEVERE]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
17:37:35 [SEVERE]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
17:37:35 [SEVERE]   at org.bukkit.Bukkit.reload(Bukkit.java:188)
17:37:35 [SEVERE]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
17:37:35 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
17:37:35 [SEVERE]   at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
17:37:35 [SEVERE]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
17:37:35 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
17:37:35 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
17:37:35 [SEVERE] Caused by: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1556
17:37:35 [SEVERE]   at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
17:37:35 [SEVERE]   at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
17:37:35 [SEVERE]   at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
17:37:35 [SEVERE]   at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
17:37:35 [SEVERE]   ... 22 more
17:37:35 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1556
17:37:35 [SEVERE]   at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
17:37:35 [SEVERE]   at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
17:37:35 [SEVERE]   at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
17:37:35 [SEVERE]   at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:37)
17:37:35 [SEVERE]   at net.citizensnpcs.questers.data.QuestProperties.initialize(QuestProperties.java:13)
17:37:35 [SEVERE]   at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:32)
17:37:35 [SEVERE]   at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
17:37:35 [SEVERE]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
17:37:35 [SEVERE]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
17:37:35 [SEVERE]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
17:37:35 [SEVERE]   at org.bukkit.Bukkit.reload(Bukkit.java:188)
17:37:35 [SEVERE]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
17:37:35 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
17:37:35 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
17:37:35 [SEVERE]   at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
17:37:35 [SEVERE]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
17:37:35 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
17:37:35 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
17:37:35 [SEVERE] Caused by: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 1556
17:37:35 [SEVERE]   at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
17:37:35 [SEVERE]   at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
17:37:35 [SEVERE]   at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
17:37:35 [SEVERE]   at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
17:37:35 [SEVERE]   ... 21 more
17:37:35 [SEVERE] Error occurred while enabling Citizens v1.1.5 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:34)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
    at org.bukkit.Bukkit.reload(Bukkit.java:188)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 28 more
17:37:35 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...

It says string error and configurationexeption: unacceptable character so i guess it's my config it's something wrong with, but removed it and downloaded a new one.
Still didn't work

Is it possible that the quester config can give string errors? Sounds stupid that the whole plugin should turn off if that's the problem

**Comment by kripts** [comment]
Copy each of your configs and paste one by one into this:
http://yaml-online-parser.appspot.com/
If there is a problem with the config it will show you to the right.

**Comment by johan-bjareholt** [comment]
Thanks for the help :)

**Comment by kripts** [comment]
Working now?
