### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Boastful1353** [CitizensDev/Citizens#740]
2012-02-02 08:26:37 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:177)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-02-02 08:26:37 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-02-02 08:26:37 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-02-02 08:26:37 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-02-02 08:26:37 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-02-02 08:26:37 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:193)
2012-02-02 08:26:37 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-02-02 08:26:37 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-02-02 08:26:37 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-02-02 08:26:37 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Boastful1353** [comment]
2012-02-02 08:26:18 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:264)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:127)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:502)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by ghost** [comment]
I fixed this issue in this binary of Citizens: http://cl.ly/DmYa

**Comment by Nihilhalla** [comment]
make sure you are using the R3 Craftbukkit jar, as reverse compatibility was removed in citizens 1.1.5

**Comment by Boastful1353** [comment]
by the way is there a way to make the npc talk when you walk near it?

**Comment by ghost** [comment]
Please close this issue.

**Comment by Boastful1353** [comment]
answer my question good sir and i will be happy to.

**Comment by Boastful1353** [comment]
or dont >.>
