### ISSUE TITLE
Severe error at startup-  java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by quickclay** [CitizensDev/Citizens#741]
I am seeing this error on startup with 1.1.5. CB 1818. 
2012-02-02 07:11:32 [SEVERE] Error occurred while enabling Citizens v1.1.5 (Is it up to date?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.citizensnpcs.healers.HealerType.registerEvents(HealerType.java:27)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.CitizensListener
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 24 more
2012-02-02 07:11:33 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2012-02-02 07:11:33 [INFO] [Citizens] An error occurred whilst sending your error report.
2012-02-02 07:11:33 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.

**Comment by ghost** [comment]
Makes no sense... It's saying that CitizensListener isn't in the binary... 

Edit: You need to use a pervious version of Citizens that works with 1.1-R1. (assuming you're using this build: http://ci.bukkit.org/job/dev-CraftBukkit/1818/)

This repository is meant to update to the newest builds and not usually for the recommended builds.

Edit2: This version will work for CB 1818: http://dev.bukkit.org/server-mods/citizens/files/10-1-1-4/

**Comment by quickclay** [comment]
Thank you!

**Comment by ghost** [comment]
Please close this issue.
