### ISSUE TITLE
Trader makes spout client crash

### ISSUE THREAD

**Issue by Snaipe** [CitizensDev/Citizens#75]
With spoutcraft client, If, as an owner of a trader, you try to open the NPC's inventory, the game crashes and throw this in the client console :
java.lang.NullPointerException
        at ds.a(RenderPlayer.java:168)
        at ds.b(RenderPlayer.java:333)
        at gv.a(RenderLiving.java:74)
        at ds.a(RenderPlayer.java:70)
        at ds.a(RenderPlayer.java:357)
        at th.a(SourceFile:141)
        at th.a(SourceFile:135)
        at n.a(RenderGlobal.java:413)
        at px.a(EntityRenderer.java:646)
        at px.b(EntityRenderer.java:476)
        at net.minecraft.client.Minecraft.run(Minecraft.java:654)
        at java.lang.Thread.run(Unknown Source)

Don't know If I have to report this to Citizens or Spout, though.

**Comment by Snaipe** [comment]
Also, when opening the NPC's inventory with the normal client, the first item is an 'undefined item' with fire texture. It makes the game crash if I pick it up.

Edit : damn this "comment and close" button in github :/

**Comment by fullwall** [comment]
This should be reported to Spout.

**Comment by Snaipe** [comment]
It seems that it is an invalid item that makes the client crash.

While spoutcraft crashes when I click on the NPC, the vanilla client crashes as well when I click on the invalid item ( which looks like fire )
