### ISSUE TITLE
/suicide causing problems with citizens + essentials + spout

### ISSUE THREAD

**Issue by DreamPhreak** [CitizensDev/Citizens#756]
Usually i can read this and figure out the problem, but since it mentions citizens, essentials, and spout, because of a suicide command, that is just baffling:

08:43:46 [INFO] [PLAYER_COMMAND] duffysteel: /suicide
08:43:46 [SEVERE] Could not pass event org.bukkit.event.entity.EntityDamageEvent to Citizens
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:453)
        at com.earth2me.essentials.commands.Commandsuicide.run(Commandsuicide.java:20)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:97)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:340)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:267)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:176)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:552)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1024)
        ... 21 more
Caused by: java.lang.ClassCastException: com.earth2me.essentials.User cannot be cast to org.bukkit.craftbukkit.entity.CraftEntity
        at net.citizensnpcs.resources.npclib.NPCList.getNPC(NPCList.java:19)
        at net.citizensnpcs.resources.npclib.NPCManager.get(NPCManager.java:31)
        at net.citizensnpcs.listeners.EntityListen.onEntityDamage(EntityListen.java:29)
        ... 25 more
08:43:46 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
08:43:46 [INFO] [Citizens] An error occurred whilst sending your error report.
08:43:46 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been incl                                                                   uded other than Citizens version information.

On one suicide attempt (lol), a different person then complained of lag right after, and because of that, i thought i would need to find out if this is a problem on my end or not, to prevent any lag from occurring in the future, or if its just a bug with citizens; and also mainly because it said it failed when sending the error report, which should also be fixed...

Plus everything was updated recently to bukkit 1.1-R3 (1846) and associated plugins for that version, so i think this might be more of an essentials problem, despite being a citizens error, hmm but then that could mean that citizens is incompatible with something from essentials?

**Comment by JaredTS486** [comment]
I have this issue as well, if you can even call it that. No one can /suicide on my server. So its out of my scope, however i do have the same issue.
