### ISSUE TITLE
CitizensListener NoClassDefFoundError

### ISSUE THREAD

**Issue by freedomfry** [CitizensDev/Citizens#757]
I upgraded bukkit & citizens but something is wrong. See server log below. I ran all my YML configs through the parser and they are all fine.
J

14:04:46 [INFO] Starting minecraft server version 1.1
14:04:46 [INFO] Loading properties
14:04:46 [INFO] Starting Minecraft server on *:25565
14:04:47 [INFO] This server is running CraftBukkit version git-Bukkit-1.1-R3-b18
46jnks (MC: 1.1) (Implementing API version 1.1-R3)
14:04:47 [INFO] [Spout] Loading Spout v721.
14:04:47 [INFO] [Spout] Spout 721 has been initialized
14:04:47 [INFO] Preparing level "SoOriginal"
14:04:47 [INFO] Default game type: 0
14:04:47 [INFO] Preparing start region for level 0 (Seed: -4407435717910576537)
14:04:48 [INFO] Preparing start region for level 1 (Seed: 2132820239645546532)
14:04:48 [INFO] Preparing spawn area: 77%
14:04:48 [INFO] Preparing start region for level 2 (Seed: 2132820239645546532)
14:04:48 [INFO] [ChairCraft] Loading ChairCraft v1.2.6.
14:04:48 [INFO] ChairCraft 1.2.6 is enabled.
14:04:48 [INFO] [WorldEdit] Loading WorldEdit v5.1.1.
14:04:49 [INFO] WorldEdit 5.1.1 enabled.
14:04:49 [INFO] WEPIF: Using the Bukkit Permissions API.
14:04:49 [INFO] WEPIF: Using the Bukkit Permissions API.
14:04:49 [INFO] [RealShop2] Loading RealShop2 v2.16.
14:04:49 [INFO] You can create plugins\RealShop2/en.lang.txt to change texts
14:04:49 [INFO] [RealShop2] version [2.16]([tickleman]) loaded
14:04:49 [INFO] [iConomy] Loading iConomy v6.0.8b.
14:04:49 [INFO] [iConomy] Database Error: java.sql.SQLException: No suitable dri
ver found for jdbc:mysql:\localhost:3306\iConomy
14:04:49 [INFO] [iConomy - Celty] Enabled (36 ms)
14:04:49 [INFO] [BookWorm] Loading BookWorm v1.8.2.
14:04:49 [INFO] BookWorm 'Spout' support enabled.
14:04:49 [INFO] BookWorm v1.8.2 loaded!
14:04:49 [INFO] [Citizens] Loading Citizens v1.1.5.
14:04:49 [INFO] [Citizens] Failed to load Citizens.jar. Does the .jar file conta
in a npctype.info file?
14:04:49 [INFO] [Citizens] NPC types loaded: blacksmith, blacksmith, guard, guar
d, healer, healer, quester, quester, trader, trader, wizard
14:04:49 [SEVERE] Error occurred while enabling Citizens v1.1.5 (Is it up to dat
e?): net/citizensnpcs/api/event/CitizensListener
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/CitizensListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.citizensnpcs.guards.GuardType.registerEvents(GuardType.java:26)
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:85)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:1057)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:379)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174
)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.Citizens
Listener
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 24 more
14:04:49 [INFO] [Citizens] An error has occurred, please wait while it is sent t
o the developers...
14:04:49 [INFO] Server permissions file permissions.yml is empty, ignoring it
14:04:49 [INFO] Done (2.602s)! For help, type "help" or "?"
14:04:50 [INFO] [Citizens] An error occurred whilst sending your error report.
14:04:50 [INFO] [Citizens] Below is the stacktrace that has been transmitted to
the developers, no other information has been included other than Citizens versi
on information.

**Comment by JaredTS486** [comment]
Make sure you are updating to 1.1.5 correctly. Replace all of your NPC files as well as the jar file. If it still fails take ALL of your plugins out and ONLY put the citizens.jar file in. You can assume two things, its incompatible with another plugin. OR it is having issues with the older config files, so you will need to regenerate them. Try to figure out which one it is.
