### ISSUE TITLE
Several Errors...

### ISSUE THREAD

**Issue by bigboy2013** [CitizensDev/Citizens#758]
When I try using citizens, I get these errors:

05.02 00:56:45 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:942)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.EntityHuman.attack(EntityHuman.java:797)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:213)
05.02 00:56:45 [Server] INFO    at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
05.02 00:56:45 [Server] INFO    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:15)
05.02 00:56:45 [Server] INFO    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
05.02 00:56:45 [Server] INFO java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;

Any ideas?

**Comment by JaredTS486** [comment]
Make sure you have updated to the R3 1.1 CraftBukkit. Also make sure if you updated citizens that you replace all of the NPC files. It helps to remove the old citizens folder and then place the latest jar file in the plugins and run it, that way it generates them for you.
