### ISSUE TITLE
Evil Npc's are rendered useless

### ISSUE THREAD

**Issue by ryanjjjj** [CitizensDev/Citizens#759]
I have configured evil NPC's to work and by what i read, they should be working.

However, this is not the case as the NPC will spawn, stare blankly at the air and do nothing.  I will hit him and this does nothing, i even offered him cake! no avail (he has to be broken, who doesn't except cake!?!?!)

the console error is:

20:13:44 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkit
Entity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
        at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.j
ava:70)
        at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:13
0)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.spawnCreatur
e(CreatureTask.java:51)
        at net.citizensnpcs.resources.npclib.creatures.CreatureTask.run(Creature
Task.java:40)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:137)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:502)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
20:13:46 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib
.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
20:13:46 [SEVERE]       at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitE
ntity(CraftNPC.java:70)
20:13:46 [SEVERE]       at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitE
ntity(CraftNPC.java:15)
20:13:46 [SEVERE]       at org.bukkit.craftbukkit.CraftWorld.getEntities(CraftWo
rld.java:503)
20:13:46 [SEVERE]       at org.getspout.spout.player.SimplePlayerManager.getEnti
ty(SimplePlayerManager.java:151)
20:13:46 [SEVERE]       at org.getspout.spoutapi.SpoutManager.getEntityFromId(Sp
outManager.java:275)
20:13:46 [SEVERE]       at org.getspout.spoutapi.packet.PacketEntityInformation.
run(PacketEntityInformation.java:74)
20:13:46 [SEVERE]       at org.getspout.spout.packet.CustomPacket.handle(CustomP
acket.java:125)
20:13:46 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
20:13:46 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:100)
20:13:46 [SEVERE]       at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetSe
rverHandler.java:587)
20:13:46 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(NetworkLis
tenThread.java:78)
20:13:46 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServe
r.java:536)
20:13:46 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:434)
20:13:46 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:465)
20:13:46 [SEVERE] Unexpected exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkit
Entity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
        at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.j
ava:70)
        at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.j
ava:15)
        at org.bukkit.craftbukkit.CraftWorld.getEntities(CraftWorld.java:503)
        at org.getspout.spout.player.SimplePlayerManager.getEntity(SimplePlayerM
anager.java:151)
        at org.getspout.spoutapi.SpoutManager.getEntityFromId(SpoutManager.java:
275)
        at org.getspout.spoutapi.packet.PacketEntityInformation.run(PacketEntity
Information.java:74)
        at org.getspout.spout.packet.CustomPacket.handle(CustomPacket.java:125)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
:587)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:7
8)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

A fix would be greatly appreciated.

Bukkit 1.1R3
citizens 1.1.5

**Comment by Nihilhalla** [comment]
are you using a remote toolkit? if so make sure the toolkit is pointed at the R3 jar, then try restarting your server entirely, otherwise i have no clue

**Comment by ryanjjjj** [comment]
no, i run my server locally with no remote control, like i said in my post the plugin should be functioning normally.  I have a feeling the source code broke again, the dev should take it out of the core and make it a separate .jar for easier updating...
