### ISSUE TITLE
Citizens Error

### ISSUE THREAD

**Issue by catsfuzz** [CitizensDev/Citizens#763]
Alright, first off, only one of the NPC's ever created on my server are there after I updated to v1.1.5. The others aren't.

Also, 

java.lang.NoSuchMehtodError: net.citizensnpcs.resources.npclip.PathNPC.GetBukkitEntry()Lorg/bukkit/craftbukkit/entity/CraftPlayer;

Another problem, you can't even select the NPC that is in existence.
I get either that, or a server crash when I try to make an NPC

**Comment by catsfuzz** [comment]
Here is a more detailed report of the incident.

05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
05.02 08:24:13 [Server] SEVERE  at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
05.02 08:24:13 [Server] SEVERE  at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:457)
05.02 08:24:13 [Server] SEVERE  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
05.02 08:24:13 [Server] SEVERE  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.Citizens.onCommand(Citizens.java:193)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
05.02 08:24:13 [Server] SEVERE  at java.lang.reflect.Method.invoke(Method.java:601)
05.02 08:24:13 [Server] SEVERE  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05.02 08:24:13 [Server] SEVERE  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
05.02 08:24:13 [Server] SEVERE  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:177)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
05.02 08:24:13 [Server] SEVERE  at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
05.02 08:24:13 [Server] SEVERE java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;

**Comment by catsfuzz** [comment]
Randomly fixed... awesome.
