### ISSUE TITLE
Console errors that started happening

### ISSUE THREAD

**Issue by vince20100** [CitizensDev/Citizens#766]
Hey all, I updated citizens 2 days ago and it was working fine. Then this morning this started happening.

05.02 17:19:43 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
05.02 17:19:43 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
05.02 17:19:43 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:502)
05.02 17:19:43 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.Citizens$2.run(Citizens.java:127)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:264)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
05.02 17:19:43 [Server] INFO    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
05.02 17:19:43 [Server] INFO java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
05.02 17:19:43 [Server] WARNING Task of 'Citizens' generated an exception

**Comment by catsfuzz** [comment]
05.02 17:19:43 [Server] INFO java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;

Getting the same issue! All but one of my NPC's are gone too, and I can't make any more! Someone really needs to help! D:

**Comment by JaredTS486** [comment]
I was getting this error too, MAKE SURE you have updated to the craft bukkit 1.1 revision 3 or 4 version. Then when you update citizens make sure you REPLACE all of the NPC files and the citizens.jar file. Im running citizens fine after those steps.

**Comment by catsfuzz** [comment]
I didn't do anything different, but today it just started working again... I don't know why.
