### ISSUE TITLE
citizens not working with xgate :(

### ISSUE THREAD

**Issue by pixelbat** [CitizensDev/Citizens#776]
A fresh install of Citizens to our server that has over 100 Xcraftgate warps and portals made seemed to be ok, that was until we created our first NPC. Then Xcraftgate stopped working and the console was flooded with errors.

Here is the initial error...

23:19:24 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib
.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
23:19:24 [SEVERE]       at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitE
ntity(CraftNPC.java:70)
23:19:24 [SEVERE]       at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(
HumanNPC.java:130)
23:19:24 [SEVERE]       at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(H
umanNPC.java:146)
23:19:24 [SEVERE]       at net.citizensnpcs.properties.properties.BasicPropertie
s.loadState(BasicProperties.java:321)
23:19:24 [SEVERE]       at net.citizensnpcs.properties.PropertyManager.load(Prop
ertyManager.java:46)
23:19:24 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register
(NPCManager.java:161)
23:19:24 [SEVERE]       at net.citizensnpcs.resources.npclib.NPCManager.register
(NPCManager.java:177)
23:19:24 [SEVERE]       at net.citizensnpcs.commands.BasicCommands.create(BasicC
ommands.java:226)
23:19:24 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
23:19:24 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
23:19:24 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
23:19:24 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
23:19:24 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
uteMethod(CommandsManager.java:530)
23:19:24 [SEVERE]       at net.citizensnpcs.resources.sk89q.CommandsManager.exec
ute(CommandsManager.java:407)
23:19:24 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:193
)
23:19:24 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:40)
23:19:24 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:168)
23:19:24 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(Cr
aftServer.java:386)
23:19:24 [SEVERE]       at net.minecraft.server.NetServerHandler.handleCommand(N
etServerHandler.java:777)
23:19:24 [SEVERE]       at net.minecraft.server.NetServerHandler.chat(NetServerH
andler.java:737)
23:19:24 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:725)
23:19:24 [SEVERE]       at net.minecraft.server.Packet3Chat.handle(Packet3Chat.j
ava:33)
23:19:24 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.
java:226)
23:19:24 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHand
ler.java:100)
23:19:24 [SEVERE]       at net.minecraft.server.NetworkListenThread.a(NetworkLis
tenThread.java:78)
23:19:24 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServe
r.java:536)
23:19:24 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:434)
23:19:24 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(Sour
ceFile:465)

Then followed by errors like this over and over and over... 

23:12:40 [SEVERE] Could not pass event org.bukkit.event.entity.CreatureSpawnEven
t to XcraftGate
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkit
Entity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
        at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.j
ava:70)
        at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.j
ava:15)
        at org.bukkit.craftbukkit.CraftWorld.getLivingEntities(CraftWorld.java:5
21)
        at de.xcraft.engelier.XcraftGate.DataWorld.checkCreatureLimit(DataWorld.
java:196)
        at de.xcraft.engelier.XcraftGate.ListenerCreature.onCreatureSpawn(Listen
erCreature.java:15)
        at org.bukkit.plugin.java.JavaPluginLoader$75.execute(JavaPluginLoader.j
ava:792)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:57)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:453)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callCreatureSpawnEvent
(CraftEventFactory.java:286)
        at net.minecraft.server.World.addEntity(World.java:886)
        at net.minecraft.server.SpawnerCreature.spawnEntities(SpawnerCreature.ja
va:154)
        at net.minecraft.server.World.doTick(World.java:1724)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:523)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

I don't know which is at fault, Citizens, or Xcraftgate, or something totally different. I think Xcraftgate has been abandoned since it hasn't been updated in a long time, but it still works, and we rely heavily on it. I hope there is some work around available here, because we really want to incorporate Citizens too. Any idea what's up?

Also using CB 1.1-RB1, I'll go ahead and try RB3 to see if that helps, but I kinda think it won't. Thank you for reading.

**Comment by pixelbat** [comment]
Ok, I feel stupid for making this ticket. RB3 DID fix it. Sorry for this!
