### ISSUE TITLE
[WARNING] Task of 'Citizens' generated an exception

### ISSUE THREAD

**Issue by IsExtant** [CitizensDev/Citizens#780]
18:06:56 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:264)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:62)
    at net.citizensnpcs.Citizens$2.run(Citizens.java:127)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:502)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

NPC's are frozen and server stops
So yeah I have no idea what to do with this so I think I'll leave it here...

**Comment by fullwall** [comment]
Bukkit version mismatch.
