### ISSUE TITLE
NPC Type

### ISSUE THREAD

**Issue by cat24max** [CitizensDev/Citizens#793]
16:47:06 [INFO] [Citizens] Loading Citizens v1.1.4.
16:47:06 [SEVERE] java.util.zip.ZipException: error in opening zip file
16:47:06 [SEVERE]       at java.util.zip.ZipFile.open(Native Method)
16:47:06 [SEVERE]       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:150)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:114)
16:47:06 [SEVERE]       at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:282)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
16:47:06 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
16:47:06 [SEVERE]       at org.bukkit.Bukkit.reload(Bukkit.java:188)
16:47:06 [SEVERE]       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
16:47:06 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
16:47:06 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
16:47:06 [SEVERE] java.util.zip.ZipException: error in opening zip file
16:47:06 [SEVERE]       at java.util.zip.ZipFile.open(Native Method)
16:47:06 [SEVERE]       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:150)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:114)
16:47:06 [SEVERE]       at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:282)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
16:47:06 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
16:47:06 [SEVERE]       at org.bukkit.Bukkit.reload(Bukkit.java:188)
16:47:06 [SEVERE]       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
16:47:06 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
16:47:06 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
16:47:06 [SEVERE] java.util.zip.ZipException: error in opening zip file
16:47:06 [SEVERE]       at java.util.zip.ZipFile.open(Native Method)
16:47:06 [SEVERE]       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:150)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:114)
16:47:06 [SEVERE]       at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:282)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
16:47:06 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
16:47:06 [SEVERE]       at org.bukkit.Bukkit.reload(Bukkit.java:188)
16:47:06 [SEVERE]       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
16:47:06 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
16:47:06 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
16:47:06 [SEVERE] java.util.zip.ZipException: error in opening zip file
16:47:06 [SEVERE]       at java.util.zip.ZipFile.open(Native Method)
16:47:06 [SEVERE]       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:150)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:114)
16:47:06 [SEVERE]       at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:282)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
16:47:06 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
16:47:06 [SEVERE]       at org.bukkit.Bukkit.reload(Bukkit.java:188)
16:47:06 [SEVERE]       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
16:47:06 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
16:47:06 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
16:47:06 [SEVERE] java.util.zip.ZipException: error in opening zip file
16:47:06 [SEVERE]       at java.util.zip.ZipFile.open(Native Method)
16:47:06 [SEVERE]       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:150)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:114)
16:47:06 [SEVERE]       at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:282)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
16:47:06 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
16:47:06 [SEVERE]       at org.bukkit.Bukkit.reload(Bukkit.java:188)
16:47:06 [SEVERE]       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
16:47:06 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
16:47:06 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:47:06 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
16:47:06 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
16:47:06 [SEVERE] java.util.zip.ZipException: error in opening zip file
16:47:06 [SEVERE]       at java.util.zip.ZipFile.open(Native Method)
16:47:06 [SEVERE]       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:150)
16:47:06 [SEVERE]       at java.util.jar.JarFile.<init>(JarFile.java:114)
16:47:06 [SEVERE]       at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:19)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:282)
16:47:06 [SEVERE]       at net.citizensnpcs.Citizens.onEnable(Citizens.java:75)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
16:47:06 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
16:47:07 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
16:47:07 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
16:47:07 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
16:47:07 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:444)
16:47:07 [SEVERE]       at org.bukkit.Bukkit.reload(Bukkit.java:188)
16:47:07 [SEVERE]       at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
16:47:07 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
16:47:07 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
16:47:07 [SEVERE]       at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
16:47:07 [SEVERE]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
16:47:07 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
16:47:07 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
16:47:07 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
16:47:07 [INFO] [Citizens] No NPC types loaded.
16:47:07 [INFO] [Citizens] Permissions system found (GroupManager v1.6 (Phoenix))
16:47:07 [INFO] [Citizens] version [1.1.4] loaded.
16:47:07 [INFO] [Citizens] Economy plugin found (iConomy v6)

**Comment by Loserman778** [comment]
What do you expect?? You say nothing except "Npc Type" And post an error..... Maybe tell us what you did before this? Etc.
