### ISSUE TITLE
ERROR when creating an npc, server crashes

### ISSUE THREAD

**Issue by Macfan1** [CitizensDev/Citizens#796]
Error when creating a npc, server then crashes
Thanks for any help, I want to make a roleplay server, but can't do it without this. Thanks

```
at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:942)
at net.minecraft.server.EntityHuman.attack(EntityHuman.java:797)
at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:213)
at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:15)
at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
```

java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
2012-02-11 02:53:27 [SEVERE] Unexpected exception
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:942)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.EntityHuman.attack(EntityHuman.java:797)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:213)
2012-02-11 02:53:27 [SEVERE]    at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
2012-02-11 02:53:27 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:15)
2012-02-11 02:53:27 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
2012-02-11 02:53:27 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
2012-02-11 02:53:17 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
2012-02-11 02:53:17 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
2012-02-11 02:53:17 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-02-11 02:53:17 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:193)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-02-11 02:53:17 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-02-11 02:53:17 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-02-11 02:53:17 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-02-11 02:53:17 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:177)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
2012-02-11 02:53:17 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
2012-02-11 02:53:17 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;

**Comment by fullwall** [comment]
CraftBukkit version mismatch.
