### ISSUE TITLE
Error whilst logging in with citizens.

### ISSUE THREAD

**Issue by MadcowD** [CitizensDev/Citizens#8]
15:25:21 [SEVERE] Could not pass event PLAYER_LOGIN to Citizens
java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.resources.npclib.creatures.Creatur
eTask
        at net.citizensnpcs.listeners.PlayerListen.onPlayerLogin(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$13.execute(JavaPluginLoader.java:328)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at net.minecraft.server.ServerConfigurationManager.a(ServerConfigurationManager.java:184)
        at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:82)
        at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:33)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:91)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

on bukkit 1060 with spout devbuild 167

**Comment by aPunch** [comment]
Read known bugs section on the forum thread before reporting an error, please.
