### ISSUE TITLE
Bug on creating NPC

### ISSUE THREAD

**Issue by staticjelly** [CitizensDev/Citizens#808]
2012-02-12 22:40:04 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:177)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)

2012-02-12 22:40:04 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2012-02-12 22:40:04 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

2012-02-12 22:40:04 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2012-02-12 22:40:04 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)

2012-02-12 22:40:04 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:220)

2012-02-12 22:40:04 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

2012-02-12 22:40:04 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)

2012-02-12 22:40:04 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)

2012-02-12 22:40:04 [SEVERE]    at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:101)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)

2012-02-12 22:40:04 [SEVERE]    at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:44)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)

2012-02-12 22:40:04 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by spiritbolt** [comment]
im having the exact same issue i dont understand

**Comment by staticjelly** [comment]
Am I ever going to get any help?

**Comment by fakulatus** [comment]
Hellow,
same isue.
I have only Citizens installed, nothing else

2012-02-15 19:40:51 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.resources.npclib.PathNPC.getBukkitEntity()Lorg/bukkit/craftbukkit/entity/CraftPlayer;
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.npclib.CraftNPC.getBukkitEntity(CraftNPC.java:70)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getPlayer(HumanNPC.java:130)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.npclib.HumanNPC.getWorld(HumanNPC.java:146)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.properties.properties.BasicProperties.loadState(BasicProperties.java:321)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:161)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:177)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:226)
2012-02-15 19:40:51 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-02-15 19:40:51 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-02-15 19:40:51 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-02-15 19:40:51 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-02-15 19:40:51 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:220)
2012-02-15 19:40:51 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-02-15 19:40:51 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-02-15 19:40:51 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:536)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
2012-02-15 19:40:51 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by fakulatus** [comment]
Found the problem!

Outdated bukkit! Try the new craftbukkit-Verison (R4 atm)

**Comment by staticjelly** [comment]
Holy cow. :/ 
thank you!
