### ISSUE TITLE
Errors again!

### ISSUE THREAD

**Issue by bigboy2013** [CitizensDev/Citizens#809]
For some reason citizens was working fine for awhile. Then randomly it crashed, and we got several errors:

13.02 07:30:48 [Server] INFO [PLAYER_COMMAND] beastley1221: /home  
13.02 07:30:47 [Server] INFO [PLAYER_COMMAND] craftmattix: /home  
13.02 07:30:40 [Server] WARNING Can't keep up! Did the system time change, or is the server overloaded?
13.02 07:29:32 [Server] INFO [PLAYER_COMMAND] beastley1221: /home  
13.02 07:29:00 [Multicraft] Player 97172 not online for task Spam
13.02 07:28:07 [Server] INFO [Quarantine] Finished checking mobs.
13.02 07:28:06 [Server] INFO /50.23.30.168:36110 lost connection
13.02 07:27:52 [Multicraft] HippieBeak ran command Message of the Day
13.02 07:27:52 [Connect] User HippieBeak, IP 69.116.46.216
13.02 07:27:41 [Server] INFO Connection reset
13.02 07:27:41 [Disconnect] User HippieBeak has disconnected, reason: disconnect.quitting
13.02 07:26:32 [Server] INFO [PLAYER_COMMAND] bigboy2013: /spawnmob zombie 5 
13.02 07:26:09 [Server] INFO [PLAYER_COMMAND] craftmattix: /home  
13.02 07:25:09 [Server] INFO [PLAYER_COMMAND] beastley1221: /home  
13.02 07:24:49 [Server] INFO Fetching addPacket for removed entity: CraftPlayer{name=fighter}
13.02 07:24:48 [Server] INFO Fetching addPacket for removed entity: CraftPlayer{name=fighter}
13.02 07:24:48 [Server] INFO Fetching addPacket for removed entity: CraftPlayer{name=fighter}
13.02 07:24:47 [Server] INFO Fetching addPacket for removed entity: CraftPlayer{name=fighter}
13.02 07:24:47 [Server] INFO Fetching addPacket for removed entity: CraftPlayer{name=fighter}
13.02 07:24:36 [Server] INFO [PLAYER_COMMAND] beastley1221: /home  
13.02 07:23:33 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
13.02 07:23:33 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
13.02 07:23:33 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
13.02 07:23:33 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.flags.FlagSorter.transformToLiving(FlagSorter.java:205)
13.02 07:23:33 [Server] INFO    at com.google.common.collect.Iterables.filter(Iterables.java:579)
13.02 07:23:33 [Server] INFO java.lang.NoClassDefFoundError: com/google/common/collect/Iterables$6
13.02 07:23:33 [Server] WARNING Task of 'Citizens' generated an exception
13.02 07:23:33 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
13.02 07:23:33 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
13.02 07:23:33 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
13.02 07:23:33 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
13.02 07:23:33 [Server] INFO    at net.citizensnpcs.guards.flags.FlagSorter.transformToLiving(FlagSorter.java:205)
13.02 07:23:33 [Server] INFO    at com.google.common.collect.Iterables.filter(Iterables.java:579)
13.02 07:23:33 [Server] INFO java.lang.NoClassDefFoundError: com/google/common/collect/Iterables$6

ALSO we have craftbukkit 1.1 R3 and the citizens to go with it. And yet we have these problems. Everything with them seem to work, however bouncer guards wont attack mobs near them when we add the mobs flag, turn on aggro, and add a radius. They just stand in place and dont move at all. Any ideas????

**Comment by bigboy2013** [comment]
Oh one more thing. This happened using the Guard.jar in the citizens.zip folder, and trying to use the Dev Guard.jar in wiki page. Somehow bodyguards still work fine, and will attack and pursue players who attack them.
