### ISSUE TITLE
[SEVERE] Could not pass event PLUGIN_ENABLE to Citizens (6times)

### ISSUE THREAD

**Issue by FlamingArmor** [CitizensDev/Citizens#81]
Problems:
-Cant use iConomy (With citizens)
-Cant Change NPC type
-All known bugs are happening =P
-Big errors in the Console

Thing's that work:
- Can Create NPC's
- Can Deal with Text/Color
- Can use Skins ans Name color

Related Plugins: (to my understanding)
-Citizens Version: v1.0.9d
-Permissions 3.-x
-iConomy 5.0.1 (Eurrania)
-(42 Unrelated Plugins)

Error Code in the Console: (edited out most unrelated stuff)

---

 Starting With 6.0GB of Ram

---

151 recipes
16 achievements
12:01:04 [INFO] Starting minecraft server version Beta 1.7.3
12:01:04 [INFO] Loading properties
12:01:04 [INFO] Starting Minecraft server on 192.168.0.101:6736
12:01:04 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-980-g4ed23b1-b1060jnks (MC: 1.7.3)
12:01:05 [INFO] DataSourcePool [MinecartManiaCore] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
12:01:05 [INFO] SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
12:01:05 [INFO] Entities enhanced[0] subclassed[2]
12:01:05 [INFO] DataSourcePool [MinecartManiaSignCommands] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
12:01:05 [INFO] SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
12:01:05 [INFO] Entities enhanced[0] subclassed[2]
12:01:05 [INFO] [Permissions] version [3.1.6](Yeti)  loaded
12:01:05 [INFO] SkylandsPlus 0.3.1: Enabled.
12:01:05 [INFO] Preparing level "Grass"
12:01:10 [INFO] [Citizens] Loaded 0 quests.
12:01:10 [INFO] [Citizens] Permissions enabled.
12:01:10 [INFO] [Citizens] version [1.0.9d](Odyssey) loaded

12:01:10 [SEVERE] Could not pass event PLUGIN_ENABLE to Citizens
java.lang.NoClassDefFoundError: com/nijiko/coelho/iConomy/iConomy
        at com.citizens.resources.register.methods.iCo4.isCompatible(iCo4.java:66)
        at com.citizens.resources.register.Methods.createMethod(Methods.java:60)
        at com.citizens.resources.register.Methods.setMethod(Methods.java:106)
        at com.citizens.listeners.ServerListen.onPluginEnable(ServerListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:548)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:892)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.ClassNotFoundException: com.nijiko.coelho.iConomy.iConomy
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
        ... 16 more

12:01:10 [SEVERE] Could not pass event PLUGIN_ENABLE to Citizens
java.lang.NoClassDefFoundError: com/nijiko/coelho/iConomy/iConomy
        at com.citizens.resources.register.methods.iCo4.isCompatible(iCo4.java:66)
        at com.citizens.resources.register.Methods.createMethod(Methods.java:60)
        at com.citizens.resources.register.Methods.setMethod(Methods.java:106)
        at com.citizens.listeners.ServerListen.onPluginEnable(ServerListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:548)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:892)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

12:01:10 [SEVERE] Could not pass event PLUGIN_ENABLE to Citizens
java.lang.NoClassDefFoundError: com/nijiko/coelho/iConomy/iConomy
        at com.citizens.resources.register.methods.iCo4.isCompatible(iCo4.java:66)
        at com.citizens.resources.register.Methods.createMethod(Methods.java:60)
        at com.citizens.resources.register.Methods.setMethod(Methods.java:106)
        at com.citizens.listeners.ServerListen.onPluginEnable(ServerListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:548)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:892)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

12:01:10 [SEVERE] Could not pass event PLUGIN_ENABLE to Citizens
java.lang.NoClassDefFoundError: com/nijiko/coelho/iConomy/iConomy
        at com.citizens.resources.register.methods.iCo4.isCompatible(iCo4.java:66)
        at com.citizens.resources.register.Methods.createMethod(Methods.java:60)
        at com.citizens.resources.register.Methods.setMethod(Methods.java:106)
        at com.citizens.listeners.ServerListen.onPluginEnable(ServerListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:548)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:892)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

12:01:10 [SEVERE] Could not pass event PLUGIN_ENABLE to Citizens
java.lang.NoClassDefFoundError: com/nijiko/coelho/iConomy/iConomy
        at com.citizens.resources.register.methods.iCo4.isCompatible(iCo4.java:66)
        at com.citizens.resources.register.Methods.createMethod(Methods.java:60)
        at com.citizens.resources.register.Methods.setMethod(Methods.java:106)
        at com.citizens.listeners.ServerListen.onPluginEnable(ServerListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:548)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:892)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

12:01:10 [SEVERE] Could not pass event PLUGIN_ENABLE to Citizens
java.lang.NoClassDefFoundError: com/nijiko/coelho/iConomy/iConomy
        at com.citizens.resources.register.methods.iCo4.isCompatible(iCo4.java:66)
        at com.citizens.resources.register.Methods.createMethod(Methods.java:60)
        at com.citizens.resources.register.Methods.setMethod(Methods.java:106)
        at com.citizens.listeners.ServerListen.onPluginEnable(ServerListen.java:35)
        at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:548)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:892)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:278)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:178)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:161)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:149)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

12:01:10 [INFO] Server permissions file permissions.yml is empty, ignoring it
12:01:10 [INFO] Done (0.438s)! For help, type "help" or "?"
12:01:10 [INFO] [Citizens] Loaded 11 NPCs.

**Comment by aPunch** [comment]
fixed in dev builds and will be in 1.1
