### ISSUE TITLE
Could not pass EntityDamageEvent to Citizens - on /suicide

### ISSUE THREAD

**Issue by SERVERCONSOLE** [CitizensDev/Citizens#815]
Got this with CraftBukkit R3. Is says it failed to send it to you so I am posting it here. I know nothing more other than this. Hope it helps.

:47 [INFO] [Citizens] An error occurred whilst sending your error report.
13:33:47 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
13:33:56 [SEVERE] Could not pass event org.bukkit.event.entity.EntityDamageEvent to Citizens
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:453)
        at com.earth2me.essentials.commands.Commandsuicide.run(Commandsuicide.java:20)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:97)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:340)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:267)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:777)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:737)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:725)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1024)
        ... 19 more
Caused by: java.lang.ClassCastException
13:33:56 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
13:33:56 [INFO] [Citizens] An error occurred whilst sending your error report.
13:33:56 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.

**Comment by SERVERCONSOLE** [comment]
Just got this again running CraftBukkit R4 and Citizens 1.1.6 - It seems to occur when some one does /suicide

**Comment by Endimmion** [comment]
I confirm, same issue on my server
