### ISSUE TITLE
Guard problems

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#83]
I've already posted this error before but I've discovered how exactly to reproduce the problem. It seems that this error is displayed every time there's two bouncer guards and they both go after a mob or something that they have a flag set for and both kill it. I'm not sure if it's because they kill it at the same time or if one kills the mob before the other one. After this error is displayed, they just don't react to anything anymore. You can kill them, mobs can come close to them they just stand there and not move at all. Here's the error :

2011-09-05 20:40:16 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
    at com.google.common.collect.Iterables.filter(Iterables.java:493)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:107)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:83)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:136)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:131)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:143)
    at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:38)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:63)
    at net.citizensnpcs.guards.GuardTask.handleTarget(GuardTask.java:100)
    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:66)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:428)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-09-05 20:40:16 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
    at com.google.common.collect.Iterables.filter(Iterables.java:493)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:107)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:83)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:606)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:136)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:131)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:143)
    at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:38)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:63)
    at net.citizensnpcs.guards.GuardTask.handleTarget(GuardTask.java:100)
    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:66)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:428)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

Also it would be a good idea to make guards jump in case they encounter an obstacle, because they get stuck in one block high holes every time. They also don't want to come back to their original spawn point like in 1.0.9d. This is on 1.1 build #119

**Comment by fullwall** [comment]
Fixed the NPE, thanks for the report. The pathfinding issue is hard to fix, as we use minecraft's pathfinding system.
