### ISSUE TITLE
/npc create   error (normal priority) (bukkit 1.1.4 error) (citizen 1.1.6)

### ISSUE THREAD

**Issue by mazius123** [CitizensDev/Citizens#843]
when i want to create npc with command /npc create it get error in the game (to report error from cmd) and the error in the cmd :

2012-02-17 17:27:33 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
2012-02-17 17:27:33 [SEVERE]    at com.iCo6.Constants$Nodes.getBoolean(Constants.java:95)
2012-02-17 17:27:33 [SEVERE]    at com.iCo6.system.Queried.setBalance(Queried.java:311)
2012-02-17 17:27:33 [SEVERE]    at com.iCo6.system.Holdings.setBalance(Holdings.java:26)
2012-02-17 17:27:33 [SEVERE]    at com.iCo6.system.Holdings.math(Holdings.java:103)
2012-02-17 17:27:33 [SEVERE]    at com.iCo6.system.Holdings.subtract(Holdings.java:65)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.resources.register.payment.methods.iCo6$iCoAccount.subtract(iCo6.java:127)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.Economy.subtract(Economy.java:112)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.Economy.pay(Economy.java:99)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:213)
2012-02-17 17:27:33 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-02-17 17:27:33 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-02-17 17:27:33 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-02-17 17:27:33 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-02-17 17:27:33 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:220)
2012-02-17 17:27:33 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-02-17 17:27:33 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-02-17 17:27:33 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:402)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:784)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:744)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:732)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
2012-02-17 17:27:33 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-02-17 17:28:05 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
2012-02-17 17:28:05 [SEVERE]    at com.iCo6.Constants$Nodes.getBoolean(Constants.java:95)
2012-02-17 17:28:05 [SEVERE]    at com.iCo6.system.Queried.setBalance(Queried.java:311)
2012-02-17 17:28:05 [SEVERE]    at com.iCo6.system.Holdings.setBalance(Holdings.java:26)
2012-02-17 17:28:05 [SEVERE]    at com.iCo6.system.Holdings.math(Holdings.java:103)
2012-02-17 17:28:05 [SEVERE]    at com.iCo6.system.Holdings.subtract(Holdings.java:65)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.resources.register.payment.methods.iCo6$iCoAccount.subtract(iCo6.java:127)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.Economy.subtract(Economy.java:112)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.Economy.pay(Economy.java:99)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:213)
2012-02-17 17:28:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-02-17 17:28:05 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-02-17 17:28:05 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-02-17 17:28:05 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:530)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:407)
2012-02-17 17:28:05 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:220)
2012-02-17 17:28:05 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
2012-02-17 17:28:05 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
2012-02-17 17:28:05 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:402)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:784)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:744)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:732)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
2012-02-17 17:28:05 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

how can i fix this thing , please help ! , thanx for comments :)

**Comment by mazius123** [comment]
fixed , after i deleted iconomy and writen again ... ;D
