### ISSUE TITLE
error starting citizens

### ISSUE THREAD

**Issue by JasonDePhillips** [CitizensDev/Citizens#85]
21:35:33 [SEVERE] Error occurred while enabling Citizens v1.0.9 (Is it up to dat
e?): com/google/common/collect/Maps
java.lang.NoClassDefFoundError: com/google/common/collect/Maps
        at com.citizens.npcs.NPCTypeManager.<clinit>(NPCTypeManager.java:10)
        at com.citizens.Citizens.registerTypes(Citizens.java:271)
        at com.citizens.Citizens.onEnable(Citizens.java:87)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:857)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:264)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:151)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:136
)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:284)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:271)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:148)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:335)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more

**Comment by PaulTT88** [comment]
May need to give them some more information, bukkit version, citizens version, etc

Looks like a missing dependancy of some sort, what JRE/JDK you using?

A quick google showed; http://code.google.com/p/gdata-java-client/issues/detail?id=180

**Comment by JasonDePhillips** [comment]
my minecraft version is 1.7.3
newest java update
citizens 1.0.9
bukkit build 556 of craftbukkit

i don't know what JRE/JDK are

**Comment by aPunch** [comment]
Build 556? CraftBukkit is on 1080+ by now. We no longer support anything less than the current RB of 1060.
