### ISSUE TITLE
Some more quester issues

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#87]
The previous error I submitted is now gone, however when I assign any quest to the quester and left/right click on him, he says "No quests are available." When I add another one (in this case it was example and example2) and right click on the quester, I get this:

Could not pass event ENTITY_TARGET to Citizens
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.citizensnpcs.questers.Quester.fetch(Quester.java:202)
    at net.citizensnpcs.questers.Quester.cycle(Quester.java:157)
    at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:58)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:158)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:112)
    at org.bukkit.plugin.java.JavaPluginLoader$64.execute(JavaPluginLoader.java:691)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:321)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:870)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

When I left click, I get this:

 Could not pass event ENTITY_DAMAGE to Citizens
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.citizensnpcs.questers.Quester.fetch(Quester.java:202)
    at net.citizensnpcs.questers.Quester.cycle(Quester.java:157)
    at net.citizensnpcs.questers.Quester.onLeftClick(Quester.java:49)
    at net.citizensnpcs.resources.npclib.HumanNPC.callLeftClick(HumanNPC.java:152)
    at net.citizensnpcs.listeners.EntityListen.onEntityDamage(EntityListen.java:48)
    at org.bukkit.plugin.java.JavaPluginLoader$59.execute(JavaPluginLoader.java:656)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:427)
    at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:180)
    at net.minecraft.server.EntityHuman.d(EntityHuman.java:566)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:883)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

Also sometimes, when a quester has all the quests removed, he still says he has one quest left and when he has one, he says he has two.

**Comment by defaultsucks** [comment]
This is fixed in the latest dev builds.
