### ISSUE TITLE
Problem Turning on! ERROR

### ISSUE THREAD

**Issue by gjossep** [CitizensDev/Citizens#878]
Hello, i have a problem running citizens on my server, when i try any command for example /npc create bob it says unknown command try /npc help, even if i do that it says the same error. So i looked through the console and found this:

Error occurred while enabling Citizens v1.1.6 (Is it up to date?): org/bukkit/event/HandlerList
java.lang.NoClassDefFoundError: org/bukkit/event/HandlerList
    at net.citizensnpcs.api.event.CitizensEnableTypeEvent.<clinit>(CitizensEnableTypeEvent.java:20)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:312)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:78)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:970)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:190)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:173)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:440)
    at org.bukkit.Bukkit.reload(Bukkit.java:188)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:768)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:728)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:721)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:96)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:534)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.HandlerList
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 23 more

Whats wrong? I just downloaded the plugin?

Thanks
Gjosse

**Comment by Fureniku** [comment]
Make sure you're using the most recent RB of craftbukkit would be the first step.

Did you move the folder as well as Citizens.jar into your plugin folder?
