### ISSUE TITLE
Issue with /suicide (Essentials)

### ISSUE THREAD

**Issue by Avarice** [CitizensDev/Citizens#893]
Any time that any player group uses /suicide, the following errors occur. There are no NPCs named after players.

03:24:46 [SEVERE] Could not pass event org.bukkit.event.entity.EntityDamageEvent
 to Citizens
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.
java:1026)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:61)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:460)
        at com.earth2me.essentials.commands.Commandsuicide.run(Commandsuicide.ja
va:20)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsComm
and.java:97)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.jav
a:340)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:267)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:16
8)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:4
02)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.
java:784)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:744)

```
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:732)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
```

:176)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java
:552)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:7
8)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.
java:1024)
        ... 21 more
Caused by: java.lang.ClassCastException: com.earth2me.essentials.User cannot be
cast to org.bukkit.craftbukkit.entity.CraftEntity
        at net.citizensnpcs.resources.npclib.NPCList.getNPC(NPCList.java:19)
        at net.citizensnpcs.resources.npclib.NPCManager.get(NPCManager.java:31)
        at net.citizensnpcs.listeners.EntityListen.onEntityDamage(EntityListen.j
ava:29)
        ... 25 more
03:24:46 [INFO] [Citizens] An error has occurred, please wait while it is sent t
o the developers...
03:24:46 [INFO] [Citizens] An error occurred whilst sending your error report.
03:24:46 [INFO] [Citizens] Below is the stacktrace that has been transmitted to
the developers, no other information has been included other than Citizens versi
on information.

**Comment by SERVERCONSOLE** [comment]
Same as #815
