### ISSUE TITLE
Not sure what this issue is? I believe it involves Guard flags

### ISSUE THREAD

**Issue by BeenCarl** [CitizensDev/Citizens#894]
[WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getType()Lorg/bukkit/entity/EntityType;
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:114)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:142)
    at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:35)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
    at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
    at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
    at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
    at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-03-02 11:31:31 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getType()Lorg/bukkit/entity/EntityType;
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:114)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:142)
    at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:35)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
    at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
    at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
    at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
    at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-03-02 11:31:31 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getType()Lorg/bukkit/entity/EntityType;
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:114)
    at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
    at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:142)
    at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:35)
    at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
    at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
    at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
    at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
    at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
    at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-03-02 11:32:03

**Comment by Fureniku** [comment]
Citizens Build? Bukkit Build?

**Comment by BeenCarl** [comment]
Citizens 1.1.5 I thought I updated but I might have dowloaded wrong current on every thing else let me re-update and I'll get back to you

**Comment by BeenCarl** [comment]
Updated the guard issue stopped I think
