### ISSUE TITLE
I believe this is Citizens quest. I have only one quest that work before.

### ISSUE THREAD

**Issue by BeenCarl** [CitizensDev/Citizens#895]
2012-03-01 15:46:23 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in "<string>", line 26, column 13:
                '0':
                ^
expected <block end>, but found BlockMappingStart
 in "<string>", line 40, column 16:
                   rewards:
                   ^

2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:37)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.properties.ConfigurationHandler.<init>(ConfigurationHandler.java:30)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.questers.data.QuestProperties.<clinit>(QuestProperties.java:9)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:29)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.Citizens.onEnable(Citizens.java:112)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-03-01 15:46:23 [SEVERE] Caused by: while parsing a block mapping
 in "<string>", line 26, column 13:
                '0':
                ^
expected <block end>, but found BlockMappingStart
 in "<string>", line 40, column 16:
                   rewards:
                   ^

2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
2012-03-01 15:46:23 [SEVERE]    ... 17 more
2012-03-01 15:46:23 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in "<string>", line 26, column 13:
                '0':
                ^
expected <block end>, but found BlockMappingStart
 in "<string>", line 40, column 16:
                   rewards:
                   ^

2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.properties.ConfigurationHandler.load(ConfigurationHandler.java:37)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.questers.data.QuestProperties.initialize(QuestProperties.java:13)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.questers.QuesterType.registerEvents(QuesterType.java:29)
2012-03-01 15:46:23 [SEVERE]    at net.citizensnpcs.Citizens.onEnable(Citizens.java:112)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
2012-03-01 15:46:23 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
2012-03-01 15:46:23 [SEVERE] Caused by: while parsing a block mapping
 in "<string>", line 26, column 13:
                '0':
                ^
expected <block end>, but found BlockMappingStart
 in "<string>", line 40, column 16:
                   rewards:
                   ^

2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
2012-03-01 15:46:23 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
2012-03-01 15:46:23 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
2012-03-01 15:46:23 [SEVERE]    ... 16 more
2012-03-01 15:46:23 [INFO] [Citizens] version [1.1.5] loaded.
2012-03-01 15:46:23

Here is the quest if I changed something. Fixed move location objective.

"Bandito Loco: 1":
    texts:
        description: "We have had a few attacks by the Banditos and we can't
            <br>spare the resources to find them. We need you to find them and 
            <br>see where they are. Please this place needs more heros.
            <br>Quest: <g>El Bandito Loco: Recruited
            <br>Objective: Find Bandito camp."
        acceptance: "Great! You are truly a friend! Our small 
            <br>city has been through a lot we appreciate it. 
            <delay=80>Quest: El Bandito Loco: Recruited started.
            <delay=40>Remember, you can use /quest status to check your progress."
        completion: "Thank you! We are spread thin right now.
            <br>We really appreciate the help!
            <br>Quest: You have recieved 100 shekel for your effort.
            <br><delay=20>We could use more men who take action like you."
    repeats: 1
    objectives:
        '0':
            '0':
                type: move location
                x:
                y:
                z:
                world: 'world'
                message: "&6Quest: A dozen slimes down. That wasn't so hard. 
                    <delay=120>Perhaps you should see if requires any additional help?"
        '1': 
            '0':
                type: Player combat
                string: 'Bandito'
                amount: 6
                npcdestination: 22
                optional: True # Optional sub-objective triggers only if you bring slimeballs
                               # before the other objective is complete. 
                message: "Quest: Banditos .
                    <delay=50>Oh, what's this? 
                    <delay=20> I am suprised you took on the Banditos! Take this -- perhaps it will help you
                    <br>slong  your journey. 
                    <delay=40>Oh, talk to Kaylin once she is done deciphering  
                    <delay=20>Quest: You have gained 60 extra shekel"  
               rewards:
                   '0':
                        type: money
                        money: 60  
           '1':
               type: delivery
                materialid: 341 # Slimeballs
                amount: 6
                npcdestination: 22
                optional: True # Optional sub-objective triggers only if you bring slimeballs
                               # before the other objective is complete. 
                message: "Quest: Book delivered.
                    <delay=50>Oh, what's this? 
                    <delay=20>Hmm, This seems to be coded. Keep whatever else you found, but I 
                    <br>am suprised you took on the Banditos! Take this -- perhaps it will help you
                    <br>along  your journey. 
                    <delay=40>Oh, report to Kaylin once she is done deciphering the book.  
                    <delay=20>&6Quest: You have received a bow and arrows! Nice!"  
                rewards:
                    '0':
                         type: item
                         id: 261  # Bow
                         amount: 1
                    '1':
                         type: item
                         id: 262  # Arrows
                         amount: 64
    rewards:
        '0':
            type: money
            money: 100

**Comment by BeenCarl** [comment]
It doesnt show the < br > no space 
and if you need something more I will respond faster to a pm on bukkit instead of here.

**Comment by Fureniku** [comment]
The dev's dont post here by the way, its community help only :P

Your YAML is messed up somehow, but I can't see how because of how its posted. Post the whole file onto pastebin and put the link here

**Comment by BeenCarl** [comment]
Oh okay thanks for the info and the help will post to pastebin
Edit: here is the link http://pastebin.com/VDrHULaY

**Comment by Fureniku** [comment]
http://pastebin.com/i8PpQ09x

Try that. You missed a few spaces in your YAML formatting (I think it was two places, you only had 3 out of the 4 spaces to make a yaml indent and so some was out of line)

When you get errors like that, paste it into this: it will tell you what line the errors are on. Usually it will say two lines - its often the second of the two (The first is the opening, the second is where its trying to close but errors because of a mistake)

http://yaml-online-parser.appspot.com/

Let me know if your NPC hunting works by the way - You've written it different to me but mine doesn't work :P
Also from experience "move location" doesn't work, but just putting "location" does, so I changed it. If it doesn't work, try changing it back, but thats how it is on all my quests and it works :P

**Comment by BeenCarl** [comment]
Okay thanks this is my first time with quests and the tutorials are a little vague. Works like a charm now

**Comment by Fureniku** [comment]
Glad to hear - did killing the NPC work right?
