### ISSUE TITLE
Problem with bPermissions

### ISSUE THREAD

**Issue by Superboop** [CitizensDev/Citizens#897]
The latest dev build (#27) does not seem to work with bPermissions. Note that I am using Bukkit buid #2029.

This is what happens when I download the build, and put the things in:

18:00:29 [SEVERE] Error occurred while enabling Citizens v1.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: de/bananaco/permissions/Permissions
    at net.citizensnpcs.permissions.BPermissionsProvider.<init>(BPermissionsProvider.java:14)
    at net.citizensnpcs.permissions.PermissionManager.init(PermissionManager.java:39)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:127)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:374)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:361)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.ClassNotFoundException: de.bananaco.permissions.Permissions
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 13 more
18:00:29 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...

The same thing happens when I close the server and put the types folder in the newly created Citizens folder (It gets created when first loading Citizens, the folder is not included in the build artifact).

The strange thing is, nothing gets sent to the developers:

18:00:29 [INFO] [Citizens] An error occurred whilst sending your error report.
18:00:29 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.
18:00:29 [INFO] Server permissions file permissions.yml is empty, ignoring it
18:00:30 [INFO] Done (8.187s)! For help, type "help" or "?"

So I am confused. Is there an incompatibility?

**Comment by Superboop** [comment]
Also note that PermissionsBukkit is outdated (It does not work with 1.2.3), and PermissionsEx is incompatible with MagicSpells, so I cannot use that either.

**Comment by Sydael** [comment]
What are you talkin about? I downloaded the latest PermissionsBukkit and it works with 1.2.3.

**Comment by Superboop** [comment]
Maybe it's an incompatibility with MagicSpells, I do not know, but it does not work (I've used PermissionsBukkit before so I know how to configure it..)

Is there any way to solve this problem while using bPermissions?
