### ISSUE TITLE
Could not pass Entity_Damage to Citizens

### ISSUE THREAD

**Issue by MadcowD** [CitizensDev/Citizens#9]
15:27:02 [SEVERE] Could not pass event ENTITY_DAMAGE to Citizens
java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.resources.npclib.creatures.Creatur
eTask
        at net.citizensnpcs.listeners.EntityListen.onEntityDamage(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$59.execute(JavaPluginLoader.java:656)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at net.minecraft.server.EntityArrow.m_(EntityArrow.java:183)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1212)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:48)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1194)
        at net.minecraft.server.World.cleanUp(World.java:1110)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:450)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

Bukit 1060, Spout 167

**Comment by aPunch** [comment]
5 errors, all caused by you not reading the OP on the Bukkit forum thread.
