### ISSUE TITLE
citizens crashing on server start

### ISSUE THREAD

**Issue by remypas** [CitizensDev/Citizens#912]

**Comment by remypas** [comment]
I have bukkit: version git-Bukkit-1.1-R6-33-gb66156b-b2034jnks (MC: 1.2.3) (Implementing API version 1.2.3-R0.1)
Citizens v1.1.2 (nevers build through link on bukkitdev)

and I'm getting this issue when I start my server:

012-03-08 23:02:01 [SEVERE] Error occurred while enabling Citizens v1.1.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.event.Event.<init>(Ljava/lang/String;)V
    at net.citizensnpcs.api.event.CitizensEvent.<init>(CitizensEvent.java:7)
    at net.citizensnpcs.api.event.CitizensEnableTypeEvent.<init>(CitizensEnableTypeEvent.java:10)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:106)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:203)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:374)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:361)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

Anyone have any ideas what I could be doing wrong?

**Comment by philipmetting** [comment]
build 43 was giving me that issue, so i tried build 42 and the error went away

**Comment by remypas** [comment]
I downloaded 43
it's still giving me the same issue.

**Comment by philipmetting** [comment]
I used 42. They still don't let you select them though
On Mar 9, 2012 3:51 AM, "remypas" <
reply@reply.github.com>
wrote:

**Comment by gabriel11798** [comment]
just . . . wait for their RB since the event system has changed, so nearly everything won't work
