### ISSUE TITLE
Guards don't attack 1.2

### ISSUE THREAD

**Issue by ansss** [CitizensDev/Citizens#927]
hi, i have this problem in my server:

11:55:03 [ADVERTENCIA] Task of 'Citizens' generated an exception
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayer
Groups(Permission_SuperPerms.java:91)
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.j
ava:522)
        at net.citizensnpcs.permissions.PermissionManager.getGroups(PermissionMa
nager.java:105)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:99)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)

```
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
```

terator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:136)
        at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:
142)
        at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:33)
        at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:
57)
        at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
        at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
        at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
        at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
        at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

and then , all guards with assigned flags won't attack mobs , can someone help me or fix the problem?

**Comment by tincopper2** [comment]
:( IK, I AM MAD NOW. STAY MORE UPTODATE FULLWALL.
