### ISSUE TITLE
Trader Transaction Issue

### ISSUE THREAD

**Issue by CovertHoax** [CitizensDev/Citizens#929]
Had a strange error happen when trying to use traders..
Used to work fine but had other issues like the NPC not actually looking at you or equipping anything.
Anyway I updated to your latest build of Citizens (1) and now they look at you and equip stuff, I can also use the /trader buy/sell command however i cant actually open the window to stock items.. I get this long error..

03:30:10 [SEVERE] Could not pass event NPCTargetEvent to Citizens org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
        at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1064)
        at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:116)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.utils.InventoryUtils.showInventory(Lnet/citizensnpcs/resources/npclib/HumanNPC;Lorg/bukkit/entity/Player;)V
        at net.citizensnpcs.traders.Trader.onRightClick(Trader.java:162)
        at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
        at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
        ... 18 more
03:30:10 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
03:30:10 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.PlayerInventory.l()Lnet/minecraft/server/ItemStack;
        at net.citizensnpcs.traders.TraderTask.run(TraderTask.java:69)
        at net.citizensnpcs.traders.TraderTask.kill(TraderTask.java:124)
        at net.citizensnpcs.traders.TraderTask.run(TraderTask.java:59)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
03:30:11 [INFO] [Citizens] <html>
03:30:11 [INFO] [Citizens] <head>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
03:30:11 [INFO] [Citizens] <meta name=ÔÇ?keywordsÔÇ? content=ÔÇ?Citizens,CitizensNPCs,NPCs for bukkit,bukkit,npcsÔÇ?>
03:30:11 [INFO] [Citizens] <meta name=ÔÇ?descriptionÔÇ? content=ÔÇ?CitizensNPCs| Citizens - NPCs for BukkitÔÇ?>
03:30:11 [INFO] [Citizens] <meta name="copyright" content="&copy; 2012 CitizensNPCs. All rights reserved.">
03:30:11 [INFO] [Citizens] <title>Citizens | CitizensNPCs - NPCs for Bukkit</title>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <link rel="icon" href="http://citizensnpcs.net/favicon.ico" type="image/x-icon">
03:30:11 [INFO] [Citizens] <link rel="shortcut icon" href="http://citizensnpcs.net/favicon.ico" type="image/x-icon">
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <script type="text/javascript" src="http://use.typekit.com/cui2twk.js"></script>
03:30:11 [INFO] [Citizens] <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <link href="assets/css/reset.css" rel="stylesheet" type="text/css" />
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] 
03:30:11 [INFO] [Citizens]      <link href="assets/css/style.css" rel="stylesheet" type="text/css" />
03:30:11 [INFO] [Citizens] 
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] 
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <link rel="canonical" href="http://citizensnpcs.net/" />
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <script src="assets/js/jquery.js" type="text/javascript"></script>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <script type="text/javascript">
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens]   var _gaq = _gaq || [];
03:30:11 [INFO] [Citizens]   _gaq.push(['_setAccount', 'UA-29470147-3']);
03:30:11 [INFO] [Citizens]   _gaq.push(['_trackPageview']);
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens](function%28%29 {
03:30:11 [INFO] [Citizens]     var ga = document.createElement%28'script'%29; ga.type =) + '.google-analytics.com/ga.js';
03:30:11 [INFO] [Citizens]     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
03:30:11 [INFO] [Citizens]   })();
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] </script>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] </head>
03:30:11 [INFO] [Citizens] <body>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] <div id="wrapper">
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens]      <div id="header">
03:30:11 [INFO] [Citizens]              <h1 class="logo">Citizens - CitizensNPCs - NPCs for bukkit!</h1>
03:30:11 [INFO] [Citizens]      </div> 
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens]      <div id="content">
03:30:11 [INFO] [Citizens]              <div id="mainbox">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                              <h2>NOW BETA TESTING</h2>
03:30:11 [INFO] [Citizens]                              <p>ItÔÇÖs finally here!
Citizens2 is the exciting new rewrite of the Citizens plugin you know and love,

03:30:11 [INFO] [Citizens]                              <br/> with more features and extendability than ever before!
03:30:11 [INFO] [Citizens]                              The new Citizens2 API enables developers to easily utilize all types of NPC traits and abilities to help create more Characters
03:30:11 [INFO] [Citizens]                              than ever before.
03:30:11 [INFO] [Citizens]                              Users will love the ability to create NPC mobs, all with the same control you would expect from Citizens
.
03:30:11 [INFO] [Citizens]                              <br/>WeÔÇÖre excited tosee how you will use Citizens2!</p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens]              <div id="community">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                              <h2>CITIZENS COMMUNITY</h2>
03:30:11 [INFO] [Citizens]                              <p>You can always find the latest information about Citizens and its Characters on our wiki.</p>
03:30:11 [INFO] [Citizens]                              <a target="#" href="http://wiki.citizensnpcs.net">http://wiki.citizensnpcs.net</a>
03:30:11 [INFO] [Citizens]                              <p>Please report any issues at <a href="http://issues.citizensnpcs.net/">http://issues.citizensnpcs.net</a></p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]              <div id="testing">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                              <h2>TESTING THE WATERS</h2>
03:30:11 [INFO] [Citizens]                              <p>Looking for bleedingedge? Download our latest developmental builds.</p>
03:30:11 [INFO] [Citizens]                              <p>Latest Developmental: <a target="#" href="http://ci.citizensnpcs.net/job/Citizens2/lastSuccessfulBuil
d/">
03:30:11 [INFO] [Citizens]                              #54
        </a></p>
03:30:11 [INFO] [Citizens]                              <p>Latest Developmental
API: <a target="#" href="http://ci.citizensnpcs.net/job/CitizensAPI/lastSuccessfulBuild/">
03:30:11 [INFO] [Citizens]                              #36
        </a></p>
03:30:11 [INFO] [Citizens]                              </p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]              <div id="donate">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                      <h2>CAVE OF DONATIONS</h2>
03:30:11 [INFO] [Citizens]                      <p>Citizens wouldnÔÇÖt be here without the work of a dedicated team of individuals. Like what weÔÇÖre doing? Let us know with your donations! 
03:30:11 [INFO] [Citizens]                      <br/>
03:30:11 [INFO] [Citizens]                      <a target="#" href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=theapunch%40yahoo%2ecom&lc=US&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted">Donate to aPunch</a><br/>
03:30:11 [INFO] [Citizens]                      <a target="#" href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=CEQD6UNQHUG3C&lc=US&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted">Donate to fullw
all</a>
03:30:11 [INFO] [Citizens]                      </p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]              <div id="download">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                              <h2>DOWNLOAD CITIZENS <br/> FOR BUKKIT</h2>
03:30:11 [INFO] [Citizens]                              <p>Latest Release: <a target="#" href="http://ci.citizensnpcs.net/job/Citizens2/Release/">
03:30:11 [INFO] [Citizens]                              #
        </a></p>
03:30:11 [INFO] [Citizens]                              <p>Latest API Release: <a target="#" href="http://ci.citizensnpcs.net/job/CitizensAPI/Release/">
03:30:11 [INFO] [Citizens]                              #
        </a></p>
03:30:11 [INFO] [Citizens]                              <p>BukkitDev Page: <a target="#" href="http://dev.bukkit.org/server-mods/citizens/">Citizens</a></p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]              <div id="underground">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                              <h2>THE UNDERGROUND</h2>

03:30:11 [INFO] [Citizens]                              <p>Visit us on irc.esper.net in the #citizens channel to watch development in real-time or to ask questions to dedicated users and developers.</p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]              <div id="credits">
03:30:11 [INFO] [Citizens]                      <div class="transparency"></div>

03:30:11 [INFO] [Citizens]                      <div class="content">
03:30:11 [INFO] [Citizens]                              <p>Sponsored by <a target="#" href="http://creeperhost.net">CreeperHost</a></p>
03:30:11 [INFO] [Citizens]                              <p>Copyright 2012 ┬® CitizensNPCs.net</p>
03:30:11 [INFO] [Citizens]                      </div>
03:30:11 [INFO] [Citizens]              </div>
03:30:11 [INFO] [Citizens]      </div> 
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] </div> 
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens]
03:30:11 [INFO] [Citizens] </body>
03:30:11 [INFO] [Citizens] </html>
03:30:11 [INFO] [Citizens] Below is the stacktrace that has been transmitted tothe developers, no other information has been included other than Citizens version information.

Not sure how helpful that is but its the most information i could get for you guys..
If its as simple as downloading a update for the trader then thats fine I can do that but if its a huge bug then how come its just me getting it?
Havent seen this error anywhere.. :/

**Comment by PhoenyxCZ** [comment]
Same to me..
its sad that nobodey can answer us.

**Comment by CovertHoax** [comment]
Found a fix...

there is a traders jar file from the 9th that works..

http://ci.citizensnpcs.net/job/Citizens/45/artifact/bin/types/Trader.jar
That one... test it and let me know if it fix's it for you too..
