### ISSUE TITLE
Could not pass InventoryClickEvent to Citizens

### ISSUE THREAD

**Issue by RightDecision** [CitizensDev/Citizens#943]
I've got a problem with my traders. I can open their Inventorys but I can't sell or buy Items. My Server is running on Craftbukkit 2098.
In the server.log file it looks so:

2012-03-20 15:59:09 [SEVERE] Could not pass event InventoryClickEvent to Citizens
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:441)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1156)
at net.minecraft.server.Packet102WindowClick.handle(SourceFile:28)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:116)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
at net.citizensnpcs.Economy.format(Economy.java:78)
at net.citizensnpcs.traders.TraderMessageUtils.getPriceMessage(TraderMessageUtils.java:13)
at net.citizensnpcs.traders.TraderMessageUtils.getStockableMessage(TraderMessageUtils.java:19)
at net.citizensnpcs.traders.TraderTask.sendStockableMessage(TraderTask.java:183)
at net.citizensnpcs.traders.TraderTask.handleTraderClick(TraderTask.java:81)
at net.citizensnpcs.traders.TraderTask.onInventoryClick(TraderTask.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
... 10 more
2012-03-20 15:59:09 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] Citizens | CitizensNPCs - NPCs for Bukkit
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] try{Typekit.load();}catch(e){}
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] <br> 2012-03-20 15:59:11 [INFO] [Citizens] <br> 2012-03-20 15:59:11 [INFO] [Citizens] var _gaq = _gaq || [];<br> 2012-03-20 15:59:11 [INFO] [Citizens] _gaq.push(['_setAccount', 'UA-29470147-3']);<br> 2012-03-20 15:59:11 [INFO] [Citizens] _gaq.push(['_trackPageview']);<br> 2012-03-20 15:59:11 [INFO] [Citizens] <br> 2012-03-20 15:59:11 [INFO] <a href="function(">Citizens</a> {<br> 2012-03-20 15:59:11 [INFO] [Citizens] var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;<br> 2012-03-20 15:59:11 [INFO] [Citizens] ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';<br> 2012-03-20 15:59:11 [INFO] [Citizens] var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);<br> 2012-03-20 15:59:11 [INFO] [Citizens] })();<br> 2012-03-20 15:59:11 [INFO] [Citizens] <br> 2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
Citizens - CitizensNPCs - NPCs for bukkit!

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
NOW BETA TESTING

2012-03-20 15:59:11 [INFO] [Citizens]
It’s finally here! Citizens2 is the exciting new rewrite of the Citizens plugin you know and love, 
2012-03-20 15:59:11 [INFO] [Citizens] 
with more features and extendability than ever before!
2012-03-20 15:59:11 [INFO] [Citizens] The new Citizens2 API enables developers to easily utilize all types of NPC traits and abilities to help create more Characters
2012-03-20 15:59:11 [INFO] [Citizens] than ever before.

2012-03-20 15:59:11 [INFO] [Citizens] Users will love the ability to create NPC mobs, all with the same control you would expect from Citizens. 
2012-03-20 15:59:11 [INFO] [Citizens] 
We’re excited to see how you will use Citizens2!

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
CITIZENS COMMUNITY

2012-03-20 15:59:11 [INFO] [Citizens]
You can always find the latest information about Citizens and its Characters on our wiki.

2012-03-20 15:59:11 [INFO] [Citizens] http://wiki.citizensnpcs.net
2012-03-20 15:59:11 [INFO] [Citizens]
Please report any issues at http://issues.citizensnpcs.net

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
TESTING THE WATERS

2012-03-20 15:59:11 [INFO] [Citizens]
Looking for bleeding edge? Download our latest developmental builds.

2012-03-20 15:59:11 [INFO] [Citizens]
Latest Developmental: 
2012-03-20 15:59:11 [INFO] [Citizens] #57

2012-03-20 15:59:11 [INFO] [Citizens]
Latest Developmental API: 
2012-03-20 15:59:11 [INFO] [Citizens] #37

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
CAVE OF DONATIONS

2012-03-20 15:59:11 [INFO] [Citizens]
Citizens wouldn’t be here without the work of a dedicated team of individuals. Like what we’re doing? Let us know with your donations! 
2012-03-20 15:59:11 [INFO] [Citizens] 

2012-03-20 15:59:11 [INFO] [Citizens] Donate to aPunch

2012-03-20 15:59:11 [INFO] [Citizens] Donate to fullwall
2012-03-20 15:59:11 [INFO] [Citizens]

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
DOWNLOAD CITIZENS 
FOR BUKKIT

2012-03-20 15:59:11 [INFO] [Citizens]
Latest Release: 
2012-03-20 15:59:11 [INFO] [Citizens] #

2012-03-20 15:59:11 [INFO] [Citizens]
Latest API Release: 
2012-03-20 15:59:11 [INFO] [Citizens] #

2012-03-20 15:59:11 [INFO] [Citizens]
BukkitDev Page: Citizens

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
THE UNDERGROUND

2012-03-20 15:59:11 [INFO] [Citizens]
Visit us on irc.esper.net in the #citizens channel to watch development in real-time or to ask questions to dedicated users and developers.

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]
Sponsored by CreeperHost

2012-03-20 15:59:11 [INFO] [Citizens]
Copyright 2012 © CitizensNPCs.net

2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens] 
2012-03-20 15:59:11 [INFO] [Citizens]

**Comment by PhoenyxCZ** [comment]
I have the same problem as you.

**Comment by RightDecision** [comment]
Good to hear that I'm not the only one. Maybe there is someone who can help us

**Comment by PhoenyxCZ** [comment]
I hope so.

**Comment by alexpriceco** [comment]
I am having a similar issue with my questers.  I get click on the quester, he shows the quest and it says "right click to accept" and when I do, I get that.  Huge pain, and I am on the latest dev build.  I tried all the other builds as well, nothing.  I hope this gets fixed...

**Comment by RightDecision** [comment]
Maybe one of the developers can have a look at our problem

**Comment by alexpriceco** [comment]
Actually, I fixed it.  I just redownloaded the latest dev build of Citizens, deleted all of the files that I had not edited, and dropped in the new files.  It was the same build and everything, I just replaced the old ones with themselves.  I don't know what caused the problem, but that error was annoying as hell, and the file replacement fixed it.  I freaking love Citizens though.

**Comment by RightDecision** [comment]
It works! One million thanks to you! You are the best! Thanks a lot!
