### ISSUE TITLE
Traders inventory can be cleared by everyone.

### ISSUE THREAD

**Issue by twinflyer** [CitizensDev/Citizens#946]
Hey guys, I found an error in the latest dev-built.

A Player (NO admin) klicks on a trader. Everything works as it should.
But if he klicks twice (rightklick) he can take Items out of the traders inventory. And he can put Items in.
And they do NOT have to pay.....

Our users cleared the traders NPCs :S

Please fix this in the next dev-built.

Greetings from germany
twinflyer

**Comment by EHAndrew** [comment]
This happens to me VERY often, you cant stop the cheaters, you can only stop the cheat.

**Comment by gfrung4** [comment]
I'm curious as to why this has been basically ignored.  This is a MAJOR bug, not a minor glitch.  It essentially makes this not usable.  Why is it that no one has provided a workaround or any information AT ALL on how to resolve it?  Is there any way to fix it, because if not, then there is no reason to even use Citizens.

I would appreciate some information on this.  Thanks!

gfrung4

**Comment by EHAndrew** [comment]
2 weeks, no reply... Hast thou forgotten about thine supporters?

**Comment by bloodriot** [comment]
I'll take a look at it.
Confirmed in commit 5b4e6aef9f

Investigating.

**Comment by bloodriot** [comment]
I added a slight delay before you can reopen the trader.
This seems to give the server enough time to realize you are trying to buy.

Pull request has been submitted.

**Comment by EHAndrew** [comment]
Any way I can download your fix? I know just short of nothing when it comes to java and compiling, blah blah. lol.

**Comment by bloodriot** [comment]
I really didn't want to give a compiled version but then I got thinking you could build it from source yourself so whats the difference.

If you have any issues with it let me know as this is obviously not from the citizens team and therefore not endorsed, etc.
http://dl.dropbox.com/u/48279215/Trader.jar

Github in its infinite wisdom removed private messages or I would have used that.

**Comment by EHAndrew** [comment]
Let it be publicly known that I will not sue, yell obscenities, make crude your-mother jokes, or trash talk behind your back if this does not work.

/|/-/___  (this is similar to my real signature, and should hold up in court)

**Comment by EHAndrew** [comment]
it works! you're a god!

**Comment by CyanLights** [comment]
Hi. I am also experiencing the same problem. I tried your fix, but my console just spits out the following errors. I understand that the jar isn't supported, but I was looking for a bit of hope.

2012-04-25 07:11:46 [SEVERE] Error occurred while enabling Citizens v1.2 (Is it up to date?)
java.lang.UnsupportedClassVersionError: net/citizensnpcs/traders/TraderType : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:334)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:37)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:297)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:76)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by bloodriot** [comment]
What version of java is your server running?
I compiled it for version 1.7 so I'm guessing that's the issue.
I'll upload a 1.5 compatible jar that should resolve any version issues.

**Comment by bloodriot** [comment]
http://dl.dropbox.com/u/48279215/Trader.jar
I think that should be using version 1.5. I'll admit I'm not all that used to eclipse so it might not.

**Comment by CyanLights** [comment]
Hi t0bbage. Thank you so much for you help. But I fear the jar didn't work. I'll leave the error it generated below.

I am hosting the server from a Linux server and java -version returned this:

OpenJDK Runtime Environment (IcedTea6 1.8.13) (6b18-1.8.13-0+squeeze1)
OpenJDK 64-Bit Server VM (build 14.0-b16, mixed mode)

Does it need to be compiled in yet another version to work? I'm not at all familiar with how java works on linux installations.
I'm so sorry for all the trouble, but thank you for all your help.

2012-04-26 03:55:40 [SEVERE] Error occurred while enabling Citizens v1.2 (Is it up to date?)
java.lang.UnsupportedClassVersionError: net/citizensnpcs/traders/TraderType : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:615)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:334)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at net.citizensnpcs.npctypes.CitizensNPCLoader.loadNPCType(CitizensNPCLoader.java:37)
    at net.citizensnpcs.Citizens.loadNPCTypes(Citizens.java:297)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:76)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)

**Comment by bloodriot** [comment]
Your using 1.6. It should work, I may have not set the version correctly.
I'll set it up on my linux box tomorrow and see if I can't get it functional.

**Comment by CyanLights** [comment]
Thank you. It's really appreciated =)

**Comment by bloodriot** [comment]
I went ahead and did it tonight.
I'm running version 1.6 of open jdk so I think it should work for you now.
http://dl.dropbox.com/u/48279215/Trader.jar

**Comment by CyanLights** [comment]
You are a saint, good sir. You have my greatest thanks for helping me. I could've never did that on my own.

The fix works, and no matter how fast I try to bypass it, it doesn't let me. Beautiful :D

**Comment by CyanLights** [comment]
Ah. I'm afraid there is still yet a bug one of my MODs found. It is difficult to make work, but you hold the right mouse button down on the NPC and press "e" to open your inventory. Sometimes, it opens 3 transaction logs and allows anyone to edit their inventories. We found a lot of our shops raided this morning.

Would a longer delay help? I wouldn't even mind if you could make it 5 seconds or longer, anything to stop it XD

**Comment by bloodriot** [comment]
The delay is configurable. It's in the main citizens config. I think it's
called trader-delay-amount. It's set at 500  by default. Feel free to
change to 5000(5 seconds) to see if that works for you. If not I'll see if
I can't do something about the inventory key.
On Apr 26, 2012 6:36 PM, "CyanLights" <
reply@reply.github.com>
wrote:

**Comment by CyanLights** [comment]
We did some testing at 1000, 2000, 5000 and 10000. It is much harder to do, but my MOD tells me that when it does happen, the transaction log closes and Citizens thinks the shop isn't actually open, so it may be the inventory key like you said.
