### ISSUE TITLE
Quester

### ISSUE THREAD

**Issue by bubbarush** [CitizensDev/Citizens#953]
ok. all my quests are fine, i can give an npc any quest, but whenever i click on him it says "right click to accept quest" but after i right click nothing happens. What is wrong?

**Comment by phonix420** [comment]
Having same issue here, been looking everywhere for a solution.

**Comment by TomYaMee** [comment]
same here 

2012-04-07 21:08:08 [SEVERE] Could not pass event NPCTargetEvent to Citizens
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:51)
    at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:978)
    at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.api.event.CitizensEvent.<init>(Ljava/lang/String;)V
    at net.citizensnpcs.questers.api.events.QuestEvent.<init>(QuestEvent.java:14)
    at net.citizensnpcs.questers.api.events.QuestBeginEvent.<init>(QuestBeginEvent.java:13)
    at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:74)
    at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:130)
    at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
    ... 17 more
2012-04-07 21:08:08 [INFO] [Citizens] An error has occurred, please wait while it is sent to the developers...
2012-04-07 21:08:10 [INFO] [Citizens] <html>
2012-04-07 21:08:10 [INFO] [Citizens] <head>
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
2012-04-07 21:08:10 [INFO] [Citizens] <meta name=â€?keywordsâ€? content=â€?Citizens,CitizensNPCs,NPCs for bukkit,bukkit,npcsâ€?>
2012-04-07 21:08:10 [INFO] [Citizens] <meta name=â€?descriptionâ€? content=â€?CitizensNPCs | Citizens - NPCs for Bukkitâ€?>
2012-04-07 21:08:10 [INFO] [Citizens] <meta name="copyright" content="&copy; 2012 CitizensNPCs. All rights reserved.">
2012-04-07 21:08:10 [INFO] [Citizens] <title>Citizens | CitizensNPCs - NPCs for Bukkit</title>
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <link rel="icon" href="http://citizensnpcs.net/favicon.ico" type="image/x-icon">
2012-04-07 21:08:10 [INFO] [Citizens] <link rel="shortcut icon" href="http://citizensnpcs.net/favicon.ico" type="image/x-icon">
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <script type="text/javascript" src="http://use.typekit.com/cui2twk.js"></script>
2012-04-07 21:08:10 [INFO] [Citizens] <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <link href="assets/css/reset.css" rel="stylesheet" type="text/css" />
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens]   <link href="assets/css/style.css" rel="stylesheet" type="text/css" />
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <link rel="canonical" href="http://citizensnpcs.net/" />
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <script src="assets/js/jquery.js" type="text/javascript"></script>
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <script type="text/javascript">
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens]   var _gaq = _gaq || [];
2012-04-07 21:08:10 [INFO] [Citizens]   _gaq.push(['_setAccount', 'UA-29470147-3']);
2012-04-07 21:08:10 [INFO] [Citizens]   _gaq.push(['_trackPageview']);
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens](function%28%29 {
2012-04-07 21:08:10 [INFO] [Citizens]     var ga = document.createElement%28'script'%29; ga.type =) + '.google-analytics.com/ga.js';
2012-04-07 21:08:10 [INFO] [Citizens]     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
2012-04-07 21:08:10 [INFO] [Citizens]   })();
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] </script>
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] </head>
2012-04-07 21:08:10 [INFO] [Citizens] <body>
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] <div id="wrapper">
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens]   <div id="header">
2012-04-07 21:08:10 [INFO] [Citizens]       <h1 class="logo">Citizens - CitizensNPCs - NPCs for bukkit!</h1>
2012-04-07 21:08:10 [INFO] [Citizens]   </div> 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens]   <div id="content">
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="mainbox">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]               <h2>NOW BETA TESTING</h2>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Itâ€™s finally here! Citizens2 is the exciting new rewrite of the Citizens plugin you know and love, 
2012-04-07 21:08:10 [INFO] [Citizens]               <br/> with more features and extendability than ever before!
2012-04-07 21:08:10 [INFO] [Citizens]               The new Citizens2 API enables developers to easily utilize all types of NPC traits and abilities to help create more Characters
2012-04-07 21:08:10 [INFO] [Citizens]               than ever before.  
2012-04-07 21:08:10 [INFO] [Citizens]               Users will love the ability to create NPC mobs, all with the same control you would expect from Citizens. 
2012-04-07 21:08:10 [INFO] [Citizens]               <br/>Weâ€™re excited to see how you will use Citizens2!</p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]  
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="community">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]               <h2>CITIZENS COMMUNITY</h2>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>You can always find the latest information about Citizens and its Characters on our wiki.</p>
2012-04-07 21:08:10 [INFO] [Citizens]               <a target="#" href="http://wiki.citizensnpcs.net">http://wiki.citizensnpcs.net</a>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Please report any issues at <a href="http://issues.citizensnpcs.net/">http://issues.citizensnpcs.net</a></p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="testing">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]               <h2>TESTING THE WATERS</h2>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Looking for bleeding edge? Download our latest developmental builds.</p> 
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Latest Developmental: <a target="#" href="http://ci.citizensnpcs.net/job/Citizens2/lastSuccessfulBuild/">
2012-04-07 21:08:10 [INFO] [Citizens]               #96             </a></p>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Latest Developmental API: <a target="#" href="http://ci.citizensnpcs.net/job/CitizensAPI/lastSuccessfulBuild/">
2012-04-07 21:08:10 [INFO] [Citizens]               #56             </a></p> 
2012-04-07 21:08:10 [INFO] [Citizens]               </p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="donate">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]           <h2>CAVE OF DONATIONS</h2>
2012-04-07 21:08:10 [INFO] [Citizens]           <p>Citizens wouldnâ€™t be here without the work of a dedicated team of individuals. Like what weâ€™re doing? Let us know with your donations! 
2012-04-07 21:08:10 [INFO] [Citizens]           <br/>
2012-04-07 21:08:10 [INFO] [Citizens]           <a target="#" href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=theapunch%40yahoo%2ecom&lc=US&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted">Donate to aPunch</a><br/>
2012-04-07 21:08:10 [INFO] [Citizens]           <a target="#" href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=CEQD6UNQHUG3C&lc=US&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted">Donate to fullwall</a>
2012-04-07 21:08:10 [INFO] [Citizens]           </p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="download">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]               <h2>DOWNLOAD CITIZENS <br/> FOR BUKKIT</h2>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Latest Release: <a target="#" href="http://ci.citizensnpcs.net/job/Citizens2/Release/">
2012-04-07 21:08:10 [INFO] [Citizens]               #               </a></p>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Latest API Release: <a target="#" href="http://ci.citizensnpcs.net/job/CitizensAPI/Release/">
2012-04-07 21:08:10 [INFO] [Citizens]               #               </a></p>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>BukkitDev Page: <a target="#" href="http://dev.bukkit.org/server-mods/citizens/">Citizens</a></p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="underground">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]               <h2>THE UNDERGROUND</h2>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Visit us on irc.esper.net in the #citizens channel to watch development in real-time or to ask questions to dedicated users and developers.</p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]       <div id="credits">
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="transparency"></div>
2012-04-07 21:08:10 [INFO] [Citizens]           <div class="content">
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Sponsored by <a target="#" href="http://creeperhost.net">CreeperHost</a></p>
2012-04-07 21:08:10 [INFO] [Citizens]               <p>Copyright 2012 Â© CitizensNPCs.net</p>
2012-04-07 21:08:10 [INFO] [Citizens]           </div>
2012-04-07 21:08:10 [INFO] [Citizens]       </div>
2012-04-07 21:08:10 [INFO] [Citizens]   </div> 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] </div> 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] 
2012-04-07 21:08:10 [INFO] [Citizens] </body>
2012-04-07 21:08:10 [INFO] [Citizens] </html>
2012-04-07 21:08:10 [INFO] [Citizens] Below is the stacktrace that has been transmitted to the developers, no other information has been included other than Citizens version information.

**Comment by TomYaMee** [comment]
woah,.... i didnt know i copied the server log will become like this...

**Comment by bloodriot** [comment]
Please provide the following information:
1) A copy of your quests.yml file.
2) The version of citizens you are running.
3) The version of bukkit you are running.
4) Any plugins you may have installed along with their versions.

Do the above and I'll take a look at it.

**Comment by phonix420** [comment]
Quests.yml : http://pastebin.com/Ptz2VhtA
Citizens 1.2
CB #2149

Plugins:
Blocklog
Bookworm
Catacombs
Chatmanager
Chestharvester
Citizens
Commandhelper
Courier
Essentials
iConomy
LWC
MagicSpells
McMMO
Mobarena
Multiverse
NoCheat
PEX
RegionSelfService
Showcasestandalone
SimpleSpleef
Stargate
TempleCraft
Timeismoney
Votifier
WorldEdit
WorldGuard

Sorry for lack of initial info, someone told me not to bother posting here because no one responds, so I just left a response to the OP. Thanks for any help you can provide!

(as a side note, I've been using citizens since I started my server 3 months ago, even before I started adding questers, NPC's would never respond to being clicked on even for conversation, I tried adding the interact permission to all groups, as well as thoroughly checking the config file thinking maybe interaction was disabled)

Also, I'm not receiving the HTML in my server log like TomYaMee.

**Comment by bloodriot** [comment]
Looking into it.

**Comment by bloodriot** [comment]
Your quest data seems to be fine as it works on my server.

<table>
<tr><td>Plugin:</td><td>Version:</td></tr>
<tr><td>Bukkit</td><td>1.2.5-R1.0-b2149jnks</td></tr>
<tr><td>Citizens</td><td>5b4e6aef9f</td></tr>
<tr><td>Vault</td><td>1.2.12-b136</td></tr>
<tr><td>Spout</td><td>1062</td></tr>
<tr><td>iConomy</td><td> v7.0 (April Fools version)</tr>
</table>


This is likely an issue with other plugins conflicting with Citizens.
You may need to disable them all and re-enable them one by one until you find the plugin that is breaking it.

If you do that and are still unable to figure it out, you can pm me a copy of your plugins folder and I'll load it on my server.
