### ISSUE TITLE
Problem by initializing iConomy

### ISSUE THREAD

**Issue by sizilium** [CitizensDev/Citizens#959]
Bukkit 1.2.5 R1.0
Citizens 1.2
iConomy 7.0 (april fool, its the version 6.0.10b)
...

I can create npc and toggle to trader.
Selling or buying does not work because Citizens say there is no economy plugin around.

Logfile:

2012-04-06 00:06:43 [INFO] [Citizens] Enabling Citizens v1.2
2012-04-06 00:06:43 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
2012-04-06 00:06:44 [SEVERE] Error occurred while enabling Citizens v1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
    at net.citizensnpcs.Economy.init(Economy.java:21)
    at net.citizensnpcs.Citizens.onEnable(Citizens.java:122)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more

**Comment by sizilium** [comment]
By the way: Loading existing npcs from npc-profiles.yml does not work anymore (reload, restart does not help) but i think this has to do with iConomy exception...

**Comment by imfzeronull** [comment]
Hi 
I have the same Problem

I have tried older versions of IConomy <- same exception
without IConomy plugin files <- same exception
I have edit the citizens.yml file. From "use-economy: true" in "use-economy: false" <- same exception

maybe the information is helpful

**Comment by sizilium** [comment]
Citizens 1.2 still doesn't work with iConomy 6.0.10b!

**Comment by aufdemrand** [comment]
Install Vault... Citizens 1 is dependent on that since Minecraft 1.2.

**Comment by sizilium** [comment]
Works fine with Vault. Thank you.

Why isn't it documented? The bukkit dev page is misleading and tells something about iConomy 4,5,6 support...

**Comment by aufdemrand** [comment]
Vault isn't an economy, it's a bridge to your economy plugin.  So it does support iConomy 4,5 and 6.

That being said... you are right about not informing, and we will get that added.
