### ISSUE TITLE
Found error in console. Figured I would post it.

### ISSUE THREAD

**Issue by BakedBrotato** [CitizensDev/Citizens#961]
2012-04-05 22:16:33 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.utils.EntityUtils.getMonsterName(Lorg/bukkit/entity/Entity;)Ljava/lang/String;
at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:122)
at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:1)
at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:150)
at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:35)
at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-04-05 22:16:33 [WARNING] Task of 'Citizens' generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.utils.EntityUtils.getMonsterName(Lorg/bukkit/entity/Entity;)Ljava/lang/String;
at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:122)
at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:1)
at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:150)
at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:35)
at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:59)
at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)

**Comment by bloodriot** [comment]
Please post your version numbers.

Can you recreate this error message?
- If so, what steps are needed to do so?

It sounds like its failing to look up an entity name when dealing with a flag.

**Comment by BakedBrotato** [comment]
1.2.5 bukkit server.  Craftbukkit version: 1.2.5 (build # uncertain: first stable 1.2.5 R1)  Citizens version: 1.2

Error messages spam server log. Cause is autonomous.
Also, This.

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.api.event.CitizensEvent.<init>(Ljava/lang/String;)V
at net.citizensnpcs.questers.api.events.QuestEvent.<init>(QuestEvent.java:14)
at net.citizensnpcs.questers.api.events.QuestBeginEvent.<init>(QuestBeginEvent.java:13)
at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:74)
at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:130)
at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
... 18 more
2012-04-13 18:43:36 [SEVERE] Could not pass event NPCTargetEvent to Citizens
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:978)
at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.api.event.CitizensEvent.<init>(Ljava/lang/String;)V
at net.citizensnpcs.questers.api.events.QuestEvent.<init>(QuestEvent.java:14)
at net.citizensnpcs.questers.api.events.QuestBeginEvent.<init>(QuestBeginEvent.java:13)
at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:74)
at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:130)
at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
... 18 more
2012-04-13 18:43:37 [SEVERE] Could not pass event NPCTargetEvent to Citizens
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:978)
at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.api.event.CitizensEvent.<init>(Ljava/lang/String;)V
at net.citizensnpcs.questers.api.events.QuestEvent.<init>(QuestEvent.java:14)
at net.citizensnpcs.questers.api.events.QuestBeginEvent.<init>(QuestBeginEvent.java:13)
at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:74)
at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:130)
at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
... 18 more
2012-04-13 18:43:38 [SEVERE] Could not pass event NPCTargetEvent to Citizens
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:978)
at net.minecraft.server.Packet7UseEntity.handle(SourceFile:33)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.api.event.CitizensEvent.<init>(Ljava/lang/String;)V
at net.citizensnpcs.questers.api.events.QuestEvent.<init>(QuestEvent.java:14)
at net.citizensnpcs.questers.api.events.QuestBeginEvent.<init>(QuestBeginEvent.java:13)
at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:74)
at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:130)
at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:73)
at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
... 18 more

**Comment by CR33PAH** [comment]
Have you tried reinstalling the plugin? That sometimes helps.
