### ISSUE TITLE
Guard bug wont do anything.

### ISSUE THREAD

**Issue by mitmit2** [CitizensDev/Citizens#963]
When i make a guard and do everthing how its suppose to it does nothing so i save all of it then restart server the gaurd walks to the mob and kills it but after that it stop i use citizen 1.2 and get following error :

Its the whole log maybe easier to figure it out :)

182 recipes
27 achievements
12:54:48 [INFO] Starting minecraft server version 1.2.5
12:54:48 [INFO] Loading properties
12:54:48 [INFO] Starting Minecraft server on 5.82.215.180:25565
12:54:48 [WARNING] ***\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
12:54:48 [WARNING] The server will make no attempt to authenticate usernames. Be
ware.
12:54:48 [WARNING] While this makes the game possible to play without internet a
ccess, it also opens up the ability for hackers to connect with any username the
y choose.
12:54:48 [WARNING] To change this, set "online-mode" to "true" in the server.pro
perties file.
12:54:49 [INFO] This server is running CraftBukkit version git-Bukkit-1.2.5-R1.0
-b2149jnks (MC: 1.2.5) (Implementing API version 1.2.5-R1.0)
12:54:49 [INFO] [CraftBukkitUpToDate] Loading CraftBukkitUpToDate v2.8.0
12:54:49 [INFO] [Vault] Loading Vault v1.2.13-b148
12:54:49 [INFO] [Pail] Loading Pail v0.8
12:54:49 [INFO] [iConomy] Loading iConomy v7.0
12:54:49 [INFO] [PailPlus] Loading PailPlus v0.3
12:54:49 [INFO] [qQuests] Loading qQuests v0.01.95
12:54:49 [INFO] [Citizens] Loading Citizens v1.2
12:54:49 [INFO] [Vault] Enabling Vault v1.2.13-b148
12:54:49 [INFO] [Vault][Economy] iConomy 6 found: Waiting
12:54:49 [INFO] [Vault][Permission] SuperPermissions loaded as backup permission
 system.
12:54:49 [INFO] [Vault] Enabled Version 1.2.13-b148
12:54:49 [INFO] [Pail] Enabling Pail v0.8
12:54:50 [INFO] Preparing level "New Survival"
12:54:50 [INFO] Default game type: 1
12:54:50 [INFO] Preparing start region for level 0 (Seed: -1660954792124779731)
12:54:51 [INFO] Preparing start region for level 1 (Seed: -6988460734474634363)
12:54:51 [INFO] Preparing spawn area: 8%
12:54:52 [INFO] Preparing start region for level 2 (Seed: -6988460734474634363)
12:54:52 [INFO] Preparing spawn area: 52%
12:54:52 [INFO] [CraftBukkitUpToDate] Enabling CraftBukkitUpToDate v2.8.0
12:54:52 [INFO] CraftBukkitUpToDate version 2.8.0 is enabled!
12:54:52 [INFO] [iConomy] Enabling iConomy v7.0
12:54:52 [INFO] [iConomy - April Fools] Enabled (29 ms)
12:54:52 [INFO] [iConomy] Hello, I'm Nijikokun. Yes, this is an April Fools joke
, but '/money top' was fixed! Enjoy :) - Rare Version!
12:54:52 [INFO] [Vault][Economy] iConomy 6 hooked.
12:54:52 [INFO] [iConomy - April Fools] Purged accounts with default balance.
12:54:52 [INFO] [PailPlus] Enabling PailPlus v0.3
12:54:52 [INFO] [qQuests] Enabling qQuests v0.01.95
12:54:52 [INFO] [qQuests] [Economy] Enabled - Vault And Economy Plugin Found.
12:54:52 [INFO] [qQuests] [Permissions] Enabled - Vault And Permissions Plugin F
ound.
12:54:52 [INFO] [qQuests] 1 Quests Successfully Loaded Into Memory.
12:54:52 [INFO] [qQuests] by Quaz3l: Enabled
12:54:52 [INFO] [Citizens] Enabling Citizens v1.2
12:54:52 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester,
 trader, wizard
12:54:53 [INFO] [Citizens] version [1.2] loaded.
12:54:53 [INFO] Server permissions file permissions.yml is empty, ignoring it
12:54:53 [INFO] Done (3.163s)! For help, type "help" or "?"
12:55:14 [INFO] [Citizens] Loaded 7 NPCs.
12:55:14 [INFO] [Citizens] Loaded 0 quests.
12:55:14 [WARNING] Task of 'Citizens' generated an exception
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayer
Groups(Permission_SuperPerms.java:91)
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.j
ava:522)
        at net.citizensnpcs.permissions.PermissionManager.getGroups(PermissionMa
nager.java:105)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:99)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)

```
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
```

terator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:136)
        at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:
142)
        at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:33)
        at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:
57)
        at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
        at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
        at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
        at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
        at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
12:55:14 [WARNING] Task of 'Citizens' generated an exception
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayer
Groups(Permission_SuperPerms.java:91)
        at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.j
ava:522)
        at net.citizensnpcs.permissions.PermissionManager.getGroups(PermissionMa
nager.java:105)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:99)
        at net.citizensnpcs.guards.flags.FlagSorter$6.apply(FlagSorter.java:76)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645)

```
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
```

terator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:136)
        at net.citizensnpcs.guards.flags.FlagSorter.getPossible(FlagSorter.java:
142)
        at net.citizensnpcs.guards.flags.FlagList.process(FlagList.java:33)
        at net.citizensnpcs.guards.flags.FlagList.processEntities(FlagList.java:
57)
        at net.citizensnpcs.guards.Targeter.findTarget(Targeter.java:14)
        at net.citizensnpcs.guards.types.Bouncer.findTarget(Bouncer.java:24)
        at net.citizensnpcs.guards.types.Bouncer.updateStatus(Bouncer.java:64)
        at net.citizensnpcs.guards.Guard.updateStatus(Guard.java:135)
        at net.citizensnpcs.guards.GuardTask.run(GuardTask.java:23)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
12:55:14 [INFO] [qQuests] Server was pung... Thank You! :)
12:55:22 [INFO] CButD: Plugin-Update-Check started
12:55:24 [INFO] No source for qQuests.jar ask the Author to add it to dev.bukkit
.org
12:55:24 [INFO] CraftBukkitUpToDate.jar changed, but you have it in your Update-
Folder.
12:55:24 [INFO] CButD: Plugin-Update-Check finished

**Comment by bloodriot** [comment]
<table>
<tr><td>Plugin:</td><td>Version:</td></tr>
<tr><td>Citizens</td><td>5b4e6aef9f</td></tr>
<tr><td>Bukkit</td><td>1.2.5-R1.0-b2149jnks</td></tr>
<tr><td>Vault</td><td>1.2.12-b136</td></tr>
<tr><td>Spout</td><td>1062</td></tr>
</table>


I was able to recreate the error message.
- The problem is asking for the users group permission when the SuperPerms has no data.
  -- I assume as part of a selection call for who should the guard target.
- I am assuming that you don't have anything configured for group permissions.
  -- So I used an empty permissions.yml file when testing.

Commands Used:
/npc create Guard
/toggle guard
/guard bouncer
/guard addflag 1 All -a
/guard aggro

Thoughts:
- The guard will still attack even with this error message.
- The ability to use group based flags is most likely disabled due to this.

Submitting a pull request to make the error message a bit nicer.
It should also not flood the server with Unhandled exception errors when this triggers.
