### ISSUE TITLE
Repeatable quests aren't repeatable

### ISSUE THREAD

**Issue by defaultsucks** [CitizensDev/Citizens#97]
After I finish a quest that has repeatable set to true and come back to the npc, he just says "No quests are available" until I log out. Then I can do the quest one time again and the problem repeats.

After I log out though it does ask me to accept the quest by right clicking and when I do that it displays this error:

Could not pass event ENTITY_TARGET to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.quests.QuestProgress.<init>(QuestProgress.java:26)
    at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:52)
    at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:155)
    at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:158)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:112)
    at org.bukkit.plugin.java.JavaPluginLoader$64.execute(JavaPluginLoader.java:691)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:321)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:870)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by fullwall** [comment]
Hmm... rather than 'true' it should be repeatable: int where int can be -1 for unlimited repeats... Can you test this format please?

**Comment by fullwall** [comment]
Sorry, it should be repeats: int.

**Comment by defaultsucks** [comment]
I changed it to repeats: 1 and whenever I finish the quest once and go back, it just says "No quests available". If I log out and log back in, it says it's available again but when I try to accept it, it throws this error in the console again: 

Could not pass event ENTITY_TARGET to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.quests.QuestProgress.<init>(QuestProgress.java:26)
    at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:52)
    at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:155)
    at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:158)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:112)
    at org.bukkit.plugin.java.JavaPluginLoader$64.execute(JavaPluginLoader.java:691)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.citizensnpcs.listeners.PlayerListen.onPlayerInteractEntity(PlayerListen.java:78)
    at org.bukkit.plugin.java.JavaPluginLoader$12.execute(JavaPluginLoader.java:321)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:870)
    at net.minecraft.server.Packet7UseEntity.a(SourceFile:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

If I do /citizens reload, that fixes it and I can take the quest again. However this will happen forever, not just 1 time.

**Comment by fullwall** [comment]
Can you paste the quest you're using for this?

**Comment by defaultsucks** [comment]
Friend_in_need:
    texts:
        description: Please deliver a fish to my friend in the Mora dungeon. He's badly hurt.
        completion: <g>Thank you so much! Have this.
        acceptance: <g>Quest <y>accepted<g>.
    repeats: 1
    objectives:
        '0':
            '0':
                type: delivery
                npcdestination: 20
                materialid: 350
                amount: 1
                message: Thank you so much kind sir! Go back to my friend up above.
    rewards:
        '0':
            type: item
            id: 264
            amount: 20
            take: false

**Comment by RincewindSCC** [comment]
Might not be quest repeats, also happens to me but on other quests too that aren't repeatable. Seems to occur more often with more people online also. Whenever the npc is right clicked the server will freeze up for a few seconds. Happens since #148 for me.

On a side note if this error doesn't occur, repeatable quests work fine. 

2011-09-11 22:45:01 [SEVERE] Could not pass event ENTITY_TARGET to Citizens
java.lang.NullPointerException
    at net.citizensnpcs.questers.quests.QuestProgress.<init>(QuestProgress.java:26)
    at net.citizensnpcs.questers.QuestManager.assignQuest(QuestManager.java:52)
    at net.citizensnpcs.questers.Quester.attemptAssign(Quester.java:155)
    at net.citizensnpcs.questers.Quester.onRightClick(Quester.java:70)
    at net.citizensnpcs.resources.npclib.HumanNPC.callRightClick(HumanNPC.java:158)
    at net.citizensnpcs.listeners.EntityListen.onEntityTarget(EntityListen.java:112)

**Comment by fullwall** [comment]
What the error essentially means is that it's trying to fetch the objectives for a particular quest step, but they're missing. I'll look more into it in the meantime.

**Comment by defaultsucks** [comment]
This is fixed but it somehow mutated into a new issue.
