### ISSUE TITLE
INTERNAL SERVER ERROR???

### ISSUE THREAD

**Issue by RDDMF** [CitizensDev/Citizens#971]
hi, i was testing my new wizard and out of curiosity(sorry for poor english) I selected falling block. and now when I try to join it says internal server error!? What can I do? Below the error..
thanks in advance, RDDMF

19:58:56 [INFO] Stefffff95 [/5.133.254.110:63694] logged in with entity id 136 a
t ([world] -471.5625, 63.0, 315.25)
19:58:56 [INFO] Disconnecting Stefffff95 [/5.133.254.110:63694]: Internal server
 error
19:58:56 [WARNING] Failed to handle packet: java.lang.IllegalArgumentException:
Don't know how to add class net.minecraft.server.EntityFallingBlock!
java.lang.IllegalArgumentException: Don't know how to add class net.minecraft.se
rver.EntityFallingBlock!
        at net.minecraft.server.EntityTrackerEntry.b(EntityTrackerEntry.java:388
)
        at net.minecraft.server.EntityTrackerEntry.updatePlayer(EntityTrackerEnt
ry.java:229)
        at net.minecraft.server.EntityTracker.track(EntityTracker.java:33)
        at net.minecraft.server.WorldManager.a(WorldManager.java:16)
        at net.minecraft.server.World.c(World.java:927)
        at net.minecraft.server.WorldServer.c(WorldServer.java:171)
        at net.minecraft.server.World.addEntity(World.java:920)
        at net.minecraft.server.World.addEntity(World.java:866)
        at net.minecraft.server.ServerConfigurationManager.c(ServerConfiguration
Manager.java:142)
        at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:129)
        at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:94)
        at net.minecraft.server.Packet1Login.handle(SourceFile:68)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:48)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:6
1)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
19:58:57 [INFO] Stefffff95 lost connection: disconnect.endOfStream

**Comment by notcam45** [comment]
Try deleting your Citizens folder and restarting your server. You will lose all your NPC data but I don't know what else to say. If that does not fix it, then this is not a problem with Citizens.
