### ISSUE TITLE
Could not load Citizens 1.2 (o.O)  - Requires Vault ?

### ISSUE THREAD

**Issue by MinecraftOrti** [CitizensDev/Citizens#976]
12:58:52 [SCHWERWIEGEND] Error occurred while enabling Citizens v1.2 (Is it up t
o date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at net.citizensnpcs.Economy.init(Economy.java:21)
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:122)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:336)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232
)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

Citizens requires now Vault? Could you please update this on the Cititzens-Bukkit Page? :D

Thank you very much!

**Comment by onlineman** [comment]
they do 
 now i know too
