### ISSUE TITLE
API Issue saveState() in NPCProperties

### ISSUE THREAD

**Issue by TruDan** [CitizensDev/Citizens#984]
Hi, i am trying to use the API to make my own NPC type. I have done this successfully except on startup i get this error:
2012-04-18 21:49:22 [WARNING] Task of 'Citizens' generated an exception
java.lang.NullPointerException
    at com.sirdrakeheart.plotagent.AgentProperties.saveState(AgentProperties.java:56)
    at com.sirdrakeheart.plotagent.AgentProperties.loadState(AgentProperties.java:46)
    at net.citizensnpcs.properties.PropertyManager.load(PropertyManager.java:46)
    at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:162)
    at net.citizensnpcs.Citizens.setupNPCs(Citizens.java:279)
    at net.citizensnpcs.Citizens.access$000(Citizens.java:63)
    at net.citizensnpcs.Citizens$3.run(Citizens.java:149)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:517)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

But, i am using the exact same methods as you are in your NPC types, and i do not fully understand why its doing this :S

**Comment by fullwall** [comment]
I would use the Citizens2 API instead.

**Comment by TruDan** [comment]
I would however I'm not sure when citizens 2 will be released and I need the plugin currently, I managed to fix it with my project setup, can't remember exactly how.
