### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by XBott94** [CitizensDev/Citizens#999]
when i start the server the console shos tis:
... 12 more
at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
at net.citizensnpcs.Citizens.onEnable(Citizens.java:122)
at net.citizensnpcs.Economy.init(Economy.java:21)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy

> 2

**Comment by fullwall** [comment]
Download vault.
